import type { StackPageData } from "./pseoData";

export const batch5StackPages: StackPageData[] = [
  {
    slug: "injury-recovery-stack-advanced",
    name: "Advanced Injury Recovery Stack",
    h1: "Advanced Injury Recovery Stack: BPC-157, TB-500 & GHK-Cu",
    metaDescription: "Advanced triple-peptide injury recovery stack combining BPC-157, TB-500, and GHK-Cu for comprehensive tissue repair. Protocol, dosing, and evidence.",
    tagline: "A comprehensive three-peptide protocol for serious injuries requiring both localized and systemic healing support.",
    peptides: ["bpc-157", "tb-500", "ghk-cu"],
    peptideNames: ["BPC-157", "TB-500", "GHK-Cu"],
    primaryGoal: "injury-recovery",
    goalSlugs: ["injury-recovery", "joint-recovery", "skin-health"],
    synergyExplanation: "BPC-157 provides localized tendon and ligament healing at the injury site. TB-500 delivers systemic anti-inflammatory and tissue repair throughout the body. GHK-Cu supports skin healing, collagen synthesis, and connective tissue remodeling. Together they cover every layer of tissue repair from deep tendon to superficial wound healing.",
    protocol: "BPC-157 250-500 mcg daily near injury site. TB-500 2.5 mg twice weekly for 4 weeks loading then weekly maintenance. GHK-Cu 1-2 mg daily rotating injection sites. Run stack for 6-8 weeks with 4-week break between cycles.",
    dosingSchedule: [
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily, post-activity near injury site", route: "Subcutaneous injection" },
      { peptide: "TB-500", dose: "2.5 mg", timing: "Twice weekly for 4 weeks, then weekly", route: "Subcutaneous injection" },
      { peptide: "GHK-Cu", dose: "1-2 mg", timing: "Daily, rotating injection sites", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Athletes recovering from moderate-to-severe injuries including tendon ruptures, ligament sprains, and post-surgical recovery. Also suitable for individuals with chronic injuries that haven't responded to single-peptide protocols.",
    evidenceBase: "Strong preclinical evidence supports all three peptides individually for tissue repair. BPC-157 and TB-500 have the most peer-reviewed research for tendon and muscle healing. GHK-Cu's role in collagen synthesis is well-established in dermatological research.",
    costEstimate: "$180-350 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Can I drop GHK-Cu and run just BPC-157 with TB-500?", a: "Yes — the two-peptide stack is the most common and well-documented protocol. GHK-Cu is optional for those prioritizing skin and connective tissue healing." },
      { q: "Should I adjust BPC-157 placement when running all three?", a: "Place BPC-157 at the primary injury site. TB-500 can go in the abdomen. GHK-Cu needs rotating sites due to injection-site reactions." },
    ],
  },
  {
    slug: "gh-secretagogue-complete-stack",
    name: "Complete GH Secretagogue Stack",
    h1: "Complete GH Secretagogue Stack: Ipamorelin & CJC-1295 Protocol",
    metaDescription: "The complete GH secretagogue stack — Ipamorelin with CJC-1295 for amplified GH pulses. Dosing schedule, timing, and cycle protocol.",
    tagline: "The gold-standard GH peptide combination for body composition, recovery, and anti-aging.",
    peptides: ["ipamorelin", "cjc-1295"],
    peptideNames: ["Ipamorelin", "CJC-1295"],
    primaryGoal: "muscle-growth",
    goalSlugs: ["muscle-growth", "fat-loss", "anti-aging"],
    synergyExplanation: "Ipamorelin acts as a GHRP, triggering pituitary GH release. CJC-1295 (no-DAC) acts as a GHRH analogue, raising baseline GH production. Together they produce amplified, sustained GH pulses that mimic youthful physiology more closely than either peptide alone.",
    protocol: "Ipamorelin 200-300 mcg + CJC-1295 no-DAC 100 mcg combined in one syringe before bed on an empty stomach. 2-hour fast before dosing. 8 weeks on, 4 weeks off. Monitor IGF-1 every 8-12 weeks.",
    dosingSchedule: [
      { peptide: "Ipamorelin", dose: "200-300 mcg", timing: "Before bed, empty stomach", route: "Subcutaneous injection" },
      { peptide: "CJC-1295 (no-DAC)", dose: "100 mcg", timing: "Before bed, same syringe as Ipamorelin", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults 30+ seeking body composition improvement, better sleep quality, enhanced recovery, and anti-aging benefits. Particularly effective for those with declining GH markers on blood work.",
    evidenceBase: "Ipamorelin has Phase I/II clinical data for GH stimulation. CJC-1295 has clinical trials demonstrating sustained GH elevation. The combination is the most researched GH secretagogue stack in the biohacking community.",
    costEstimate: "$70-160 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Do I need CJC-1295 with DAC or without DAC?", a: "No-DAC (Mod GRF 1-29) is preferred for this stack. DAC version extends half-life to 8+ days, creating a GH bleed rather than natural pulses. No-DAC produces more physiological GH patterns." },
      { q: "Can I add Sermorelin instead of CJC-1295?", a: "Yes — Sermorelin is a milder GHRH analogue with more clinical history. It produces less GH elevation but is suitable for those wanting a gentler protocol or who have a Sermorelin prescription." },
    ],
  },
  {
    slug: "cognitive-enhancement-stack",
    name: "Cognitive Enhancement Stack",
    h1: "Cognitive Enhancement Stack: Semax & Selank Protocol",
    metaDescription: "The nootropic peptide stack combining Semax and Selank for focus, memory, and anxiety-free cognitive performance. Dosing and cycling protocol.",
    tagline: "The most popular nootropic peptide combination for sharp focus without anxiety.",
    peptides: ["semax", "selank"],
    peptideNames: ["Semax", "Selank"],
    primaryGoal: "cognitive-performance",
    goalSlugs: ["cognitive-performance", "focus", "anxiety-reduction"],
    synergyExplanation: "Semax upregulates BDNF and NGF for neuroplasticity, focus, and memory. Selank modulates GABAergic activity for anxiety reduction without sedation. Together they provide calm, focused cognition — the anxiolytic effects of Selank balance the stimulating effects of Semax.",
    protocol: "Semax 200-400 mcg intranasal in the morning. Selank 400-800 mcg intranasal in the morning and optionally early afternoon. Cycle 4-8 weeks with 1-2 week breaks. Can be used as needed for cognitive demands.",
    dosingSchedule: [
      { peptide: "Semax", dose: "200-400 mcg", timing: "Morning, intranasal", route: "Intranasal spray" },
      { peptide: "Selank", dose: "400-800 mcg", timing: "Morning and early afternoon", route: "Intranasal spray" },
    ],
    whoIsItFor: "Professionals, students, and biohackers seeking improved focus, working memory, and verbal fluency without the anxiety or crash of traditional stimulants. Also suitable for those with mild cognitive decline or brain fog.",
    evidenceBase: "Both peptides have Russian clinical trial data supporting their cognitive and anxiolytic effects. Semax has the stronger evidence for cognitive enhancement (stroke recovery, ADHD). Selank has clinical data for generalized anxiety disorder.",
    costEstimate: "$60-140 for a 4-week cycle depending on vendor",
    faqItems: [
      { q: "Can I take both in the same nasal spray bottle?", a: "It is safer to keep them in separate bottles and administer sequentially. Some users combine them but peptide stability in mixed solutions is not well studied." },
      { q: "Will this stack keep me awake at night?", a: "Semax can be stimulating — avoid dosing after 2 PM. Selank may promote calm that helps sleep onset in some users." },
    ],
  },
  {
    slug: "gut-healing-restoration-stack",
    name: "Gut Healing & Restoration Stack",
    h1: "Gut Healing & Restoration Stack: BPC-157, KPV & VIP Protocol",
    metaDescription: "Comprehensive gut health peptide stack combining BPC-157, KPV, and VIP for intestinal barrier repair and microbiome support.",
    tagline: "A targeted peptide protocol for gut barrier repair, inflammation reduction, and digestive health restoration.",
    peptides: ["bpc-157", "vip"],
    peptideNames: ["BPC-157", "VIP"],
    primaryGoal: "gut-health",
    goalSlugs: ["gut-health", "inflammation"],
    synergyExplanation: "BPC-157 supports gut mucosal healing and barrier repair through angiogenesis and cytoprotective mechanisms. VIP regulates gut motility, reduces intestinal inflammation, and supports the gut-brain axis. Together they address both structural integrity and functional regulation of the digestive tract.",
    protocol: "BPC-157 250-500 mcg daily near the abdomen for 6-8 weeks. VIP dosing varies by protocol — typically 50-100 mcg once or twice daily. Start BPC-157 first for 2 weeks before adding VIP to assess individual response.",
    dosingSchedule: [
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily, abdominal area", route: "Subcutaneous injection" },
      { peptide: "VIP", dose: "50-100 mcg", timing: "Once or twice daily, morning preferred", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Individuals with chronic digestive issues including IBS, leaky gut, SIBO recovery, and inflammatory bowel conditions. Also suitable for those on long-term NSAID therapy seeking gut protection.",
    evidenceBase: "BPC-157 has strong preclinical evidence for gut mucosal healing including near-complete prevention of NSAID-induced ulcers in animal models. VIP has research supporting its role in gut motility and intestinal anti-inflammatory effects.",
    costEstimate: "$80-180 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Should I take BPC-157 orally or by injection for gut health?", a: "Injectable BPC-157 has higher bioavailability and stronger preclinical evidence for gut healing. Oral BPC-157 may still provide benefits for some users." },
      { q: "Can I use this stack alongside probiotics?", a: "Yes — probiotics support the microbiome while BPC-157 supports the intestinal barrier. They work through complementary mechanisms." },
    ],
  },
  {
    slug: "bodybuilding-prep-stack",
    name: "Bodybuilding Contest Prep Stack",
    h1: "Bodybuilding Contest Prep Stack: Ipamorelin, CJC-1295 & AOD-9604",
    metaDescription: "Competition prep peptide stack for bodybuilders combining Ipamorelin, CJC-1295, and AOD-9604 for fat loss and muscle preservation.",
    tagline: "A three-peptide protocol designed for the unique demands of contest preparation — fat loss, muscle preservation, and recovery.",
    peptides: ["ipamorelin", "cjc-1295", "aod-9604"],
    peptideNames: ["Ipamorelin", "CJC-1295", "AOD-9604"],
    primaryGoal: "fat-loss",
    goalSlugs: ["fat-loss", "muscle-growth", "body-recomposition"],
    synergyExplanation: "Ipamorelin/CJC-1295 maintains GH/IGF-1 axis activity during caloric restriction, helping preserve lean mass. AOD-9604 provides targeted lipolytic support for stubborn fat areas. The combination supports body composition goals during the catabolic stress of contest prep.",
    protocol: "Ipamorelin 200-300 mcg + CJC-1295 no-DAC 100 mcg before bed. AOD-9604 300 mcg before fasted morning cardio. Stop GH secretagogues 2-3 weeks before show day to shed water. Maintain AOD-9604 through show week.",
    dosingSchedule: [
      { peptide: "Ipamorelin", dose: "200-300 mcg", timing: "Before bed, empty stomach", route: "Subcutaneous injection" },
      { peptide: "CJC-1295 (no-DAC)", dose: "100 mcg", timing: "Before bed, with Ipamorelin", route: "Subcutaneous injection" },
      { peptide: "AOD-9604", dose: "300 mcg", timing: "Before fasted morning cardio", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Competitive bodybuilders in contest preparation who want to maximize fat loss while preserving lean muscle tissue. Also useful for fitness models and individuals preparing for photo shoots or physique competitions.",
    evidenceBase: "AOD-9604 has clinical data for fat reduction without IGF-1 elevation. The Ipamorelin/CJC-1295 combination is supported by preclinical evidence for GH amplification. The stack is widely used in the bodybuilding community.",
    costEstimate: "$130-280 for a 12-week prep cycle depending on vendor and dosing",
    faqItems: [
      { q: "When should I stop GH secretagogues before a show?", a: "Most competitors stop 2-3 weeks before show day to allow water retention from GH elevation to subside. AOD-9604 does not cause water retention and can continue." },
      { q: "Will this stack prevent muscle loss during prep?", a: "The GH secretagogues support an anabolic environment but don't fully prevent muscle loss during aggressive calorie restriction. Adequate protein intake and resistance training are essential." },
    ],
  },
  {
    slug: "longevity-comprehensive-stack",
    name: "Comprehensive Longevity Stack",
    h1: "Comprehensive Longevity Stack: Epithalon, GHK-Cu & NAD+ Protocol",
    metaDescription: "Anti-aging peptide stack combining Epithalon, GHK-Cu, and NAD+ for cellular health, telomere support, and mitochondrial function.",
    tagline: "A science-backed peptide protocol targeting three core aging mechanisms: telomeres, mitochondria, and cellular repair.",
    peptides: ["epithalon", "ghk-cu"],
    peptideNames: ["Epithalon", "GHK-Cu"],
    primaryGoal: "anti-aging",
    goalSlugs: ["anti-aging", "longevity", "energy"],
    synergyExplanation: "Epithalon activates telomerase to maintain telomere length and regulates pineal function for improved sleep. GHK-Cu supports collagen synthesis, tissue repair, and gene expression for cellular regeneration. Both target fundamental aging pathways through complementary mechanisms.",
    protocol: "Epithalon 5-10 mg daily for 10-20 days, cycled 1-2 times per year. GHK-Cu 1-2 mg daily for 8-12 weeks, cycled with 4-week breaks. The protocols overlap or run sequentially depending on goals.",
    dosingSchedule: [
      { peptide: "Epithalon", dose: "5-10 mg", timing: "Daily for 10-20 day cycle", route: "Subcutaneous injection" },
      { peptide: "GHK-Cu", dose: "1-2 mg", timing: "Daily, rotating sites", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults 40+ serious about cellular anti-aging who want to address aging at the fundamental level. Suitable for those who have optimized sleep, nutrition, and exercise and want additional longevity support.",
    evidenceBase: "Epithalon has 30+ years of Russian research showing lifespan extension in animal models and improved immune function in elderly patients. GHK-Cu has extensive dermatological research for collagen synthesis and wound healing.",
    costEstimate: "$150-250 per Epithalon cycle (1-2x per year) plus $80-180 per GHK-Cu cycle",
    faqItems: [
      { q: "Can I run Epithalon and GHK-Cu at the same time?", a: "Yes — they work through different mechanisms and can be safely combined. Some users prefer to run them sequentially to better assess individual response." },
      { q: "How often should I repeat the Epithalon cycle?", a: "The original Russian research suggests 1-2 cycles per year, typically in spring and fall. Some practitioners recommend up to 3 cycles per year for older adults." },
    ],
  },
  {
    slug: "sleep-recovery-optimization-stack",
    name: "Sleep & Recovery Optimization Stack",
    h1: "Sleep & Recovery Optimization Stack: Ipamorelin, Epithalon & BPC-157",
    metaDescription: "Sleep-enhancing peptide stack combining Ipamorelin, Epithalon, and BPC-157 for deep sleep, recovery, and tissue repair.",
    tagline: "A synergistic protocol targeting sleep quality, overnight recovery, and daily tissue repair through multiple pathways.",
    peptides: ["ipamorelin", "epithalon", "bpc-157"],
    peptideNames: ["Ipamorelin", "Epithalon", "BPC-157"],
    primaryGoal: "sleep-optimization",
    goalSlugs: ["sleep-optimization", "recovery", "anti-aging"],
    synergyExplanation: "Ipamorelin amplifies the nocturnal GH pulse for deeper sleep and overnight tissue repair. Epithalon regulates pineal function and normalizes melatonin production for circadian rhythm support. BPC-157 repairs tissue damage that accumulated during the day. Together they create an optimized overnight recovery environment.",
    protocol: "Ipamorelin 200-300 mcg before bed on empty stomach nightly. Epithalon 5-10 mg daily for 10-20 day cycles. BPC-157 250-500 mcg daily, timing flexible but evening preferred. Cycle Ipamorelin 8 weeks on, 4 weeks off.",
    dosingSchedule: [
      { peptide: "Ipamorelin", dose: "200-300 mcg", timing: "Before bed, empty stomach", route: "Subcutaneous injection" },
      { peptide: "Epithalon", dose: "5-10 mg", timing: "Daily during active cycle (10-20 days)", route: "Subcutaneous injection" },
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily, evening preferred", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Individuals with poor sleep quality, frequent night waking, or inadequate recovery from daily activity. Also suitable for those recovering from overtraining syndrome or chronic stress that has disrupted sleep architecture.",
    evidenceBase: "Ipamorelin has clinical data for GH pulse stimulation. Epithalon has research demonstrating pineal gland regulation and melatonin normalization. BPC-157 has preclinical evidence for gut-brain axis effects on stress and sleep.",
    costEstimate: "$100-220 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Will this stack make me sleepy during the day?", a: "No — the sleep benefits work overnight. Users report better sleep quality and waking more refreshed. Daytime energy typically improves." },
      { q: "Can I take melatonin alongside Epithalon?", a: "Epithalon normalizes endogenous melatonin production rather than supplementing it. Additional melatonin may interfere with this regulatory effect." },
    ],
  },
  {
    slug: "metabolic-health-weight-loss-stack",
    name: "Metabolic Health & Weight Loss Stack",
    h1: "Metabolic Health & Weight Loss Stack: AOD-9604, MOTS-C & Tesamorelin",
    metaDescription: "Metabolic peptide stack combining AOD-9604, MOTS-C, and Tesamorelin for weight loss, metabolic rate, and mitochondrial function.",
    tagline: "A targeted metabolic protocol for weight loss, fat oxidation, and mitochondrial efficiency.",
    peptides: ["aod-9604", "mots-c", "tesamorelin"],
    peptideNames: ["AOD-9604", "MOTS-C", "Tesamorelin"],
    primaryGoal: "fat-loss",
    goalSlugs: ["fat-loss", "metabolic-health", "energy"],
    synergyExplanation: "AOD-9604 stimulates lipolysis without affecting IGF-1 or blood sugar. MOTS-C supports mitochondrial function and metabolic regulation at the cellular level. Tesamorelin targets visceral abdominal fat through GH release. Each addresses a different aspect of metabolic health.",
    protocol: "AOD-9604 300-500 mcg before fasted morning exercise. MOTS-C 10 mg twice weekly. Tesamorelin 1-2 mg before bed nightly for 8-26 weeks. Combine with calorie-controlled diet and regular exercise.",
    dosingSchedule: [
      { peptide: "AOD-9604", dose: "300-500 mcg", timing: "Before fasted morning exercise", route: "Subcutaneous injection" },
      { peptide: "MOTS-C", dose: "10 mg", timing: "Twice weekly", route: "Subcutaneous injection" },
      { peptide: "Tesamorelin", dose: "1-2 mg", timing: "Before bed, empty stomach", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Individuals with metabolic syndrome, visceral adiposity, or weight loss resistance. Also suitable for those who need metabolic support during caloric restriction to maintain energy and mitochondrial function.",
    evidenceBase: "Tesamorelin has FDA clinical trials for visceral fat reduction in HIV patients. AOD-9604 has preclinical data for lipolysis. MOTS-C has preclinical mitochondrial research but limited human evidence.",
    costEstimate: "$200-450 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Is this stack safe for people with insulin resistance?", a: "Tesamorelin requires monitoring of IGF-1 and blood glucose. AOD-9604 does not affect blood sugar. MOTS-C may improve insulin sensitivity. Medical supervision is recommended." },
      { q: "How quickly will I see weight loss results?", a: "AOD-9604 effects on fat oxidation may be noticeable within 4-6 weeks. Tesamorelin visceral fat reduction is measurable at 8-12 weeks in clinical trials." },
    ],
  },
  {
    slug: "inflammation-pain-management-stack",
    name: "Systemic Inflammation & Pain Management Stack",
    h1: "Systemic Inflammation & Pain Management Stack: TB-500, BPC-157 & GHK-Cu",
    metaDescription: "Anti-inflammatory peptide stack combining TB-500, BPC-157, and GHK-Cu for chronic pain and systemic inflammation management.",
    tagline: "A multi-target approach to systemic inflammation combining localized and whole-body anti-inflammatory peptides.",
    peptides: ["tb-500", "bpc-157", "ghk-cu"],
    peptideNames: ["TB-500", "BPC-157", "GHK-Cu"],
    primaryGoal: "inflammation",
    goalSlugs: ["inflammation", "joint-recovery", "anti-aging"],
    synergyExplanation: "TB-500 downregulates pro-inflammatory cytokines systemically for whole-body anti-inflammatory effects. BPC-157 targets specific inflammatory sites and promotes tissue repair. GHK-Cu provides antioxidant and anti-inflammatory effects at the cellular level.",
    protocol: "TB-500 2.5 mg twice weekly for 4 weeks loading then weekly maintenance. BPC-157 250-500 mcg daily near specific pain sites. GHK-Cu 1-2 mg daily. Run for 8 weeks with 4-week break between cycles.",
    dosingSchedule: [
      { peptide: "TB-500", dose: "2.5 mg", timing: "Twice weekly loading, then weekly", route: "Subcutaneous injection" },
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily near pain/inflammation sites", route: "Subcutaneous injection" },
      { peptide: "GHK-Cu", dose: "1-2 mg", timing: "Daily, rotating sites", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Individuals with chronic systemic inflammation, autoimmune conditions, widespread joint pain, or slow recovery from exercise. Also suitable for those with elevated inflammatory markers on blood work.",
    evidenceBase: "TB-500 has preclinical evidence for TNF-alpha and IL-1β downregulation. BPC-157 has strong preclinical data for site-specific inflammation modulation. GHK-Cu has established anti-inflammatory and antioxidant properties.",
    costEstimate: "$160-300 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Can I use NSAIDs alongside this stack?", a: "Some users reduce NSAID use due to the anti-inflammatory effects of this stack. However, there is limited research on direct interactions. Consult a healthcare provider." },
      { q: "How long before I notice inflammation reduction?", a: "TB-500 effects are often reported within 1-2 weeks. BPC-157 site-specific effects in 1-3 weeks. GHK-Cu anti-inflammatory effects are more gradual." },
    ],
  },
  {
    slug: "skin-hair-regeneration-stack",
    name: "Skin, Hair & Connective Tissue Regeneration Stack",
    h1: "Skin, Hair & Connective Tissue Regeneration Stack: GHK-Cu, BPC-157 & Epithalon",
    metaDescription: "Regenerative peptide stack for skin, hair, and connective tissue combining GHK-Cu, BPC-157, and Epithalon.",
    tagline: "A comprehensive beauty-from-within protocol targeting skin elasticity, hair density, and connective tissue health.",
    peptides: ["ghk-cu", "bpc-157", "epithalon"],
    peptideNames: ["GHK-Cu", "BPC-157", "Epithalon"],
    primaryGoal: "skin-health",
    goalSlugs: ["skin-health", "hair-growth", "anti-aging"],
    synergyExplanation: "GHK-Cu stimulates collagen and elastin synthesis while promoting hair follicle cycling. BPC-157 supports wound healing and tissue repair throughout the body. Epithalon regulates pineal function and may support the endocrine environment for healthy skin and hair.",
    protocol: "GHK-Cu 1-2 mg daily subcutaneous. BPC-157 250-500 mcg daily. Epithalon 5-10 mg daily for 10-20 day cycles. GHK-Cu and BPC-157 can run for 8-12 weeks. Epithalon cycles 1-2 times per year.",
    dosingSchedule: [
      { peptide: "GHK-Cu", dose: "1-2 mg", timing: "Daily, rotating injection sites", route: "Subcutaneous injection" },
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily", route: "Subcutaneous injection" },
      { peptide: "Epithalon", dose: "5-10 mg", timing: "Daily for 10-20 day cycles", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults concerned with skin aging, elasticity loss, fine lines, and hair thinning. Also suitable for those recovering from surgical scars or looking for comprehensive connective tissue support.",
    evidenceBase: "GHK-Cu has the strongest evidence base for skin health with clinical trials showing improved skin firmness and reduced fine lines. BPC-157 supports the wound healing and repair mechanism. Epithalon's anti-aging effects are supported by Russian longevity research.",
    costEstimate: "$150-280 for a 12-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Can I use topical GHK-Cu instead of injectable?", a: "Yes — topical GHK-Cu is effective for skin-specific concerns. Injectable provides more systemic effects including hair growth and connective tissue repair." },
      { q: "Will this stack help with surgical scar recovery?", a: "GHK-Cu and BPC-157 are both discussed for scar reduction when started after initial wound closure." },
    ],
  },
  {
    slug: "hormone-axis-support-stack",
    name: "HPA Axis & Hormone Support Stack",
    h1: "HPA Axis & Hormone Support Stack: Kisspeptin, Selank & BPC-157",
    metaDescription: "Hormonal support peptide stack combining Kisspeptin, Selank, and BPC-157 for HPA axis regulation and hormonal balance.",
    tagline: "A targeted protocol for HPA axis support, stress resilience, and hormonal balance through complementary peptide mechanisms.",
    peptides: ["kisspeptin", "selank", "bpc-157"],
    peptideNames: ["Kisspeptin", "Selank", "BPC-157"],
    primaryGoal: "libido",
    goalSlugs: ["libido", "hormone-balance", "energy"],
    synergyExplanation: "Kisspeptin stimulates GnRH release for upstream HPG axis activation, supporting healthy testosterone and estrogen production. Selank modulates stress response and reduces cortisol through GABAergic pathways. BPC-157 supports gut-brain axis function and may help regulate the stress response.",
    protocol: "Kisspeptin 200-500 mcg once or twice daily for 4-8 weeks. Selank 400-800 mcg intranasal daily. BPC-157 250-500 mcg daily. Kisspeptin and Selank can be started together. Add BPC-157 for comprehensive support.",
    dosingSchedule: [
      { peptide: "Kisspeptin", dose: "200-500 mcg", timing: "Once to twice daily", route: "Subcutaneous injection" },
      { peptide: "Selank", dose: "400-800 mcg", timing: "Daily intranasal", route: "Intranasal spray" },
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults experiencing hormonal imbalances, low libido, chronic stress effects on hormones, or HPA axis dysfunction. Also suitable for those wanting support during TRT or hormonal therapy.",
    evidenceBase: "Kisspeptin has clinical research for HPG axis stimulation in both men and women. Selank has Russian clinical trials for stress and anxiety. BPC-157 has preclinical evidence for gut-brain axis effects.",
    costEstimate: "$120-250 for a 6-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Will this stack increase testosterone?", a: "Kisspeptin may support healthy LH and FSH signaling which can support natural testosterone production. Effects vary by individual baseline." },
      { q: "Can I use this stack while on TRT?", a: "Kisspeptin is not typically needed during TRT since exogenous testosterone suppresses the HPG axis. Selank and BPC-157 are compatible with TRT." },
    ],
  },
  {
    slug: "endurance-athlete-recovery-stack",
    name: "Endurance Athlete Recovery Stack",
    h1: "Endurance Athlete Recovery Stack: TB-500, AOD-9604 & MOTS-C",
    metaDescription: "Recovery peptide stack for endurance athletes combining TB-500, AOD-9604, and MOTS-C for inflammation management and metabolic support.",
    tagline: "A purpose-built protocol for runners, cyclists, and triathletes targeting the unique demands of high-volume endurance training.",
    peptides: ["tb-500", "aod-9604", "mots-c"],
    peptideNames: ["TB-500", "AOD-9604", "MOTS-C"],
    primaryGoal: "endurance",
    goalSlugs: ["endurance", "inflammation", "energy"],
    synergyExplanation: "TB-500 manages systemic inflammation from high training volume through cytokine modulation. AOD-9604 supports fat utilization during long endurance efforts. MOTS-C targets mitochondrial function for improved cellular energy production.",
    protocol: "TB-500 2.5 mg twice weekly for 4 weeks loading then weekly. AOD-9604 300 mcg before long endurance sessions. MOTS-C 10 mg twice weekly. Use TB-500 during base and build phases. Time AOD-9604 before key sessions.",
    dosingSchedule: [
      { peptide: "TB-500", dose: "2.5 mg", timing: "Twice weekly loading, then weekly", route: "Subcutaneous injection" },
      { peptide: "AOD-9604", dose: "300 mcg", timing: "Before endurance sessions", route: "Subcutaneous injection" },
      { peptide: "MOTS-C", dose: "10 mg", timing: "Twice weekly", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Serious endurance athletes in base-building and peak training phases who need inflammation management, metabolic support, and improved recovery between sessions.",
    evidenceBase: "TB-500 has preclinical evidence for systemic anti-inflammatory effects. AOD-9604 has clinical data for lipolysis. MOTS-C has preclinical mitochondrial research relevant to endurance metabolism.",
    costEstimate: "$180-350 for an 8-week block depending on vendor and dosing",
    faqItems: [
      { q: "Should I stop this stack before race day?", a: "Taper or stop TB-500 1-2 weeks before goal races. AOD-9604 and MOTS-C can continue through race week." },
      { q: "Can I use AOD-9604 before every training session?", a: "AOD-9604 is best reserved for key endurance sessions or fasted morning training. Daily use may reduce effectiveness over time." },
    ],
  },
  {
    slug: "stress-resilience-adaptogen-stack",
    name: "Stress Resilience & Adaptogen Stack",
    h1: "Stress Resilience & Adaptogen Stack: Selank, Semax & BPC-157",
    metaDescription: "Stress adaptation peptide stack combining Selank, Semax, and BPC-157 for cognitive resilience and stress management.",
    tagline: "A targeted protocol for building stress resilience, maintaining cognitive performance under pressure, and supporting the nervous system.",
    peptides: ["selank", "semax", "bpc-157"],
    peptideNames: ["Selank", "Semax", "BPC-157"],
    primaryGoal: "anxiety-reduction",
    goalSlugs: ["anxiety-reduction", "cognitive-performance", "focus"],
    synergyExplanation: "Selank reduces anxiety and improves stress tolerance through GABAergic modulation. Semax maintains cognitive function and BDNF expression even under stress. BPC-157 supports the gut-brain axis and may help regulate the physiological stress response.",
    protocol: "Selank 400-800 mcg intranasal morning and early afternoon. Semax 200-400 mcg intranasal morning only. BPC-157 250-500 mcg daily. Run 6-8 weeks with periodic breaks as needed.",
    dosingSchedule: [
      { peptide: "Selank", dose: "400-800 mcg", timing: "Morning and early afternoon", route: "Intranasal spray" },
      { peptide: "Semax", dose: "200-400 mcg", timing: "Morning only", route: "Intranasal spray" },
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Professionals in high-stress environments, students during exam periods, and anyone experiencing chronic stress that affects cognitive performance and well-being.",
    evidenceBase: "Selank has Russian clinical trials for anxiety disorders. Semax has clinical data for cognitive enhancement under stress. BPC-157 has preclinical evidence for stress-protective effects.",
    costEstimate: "$100-200 for a 6-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Can I use this stack as needed rather than daily?", a: "Selank and Semax can be used as needed for acute stress or cognitive demands. BPC-157 works best with consistent daily dosing." },
      { q: "Will this stack make me less motivated?", a: "No — the combination provides calm focus without reducing motivation. Selank reduces anxiety while Semax maintains cognitive drive." },
    ],
  },
  {
    slug: "post-surgical-recovery-stack",
    name: "Post-Surgical Recovery Stack",
    h1: "Post-Surgical Recovery Stack: BPC-157, TB-500 & GHK-Cu",
    metaDescription: "Post-operative recovery peptide stack combining BPC-157, TB-500, and GHK-Cu for surgical wound healing and tissue repair.",
    tagline: "A comprehensive post-surgical protocol designed to support incision healing, reduce scar tissue, and accelerate return to activity.",
    peptides: ["bpc-157", "tb-500", "ghk-cu"],
    peptideNames: ["BPC-157", "TB-500", "GHK-Cu"],
    primaryGoal: "injury-recovery",
    goalSlugs: ["injury-recovery", "skin-health", "inflammation"],
    synergyExplanation: "BPC-157 promotes angiogenesis and tissue repair at the surgical site. TB-500 reduces systemic inflammation and supports whole-body recovery from the surgical stress response. GHK-Cu enhances incision healing, collagen remodeling, and may reduce scar formation.",
    protocol: "Wait until surgical incisions are closed and cleared by surgeon. BPC-157 250-500 mcg daily near incision site. TB-500 2.5 mg twice weekly for 4 weeks. GHK-Cu 1-2 mg daily. Run for 6-8 weeks post-clearance.",
    dosingSchedule: [
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily near incision", route: "Subcutaneous injection" },
      { peptide: "TB-500", dose: "2.5 mg", timing: "Twice weekly for 4 weeks", route: "Subcutaneous injection" },
      { peptide: "GHK-Cu", dose: "1-2 mg", timing: "Daily, rotating sites", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Individuals recovering from orthopedic surgery, C-sections, hernia repair, or any surgical procedure where accelerated healing and reduced scarring are desired.",
    evidenceBase: "All three peptides have preclinical evidence for wound healing and tissue repair. BPC-157 has the strongest evidence for surgical wound healing. GHK-Cu is well-established in dermatological wound healing research.",
    costEstimate: "$180-320 for a 6-week post-surgical protocol depending on vendor",
    faqItems: [
      { q: "When can I start peptides after surgery?", a: "Only after surgical incisions are fully closed and your surgeon has cleared you. Typically 2-4 weeks post-surgery depending on the procedure." },
      { q: "Will these peptides help with internal scar tissue?", a: "BPC-157 and TB-500 may help reduce internal adhesion formation based on preclinical evidence." },
    ],
  },
  {
    slug: "immune-boost-recovery-stack",
    name: "Immune Boost & Recovery Stack",
    h1: "Immune Boost & Recovery Stack: Thymosin Alpha-1, BPC-157 & Epithalon",
    metaDescription: "Immune support peptide stack combining Thymosin Alpha-1, BPC-157, and Epithalon for comprehensive immune function and recovery.",
    tagline: "A targeted immune modulation protocol for chronic infections, post-viral recovery, and age-related immune decline.",
    peptides: ["thymosin-alpha-1", "bpc-157", "epithalon"],
    peptideNames: ["Thymosin Alpha-1", "BPC-157", "Epithalon"],
    primaryGoal: "immune-function",
    goalSlugs: ["immune-function", "anti-aging", "energy"],
    synergyExplanation: "Thymosin Alpha-1 activates T-cell maturation and modulates immune response for comprehensive immune support. BPC-157 supports the gut-immune axis and mucosal barrier function. Epithalon supports thymus gland function and pineal regulation for immune-endocrine balance.",
    protocol: "Thymosin Alpha-1 1.6 mg twice weekly for 6-12 weeks. BPC-157 250-500 mcg daily. Epithalon 5-10 mg daily for 10-20 day cycles every 6-12 months.",
    dosingSchedule: [
      { peptide: "Thymosin Alpha-1", dose: "1.6 mg", timing: "Twice weekly (e.g., Mon/Thu)", route: "Subcutaneous injection" },
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily", route: "Subcutaneous injection" },
      { peptide: "Epithalon", dose: "5-10 mg", timing: "Daily for 10-20 day cycles", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults with chronic infections, post-viral syndromes (including long COVID), frequent illness, or age-related immune decline. Also suitable for those seeking immune optimization during cold and flu season.",
    evidenceBase: "Thymosin Alpha-1 is approved in 35+ countries for hepatitis B and C and has clinical data for immune modulation. BPC-157 supports mucosal immunity. Epithalon has research for thymus function and immune optimization.",
    costEstimate: "$200-450 for a 12-week protocol depending on vendor and dosing",
    faqItems: [
      { q: "Can this stack help with long COVID?", a: "Thymosin Alpha-1 has the most promising evidence for long COVID immune dysregulation. Several small studies and case reports suggest immune-modulating benefits." },
      { q: "Should I use this stack only when sick?", a: "Thymosin Alpha-1 works best as a consistent protocol for immune modulation, not as an acute treatment for active illness." },
    ],
  },
  {
    slug: "mitochondrial-energy-stack",
    name: "Mitochondrial Energy & Vitality Stack",
    h1: "Mitochondrial Energy & Vitality Stack: NAD+, MOTS-C & Epithalon",
    metaDescription: "Energy optimization peptide stack combining NAD+, MOTS-C, and Epithalon for mitochondrial function, cellular energy, and vitality.",
    tagline: "A mitochondrial-targeted protocol for sustained energy, metabolic efficiency, and cellular vitality.",
    peptides: ["nad-plus", "mots-c", "epithalon"],
    peptideNames: ["NAD+", "MOTS-C", "Epithalon"],
    primaryGoal: "energy",
    goalSlugs: ["energy", "longevity", "anti-aging"],
    synergyExplanation: "NAD+ fuels the mitochondrial electron transport chain for cellular energy production. MOTS-C regulates mitochondrial biogenesis and metabolic homeostasis. Epithalon supports telomere maintenance and pineal function for cellular longevity.",
    protocol: "NAD+ 100-200 mg subcutaneous twice weekly or IV 250-500 mg monthly. MOTS-C 10 mg twice weekly. Epithalon 5-10 mg daily for 10-20 day cycles. NAD+ and MOTS-C can run continuously while Epithalon is cycled.",
    dosingSchedule: [
      { peptide: "NAD+", dose: "100-200 mg", timing: "Twice weekly SubQ or monthly IV", route: "Subcutaneous injection or IV infusion" },
      { peptide: "MOTS-C", dose: "10 mg", timing: "Twice weekly", route: "Subcutaneous injection" },
      { peptide: "Epithalon", dose: "5-10 mg", timing: "Daily for 10-20 day cycles", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults 35+ experiencing declining energy, metabolic slowdown, or age-related vitality loss. Also suitable for those with chronic fatigue or mitochondrial dysfunction concerns.",
    evidenceBase: "NAD+ has the strongest human evidence with clinical trials showing improved muscle function and metabolic markers. MOTS-C has preclinical mitochondrial research. Epithalon has Russian longevity research.",
    costEstimate: "$250-500 per month depending on NAD+ form (IV more expensive, SubQ more affordable)",
    faqItems: [
      { q: "Is IV or subcutaneous NAD+ better?", a: "IV provides faster, more complete absorption but requires clinic visits. Subcutaneous is more convenient for at-home use with good bioavailability." },
      { q: "Can I feel the energy boost immediately?", a: "NAD+ IV often produces noticeable effects within 24-48 hours. Subcutaneous effects are more gradual over 1-2 weeks. Epithalon benefits are cumulative over weeks to months." },
    ],
  },
  {
    slug: "connective-tissue-joint-stack",
    name: "Connective Tissue & Joint Longevity Stack",
    h1: "Connective Tissue & Joint Longevity Stack: BPC-157, GHK-Cu & TB-500",
    metaDescription: "Joint health peptide stack combining BPC-157, GHK-Cu, and TB-500 for connective tissue maintenance and joint longevity.",
    tagline: "A proactive protocol for maintaining joint health, supporting connective tissue integrity, and preventing age-related joint decline.",
    peptides: ["bpc-157", "ghk-cu", "tb-500"],
    peptideNames: ["BPC-157", "GHK-Cu", "TB-500"],
    primaryGoal: "joint-recovery",
    goalSlugs: ["joint-recovery", "anti-aging", "inflammation"],
    synergyExplanation: "BPC-157 targets tendon and ligament healing at specific joints. GHK-Cu supports collagen synthesis and connective tissue matrix integrity. TB-500 manages systemic inflammation that contributes to joint discomfort.",
    protocol: "BPC-157 250-500 mcg daily near most problematic joints. GHK-Cu 1-2 mg daily. TB-500 2.5 mg weekly after initial 4-week loading. Run for 8 weeks with 4-week breaks between cycles.",
    dosingSchedule: [
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily near problem joints", route: "Subcutaneous injection" },
      { peptide: "GHK-Cu", dose: "1-2 mg", timing: "Daily, rotating sites", route: "Subcutaneous injection" },
      { peptide: "TB-500", dose: "2.5 mg", timing: "Weekly after loading", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults 40+ concerned with age-related joint health, those with early osteoarthritis, and athletes wanting to proactively maintain joint function and prevent chronic issues.",
    evidenceBase: "BPC-157 has strong preclinical evidence for tendon and ligament healing. GHK-Cu has established research for collagen synthesis. TB-500 has preclinical evidence for systemic anti-inflammatory support.",
    costEstimate: "$160-300 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Can this stack reverse osteoarthritis?", a: "These peptides support connective tissue health but cannot reverse established cartilage loss. They may help manage symptoms and slow progression." },
      { q: "How often should I run maintenance cycles?", a: "Many users run one 8-week cycle per quarter for ongoing joint support, or cycle based on training demands." },
    ],
  },
  {
    slug: "fat-loss-metabolic-ignition-stack",
    name: "Fat Loss Metabolic Ignition Stack",
    h1: "Fat Loss Metabolic Ignition Stack: AOD-9604, Tesamorelin & Semaglutide",
    metaDescription: "Maximum fat loss peptide stack combining AOD-9604, Tesamorelin, and Semaglutide for comprehensive metabolic optimization.",
    tagline: "A comprehensive metabolic protocol for significant fat loss through appetite suppression, GH optimization, and targeted lipolysis.",
    peptides: ["aod-9604", "tesamorelin", "semaglutide"],
    peptideNames: ["AOD-9604", "Tesamorelin", "Semaglutide"],
    primaryGoal: "fat-loss",
    goalSlugs: ["fat-loss", "metabolic-health", "body-recomposition"],
    synergyExplanation: "Semaglutide reduces appetite and improves glycemic control through GLP-1 receptor activation. Tesamorelin targets visceral abdominal fat through GH release. AOD-9604 provides additional lipolytic support without affecting blood sugar or IGF-1.",
    protocol: "Semaglutide 0.25-2.4 mg weekly under medical supervision. Tesamorelin 1-2 mg before bed nightly. AOD-9604 300-500 mcg before fasted morning exercise. Semaglutide requires prescription and dose titration.",
    dosingSchedule: [
      { peptide: "Semaglutide", dose: "0.25-2.4 mg", timing: "Weekly, titrating up", route: "Subcutaneous injection (Rx required)" },
      { peptide: "Tesamorelin", dose: "1-2 mg", timing: "Before bed nightly", route: "Subcutaneous injection" },
      { peptide: "AOD-9604", dose: "300-500 mcg", timing: "Before fasted exercise", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Individuals with significant weight loss goals who need multi-mechanism support. Best suited for those with metabolic syndrome, insulin resistance, or who have plateaued on single interventions.",
    evidenceBase: "Semaglutide has the strongest clinical evidence with 15-20% average weight reduction. Tesamorelin has FDA clinical trials for visceral fat reduction. AOD-9604 has preclinical lipolysis data.",
    costEstimate: "$300-700 per month depending on Semaglutide source and dosing",
    faqItems: [
      { q: "Is this stack safe for long-term use?", a: "Semaglutide is approved for long-term use. Tesamorelin is typically cycled at 8-26 weeks. AOD-9604 can be used in cycles. Medical supervision is essential." },
      { q: "Will I lose muscle mass on this stack?", a: "Semaglutide can cause muscle loss during rapid weight reduction. Adequate protein intake and resistance training are essential. Tesamorelin may help preserve lean mass." },
    ],
  },
  {
    slug: "recovery-stack-everyday-active",
    name: "Everyday Active Recovery Stack",
    h1: "Everyday Active Recovery Stack: BPC-157 & Ipamorelin for Daily Wellness",
    metaDescription: "Daily recovery peptide stack combining low-dose BPC-157 and Ipamorelin for active individuals seeking consistent recovery support.",
    tagline: "A sustainable low-dose protocol for active adults who want consistent recovery support without aggressive cycling.",
    peptides: ["bpc-157", "ipamorelin"],
    peptideNames: ["BPC-157", "Ipamorelin"],
    primaryGoal: "recovery",
    goalSlugs: ["recovery", "sleep-optimization", "joint-recovery"],
    synergyExplanation: "BPC-157 provides daily tissue maintenance and repair for the minor injuries and inflammation from regular activity. Ipamorelin supports overnight recovery through GH pulse amplification. Together they create a foundation for consistent training without overuse accumulation.",
    protocol: "BPC-157 200-300 mcg daily (mild maintenance dose). Ipamorelin 200 mcg before bed on empty stomach. Run BPC-157 8 weeks on, 4 weeks off. Ipamorelin 12 weeks on, 4 weeks off.",
    dosingSchedule: [
      { peptide: "BPC-157", dose: "200-300 mcg", timing: "Daily, maintenance dose", route: "Subcutaneous injection" },
      { peptide: "Ipamorelin", dose: "200 mcg", timing: "Before bed, empty stomach", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Active adults who train 3-6 times per week and want to prevent overuse accumulation, improve recovery between sessions, and maintain joint health long-term.",
    evidenceBase: "Both peptides have preclinical evidence supporting their mechanisms. The low-dose maintenance approach is based on community experience rather than formal clinical studies.",
    costEstimate: "$80-160 for an 8-week cycle depending on vendor and dosing",
    faqItems: [
      { q: "Is this stack suitable for long-term use?", a: "The cycling protocol (8-12 weeks on, 4 weeks off) is designed for sustainable long-term use. Many active adults run this stack 2-3 times per year." },
      { q: "Can I increase the doses if I train more intensely?", a: "The low-dose approach is intentionally conservative. You can temporarily increase BPC-157 to 500 mcg during high-volume or intense training blocks." },
    ],
  },
  {
    slug: "libido-desire-optimization-stack",
    name: "Libido & Desire Optimization Stack",
    h1: "Libido & Desire Optimization Stack: PT-141, Kisspeptin & Selank",
    metaDescription: "Sexual health peptide stack combining PT-141, Kisspeptin, and Selank for comprehensive libido and desire support.",
    tagline: "A multi-mechanism protocol addressing both central desire pathways and hormonal signaling for comprehensive sexual health.",
    peptides: ["pt-141", "kisspeptin", "selank"],
    peptideNames: ["PT-141", "Kisspeptin", "Selank"],
    primaryGoal: "libido",
    goalSlugs: ["libido", "sexual-health", "confidence"],
    synergyExplanation: "PT-141 activates melanocortin receptors in the hypothalamus for central desire enhancement. Kisspeptin stimulates GnRH for downstream hormonal support. Selank reduces performance anxiety through its anxiolytic effects.",
    protocol: "PT-141 as needed, 0.5-1.75 mg 45 minutes before sexual activity. Kisspeptin 200-500 mcg daily for 4-8 week cycles. Selank 400-800 mcg intranasal daily or as needed for anxiety.",
    dosingSchedule: [
      { peptide: "PT-141", dose: "0.5-1.75 mg", timing: "45 min before activity, as needed", route: "Subcutaneous injection" },
      { peptide: "Kisspeptin", dose: "200-500 mcg", timing: "Once to twice daily", route: "Subcutaneous injection" },
      { peptide: "Selank", dose: "400-800 mcg", timing: "Daily or as needed", route: "Intranasal spray" },
    ],
    whoIsItFor: "Adults experiencing low libido, sexual desire issues, or performance anxiety. Particularly suitable when the root cause involves both biological (hormonal) and psychological (anxiety) components.",
    evidenceBase: "PT-141 is FDA-approved for hypoactive sexual desire disorder. Kisspeptin has clinical research for HPG axis stimulation. Selank has clinical data for anxiety reduction.",
    costEstimate: "$100-250 for a 4-week protocol plus PT-141 as needed",
    faqItems: [
      { q: "How long does PT-141 take to work?", a: "PT-141 typically produces effects within 30-45 minutes of injection, lasting 4-8 hours. Start at the lowest dose to assess side effect tolerance." },
      { q: "Can women use this stack?", a: "Yes — PT-141 is FDA-approved for premenopausal women. Kisspeptin and Selank are also suitable for women." },
    ],
  },
];
