/* Auto-generated by scripts/export-static-content.ts. */
import type { PseoSection } from "./pseo";

export const pseoSections = [
  {
    "key": "peptides",
    "label": "Peptide Library",
    "path": "/peptides",
    "description": "Profiles for 12+ research peptides.",
    "entries": [
      {
        "slug": "bpc-157",
        "path": "/peptides/bpc-157",
        "title": "BPC-157"
      },
      {
        "slug": "tb-500",
        "path": "/peptides/tb-500",
        "title": "TB-500"
      },
      {
        "slug": "ipamorelin",
        "path": "/peptides/ipamorelin",
        "title": "Ipamorelin"
      },
      {
        "slug": "cjc-1295",
        "path": "/peptides/cjc-1295",
        "title": "CJC-1295"
      },
      {
        "slug": "sermorelin",
        "path": "/peptides/sermorelin",
        "title": "Sermorelin"
      },
      {
        "slug": "semaglutide",
        "path": "/peptides/semaglutide",
        "title": "Semaglutide"
      },
      {
        "slug": "tirzepatide",
        "path": "/peptides/tirzepatide",
        "title": "Tirzepatide"
      },
      {
        "slug": "ghk-cu",
        "path": "/peptides/ghk-cu",
        "title": "GHK-Cu"
      },
      {
        "slug": "epithalon",
        "path": "/peptides/epithalon",
        "title": "Epithalon"
      },
      {
        "slug": "selank",
        "path": "/peptides/selank",
        "title": "Selank"
      },
      {
        "slug": "semax",
        "path": "/peptides/semax",
        "title": "Semax"
      },
      {
        "slug": "pt-141",
        "path": "/peptides/pt-141",
        "title": "PT-141"
      },
      {
        "slug": "nad-plus",
        "path": "/peptides/nad-plus",
        "title": "NAD+"
      },
      {
        "slug": "methylene-blue",
        "path": "/peptides/methylene-blue",
        "title": "Methylene Blue"
      },
      {
        "slug": "glutathione",
        "path": "/peptides/glutathione",
        "title": "Glutathione"
      },
      {
        "slug": "rapamycin",
        "path": "/peptides/rapamycin",
        "title": "Rapamycin"
      },
      {
        "slug": "low-dose-naltrexone",
        "path": "/peptides/low-dose-naltrexone",
        "title": "Low Dose Naltrexone (LDN)"
      },
      {
        "slug": "metformin",
        "path": "/peptides/metformin",
        "title": "Metformin"
      },
      {
        "slug": "oxandrolone",
        "path": "/peptides/oxandrolone",
        "title": "Oxandrolone (Anavar)"
      },
      {
        "slug": "nandrolone",
        "path": "/peptides/nandrolone",
        "title": "Nandrolone (Deca)"
      },
      {
        "slug": "retatrutide",
        "path": "/peptides/retatrutide",
        "title": "Retatrutide"
      },
      {
        "slug": "kpv",
        "path": "/peptides/kpv",
        "title": "KPV"
      },
      {
        "slug": "mots-c",
        "path": "/peptides/mots-c",
        "title": "MOTS-c"
      },
      {
        "slug": "ll-37",
        "path": "/peptides/ll-37",
        "title": "LL-37"
      },
      {
        "slug": "humanin",
        "path": "/peptides/humanin",
        "title": "Humanin"
      },
      {
        "slug": "orforglipron",
        "path": "/peptides/orforglipron",
        "title": "Orforglipron"
      },
      {
        "slug": "dihexa",
        "path": "/peptides/dihexa",
        "title": "Dihexa"
      },
      {
        "slug": "tesamorelin",
        "path": "/peptides/tesamorelin",
        "title": "Tesamorelin"
      },
      {
        "slug": "aod-9604",
        "path": "/peptides/aod-9604",
        "title": "AOD-9604"
      },
      {
        "slug": "ss-31",
        "path": "/peptides/ss-31",
        "title": "SS-31"
      }
    ]
  },
  {
    "key": "goals",
    "label": "Goals",
    "path": "/goals",
    "description": "Find peptides by health goal.",
    "entries": [
      {
        "slug": "muscle-growth",
        "path": "/goals/muscle-growth",
        "title": "Best Peptides for Muscle Growth"
      },
      {
        "slug": "fat-loss",
        "path": "/goals/fat-loss",
        "title": "Best Peptides for Fat Loss"
      },
      {
        "slug": "joint-recovery",
        "path": "/goals/joint-recovery",
        "title": "Best Peptides for Joint Recovery"
      },
      {
        "slug": "gut-health",
        "path": "/goals/gut-health",
        "title": "Best Peptides for Gut Health"
      },
      {
        "slug": "anti-aging",
        "path": "/goals/anti-aging",
        "title": "Best Peptides for Anti-Aging"
      },
      {
        "slug": "sleep-optimization",
        "path": "/goals/sleep-optimization",
        "title": "Best Peptides for Sleep"
      },
      {
        "slug": "cognitive-performance",
        "path": "/goals/cognitive-performance",
        "title": "Best Peptides for Cognitive Performance"
      },
      {
        "slug": "anxiety-reduction",
        "path": "/goals/anxiety-reduction",
        "title": "Best Peptides for Anxiety"
      },
      {
        "slug": "skin-health",
        "path": "/goals/skin-health",
        "title": "Best Peptides for Skin Health"
      },
      {
        "slug": "hair-growth",
        "path": "/goals/hair-growth",
        "title": "Best Peptides for Hair Growth"
      },
      {
        "slug": "longevity",
        "path": "/goals/longevity",
        "title": "Best Peptides for Longevity"
      },
      {
        "slug": "body-recomposition",
        "path": "/goals/body-recomposition",
        "title": "Best Peptides for Body Recomposition"
      },
      {
        "slug": "injury-recovery",
        "path": "/goals/injury-recovery",
        "title": "Best Peptides for Injury Recovery"
      },
      {
        "slug": "energy",
        "path": "/goals/energy",
        "title": "Best Peptides for Energy"
      },
      {
        "slug": "libido",
        "path": "/goals/libido",
        "title": "Best Peptides for Libido"
      },
      {
        "slug": "inflammation",
        "path": "/goals/inflammation",
        "title": "Best Peptides for Inflammation"
      },
      {
        "slug": "metabolic-health",
        "path": "/goals/metabolic-health",
        "title": "Best Peptides for Metabolic Health"
      },
      {
        "slug": "muscle-recovery",
        "path": "/goals/muscle-recovery",
        "title": "Best Peptides for Muscle Recovery"
      }
    ]
  },
  {
    "key": "compare",
    "label": "Compare",
    "path": "/compare",
    "description": "Head-to-head peptide comparisons.",
    "entries": [
      {
        "slug": "bpc-157-vs-tb-500",
        "path": "/compare/bpc-157-vs-tb-500",
        "title": "BPC-157 vs TB-500"
      },
      {
        "slug": "semaglutide-vs-tirzepatide",
        "path": "/compare/semaglutide-vs-tirzepatide",
        "title": "Semaglutide vs Tirzepatide"
      },
      {
        "slug": "ipamorelin-vs-cjc-1295",
        "path": "/compare/ipamorelin-vs-cjc-1295",
        "title": "Ipamorelin vs CJC-1295"
      },
      {
        "slug": "ozempic-vs-wegovy",
        "path": "/compare/ozempic-vs-wegovy",
        "title": "Ozempic vs Wegovy"
      },
      {
        "slug": "mounjaro-vs-zepbound",
        "path": "/compare/mounjaro-vs-zepbound",
        "title": "Mounjaro vs Zepbound"
      },
      {
        "slug": "selank-vs-semax",
        "path": "/compare/selank-vs-semax",
        "title": "Selank vs Semax"
      },
      {
        "slug": "epithalon-vs-ghk-cu",
        "path": "/compare/epithalon-vs-ghk-cu",
        "title": "Epithalon vs GHK-Cu"
      },
      {
        "slug": "sermorelin-vs-ipamorelin",
        "path": "/compare/sermorelin-vs-ipamorelin",
        "title": "Sermorelin vs Ipamorelin"
      },
      {
        "slug": "bpc-157-vs-ghk-cu",
        "path": "/compare/bpc-157-vs-ghk-cu",
        "title": "BPC-157 vs GHK-Cu"
      },
      {
        "slug": "tb-500-vs-ghk-cu",
        "path": "/compare/tb-500-vs-ghk-cu",
        "title": "TB-500 vs GHK-Cu"
      },
      {
        "slug": "tesamorelin-vs-ipamorelin",
        "path": "/compare/tesamorelin-vs-ipamorelin",
        "title": "Tesamorelin vs Ipamorelin"
      },
      {
        "slug": "semaglutide-vs-retatrutide",
        "path": "/compare/semaglutide-vs-retatrutide",
        "title": "Semaglutide vs Retatrutide"
      },
      {
        "slug": "aod-9604-vs-semaglutide",
        "path": "/compare/aod-9604-vs-semaglutide",
        "title": "AOD-9604 vs Semaglutide"
      },
      {
        "slug": "cjc-1295-vs-ghrp-6",
        "path": "/compare/cjc-1295-vs-ghrp-6",
        "title": "CJC-1295 vs GHRP-6"
      },
      {
        "slug": "pt-141-vs-kisspeptin",
        "path": "/compare/pt-141-vs-kisspeptin",
        "title": "PT-141 vs Kisspeptin"
      },
      {
        "slug": "semaglutide-vs-liraglutide",
        "path": "/compare/semaglutide-vs-liraglutide",
        "title": "Semaglutide vs Liraglutide"
      },
      {
        "slug": "mots-c-vs-nad",
        "path": "/compare/mots-c-vs-nad",
        "title": "MOTS-c vs NAD+"
      },
      {
        "slug": "ozempic-vs-mounjaro",
        "path": "/compare/ozempic-vs-mounjaro",
        "title": "Ozempic vs Mounjaro"
      },
      {
        "slug": "ozempic-vs-saxenda",
        "path": "/compare/ozempic-vs-saxenda",
        "title": "Ozempic vs Saxenda"
      },
      {
        "slug": "wegovy-vs-mounjaro",
        "path": "/compare/wegovy-vs-mounjaro",
        "title": "Wegovy vs Mounjaro"
      },
      {
        "slug": "wegovy-vs-saxenda",
        "path": "/compare/wegovy-vs-saxenda",
        "title": "Wegovy vs Saxenda"
      },
      {
        "slug": "tirzepatide-vs-retatrutide",
        "path": "/compare/tirzepatide-vs-retatrutide",
        "title": "Tirzepatide vs Retatrutide"
      },
      {
        "slug": "ozempic-vs-rybelsus",
        "path": "/compare/ozempic-vs-rybelsus",
        "title": "Ozempic vs Rybelsus"
      },
      {
        "slug": "trulicity-vs-ozempic",
        "path": "/compare/trulicity-vs-ozempic",
        "title": "Trulicity vs Ozempic"
      },
      {
        "slug": "victoza-vs-ozempic",
        "path": "/compare/victoza-vs-ozempic",
        "title": "Victoza vs Ozempic"
      },
      {
        "slug": "ipamorelin-vs-sermorelin",
        "path": "/compare/ipamorelin-vs-sermorelin",
        "title": "Ipamorelin vs Sermorelin"
      },
      {
        "slug": "cjc-1295-vs-sermorelin",
        "path": "/compare/cjc-1295-vs-sermorelin",
        "title": "CJC-1295 vs Sermorelin"
      },
      {
        "slug": "ghrp-6-vs-ghrp-2",
        "path": "/compare/ghrp-6-vs-ghrp-2",
        "title": "GHRP-6 vs GHRP-2"
      },
      {
        "slug": "ipamorelin-vs-ghrp-6",
        "path": "/compare/ipamorelin-vs-ghrp-6",
        "title": "Ipamorelin vs GHRP-6"
      },
      {
        "slug": "ipamorelin-vs-ghrp-2",
        "path": "/compare/ipamorelin-vs-ghrp-2",
        "title": "Ipamorelin vs GHRP-2"
      },
      {
        "slug": "hexarelin-vs-ipamorelin",
        "path": "/compare/hexarelin-vs-ipamorelin",
        "title": "Hexarelin vs Ipamorelin"
      },
      {
        "slug": "tesamorelin-vs-sermorelin",
        "path": "/compare/tesamorelin-vs-sermorelin",
        "title": "Tesamorelin vs Sermorelin"
      },
      {
        "slug": "cjc-1295-dac-vs-no-dac",
        "path": "/compare/cjc-1295-dac-vs-no-dac",
        "title": "CJC-1295 with DAC vs CJC-1295 without DAC (Mod GRF 1-29)"
      },
      {
        "slug": "sermorelin-vs-hgh",
        "path": "/compare/sermorelin-vs-hgh",
        "title": "Sermorelin vs HGH (Synthetic)"
      },
      {
        "slug": "ipamorelin-vs-hgh",
        "path": "/compare/ipamorelin-vs-hgh",
        "title": "Ipamorelin vs HGH (Synthetic)"
      },
      {
        "slug": "bpc-157-vs-ipamorelin",
        "path": "/compare/bpc-157-vs-ipamorelin",
        "title": "BPC-157 vs Ipamorelin"
      },
      {
        "slug": "epithalon-vs-nad",
        "path": "/compare/epithalon-vs-nad",
        "title": "Epithalon vs NAD+"
      },
      {
        "slug": "ghk-cu-vs-nad",
        "path": "/compare/ghk-cu-vs-nad",
        "title": "GHK-Cu vs NAD+"
      },
      {
        "slug": "nad-vs-nmn",
        "path": "/compare/nad-vs-nmn",
        "title": "NAD+ (IV) vs NMN (Oral)"
      },
      {
        "slug": "nad-vs-niacin",
        "path": "/compare/nad-vs-niacin",
        "title": "NAD+ / NMN vs Niacin (Vitamin B3)"
      },
      {
        "slug": "selank-vs-semax-anxiety",
        "path": "/compare/selank-vs-semax-anxiety",
        "title": "Selank vs Semax"
      },
      {
        "slug": "semax-vs-dihexa",
        "path": "/compare/semax-vs-dihexa",
        "title": "Semax vs Dihexa"
      },
      {
        "slug": "pt-141-vs-tadalafil",
        "path": "/compare/pt-141-vs-tadalafil",
        "title": "PT-141 vs Tadalafil (Cialis)"
      },
      {
        "slug": "pt-141-vs-sildenafil",
        "path": "/compare/pt-141-vs-sildenafil",
        "title": "PT-141 vs Sildenafil (Viagra)"
      },
      {
        "slug": "melanotan-2-vs-pt-141",
        "path": "/compare/melanotan-2-vs-pt-141",
        "title": "Melanotan II vs PT-141"
      },
      {
        "slug": "ghk-cu-vs-retinol",
        "path": "/compare/ghk-cu-vs-retinol",
        "title": "GHK-Cu vs Retinol (Vitamin A)"
      },
      {
        "slug": "ghk-cu-vs-hyaluronic-acid",
        "path": "/compare/ghk-cu-vs-hyaluronic-acid",
        "title": "GHK-Cu vs Hyaluronic Acid"
      },
      {
        "slug": "ghk-cu-vs-minoxidil",
        "path": "/compare/ghk-cu-vs-minoxidil",
        "title": "GHK-Cu vs Minoxidil"
      },
      {
        "slug": "bpc-157-vs-minoxidil",
        "path": "/compare/bpc-157-vs-minoxidil",
        "title": "BPC-157 vs Minoxidil"
      },
      {
        "slug": "thymosin-alpha-1-vs-ll-37",
        "path": "/compare/thymosin-alpha-1-vs-ll-37",
        "title": "Thymosin Alpha-1 vs LL-37"
      },
      {
        "slug": "thymosin-alpha-1-vs-bpc-157",
        "path": "/compare/thymosin-alpha-1-vs-bpc-157",
        "title": "Thymosin Alpha-1 vs BPC-157"
      },
      {
        "slug": "ll-37-vs-bpc-157",
        "path": "/compare/ll-37-vs-bpc-157",
        "title": "LL-37 vs BPC-157"
      },
      {
        "slug": "snap-8-vs-argireline",
        "path": "/compare/snap-8-vs-argireline",
        "title": "SNAP-8 vs Argireline (Acetyl Hexapeptide-3)"
      },
      {
        "slug": "ghk-cu-vs-argireline",
        "path": "/compare/ghk-cu-vs-argireline",
        "title": "GHK-Cu vs Argireline"
      },
      {
        "slug": "semaglutide-vs-orforglipron",
        "path": "/compare/semaglutide-vs-orforglipron",
        "title": "Semaglutide vs Orforglipron"
      },
      {
        "slug": "aod-9604-vs-tirzepatide",
        "path": "/compare/aod-9604-vs-tirzepatide",
        "title": "AOD-9604 vs Tirzepatide"
      },
      {
        "slug": "oxytocin-vs-kisspeptin",
        "path": "/compare/oxytocin-vs-kisspeptin",
        "title": "Oxytocin vs Kisspeptin"
      },
      {
        "slug": "pt-141-vs-oxytocin",
        "path": "/compare/pt-141-vs-oxytocin",
        "title": "PT-141 vs Oxytocin"
      },
      {
        "slug": "kisspeptin-vs-pt-141",
        "path": "/compare/kisspeptin-vs-pt-141",
        "title": "Kisspeptin vs PT-141"
      },
      {
        "slug": "dsip-vs-selank",
        "path": "/compare/dsip-vs-selank",
        "title": "DSIP vs Selank"
      },
      {
        "slug": "dsip-vs-ipamorelin",
        "path": "/compare/dsip-vs-ipamorelin",
        "title": "DSIP vs Ipamorelin"
      },
      {
        "slug": "cerebrolysin-vs-dihexa",
        "path": "/compare/cerebrolysin-vs-dihexa",
        "title": "Cerebrolysin vs Dihexa"
      },
      {
        "slug": "cerebrolysin-vs-semax",
        "path": "/compare/cerebrolysin-vs-semax",
        "title": "Cerebrolysin vs Semax"
      },
      {
        "slug": "bpc-157-vs-glutamine",
        "path": "/compare/bpc-157-vs-glutamine",
        "title": "BPC-157 vs L-Glutamine"
      },
      {
        "slug": "bpc-157-vs-zinc-carnosine",
        "path": "/compare/bpc-157-vs-zinc-carnosine",
        "title": "BPC-157 vs Zinc Carnosine"
      },
      {
        "slug": "tb-500-vs-ipamorelin",
        "path": "/compare/tb-500-vs-ipamorelin",
        "title": "TB-500 vs Ipamorelin"
      },
      {
        "slug": "bpc-157-vs-nac",
        "path": "/compare/bpc-157-vs-nac",
        "title": "BPC-157 vs NAC (N-Acetyl Cysteine)"
      },
      {
        "slug": "ghk-cu-vs-epithalon",
        "path": "/compare/ghk-cu-vs-epithalon",
        "title": "GHK-Cu vs Epithalon"
      },
      {
        "slug": "mots-c-vs-humanin",
        "path": "/compare/mots-c-vs-humanin",
        "title": "MOTS-c vs Humanin"
      },
      {
        "slug": "ipamorelin-vs-mk-677",
        "path": "/compare/ipamorelin-vs-mk-677",
        "title": "Ipamorelin vs MK-677 (Ibutamoren)"
      }
    ]
  },
  {
    "key": "stacks",
    "label": "Stacks",
    "path": "/stacks",
    "description": "Curated peptide protocols.",
    "entries": [
      {
        "slug": "recovery-stack",
        "path": "/stacks/recovery-stack",
        "title": "The Recovery Stack"
      },
      {
        "slug": "gh-optimization-stack",
        "path": "/stacks/gh-optimization-stack",
        "title": "The GH Optimization Stack"
      },
      {
        "slug": "anti-aging-stack",
        "path": "/stacks/anti-aging-stack",
        "title": "The Anti-Aging Stack"
      },
      {
        "slug": "metabolic-stack",
        "path": "/stacks/metabolic-stack",
        "title": "The Metabolic Stack"
      },
      {
        "slug": "cognitive-stack",
        "path": "/stacks/cognitive-stack",
        "title": "The Cognitive Stack"
      },
      {
        "slug": "wolverine-stack",
        "path": "/stacks/wolverine-stack",
        "title": "The Wolverine Stack"
      }
    ]
  },
  {
    "key": "guides",
    "label": "Guides",
    "path": "/guides",
    "description": "How-to dosing and injection guides.",
    "entries": [
      {
        "slug": "how-to-reconstitute-peptides",
        "path": "/guides/how-to-reconstitute-peptides",
        "title": "How to Reconstitute Peptides with Bacteriostatic Water"
      },
      {
        "slug": "how-to-inject-peptides-subcutaneously",
        "path": "/guides/how-to-inject-peptides-subcutaneously",
        "title": "How to Inject Peptides Subcutaneously"
      },
      {
        "slug": "how-to-calculate-peptide-dosage",
        "path": "/guides/how-to-calculate-peptide-dosage",
        "title": "How to Calculate Peptide Dosage"
      },
      {
        "slug": "how-to-store-peptides",
        "path": "/guides/how-to-store-peptides",
        "title": "How to Store Peptides: Refrigeration and Shelf Life Guide"
      },
      {
        "slug": "how-to-use-bpc-157-for-gut-healing",
        "path": "/guides/how-to-use-bpc-157-for-gut-healing",
        "title": "How to Use BPC-157 for Gut Healing"
      },
      {
        "slug": "how-to-inject-subcutaneously",
        "path": "/guides/how-to-inject-subcutaneously",
        "title": "How to Inject Peptides Subcutaneously (SubQ) — Step-by-Step"
      },
      {
        "slug": "how-to-use-ipamorelin",
        "path": "/guides/how-to-use-ipamorelin",
        "title": "How to Use Ipamorelin: Dosing, Timing & Protocol Guide"
      },
      {
        "slug": "how-to-use-sermorelin",
        "path": "/guides/how-to-use-sermorelin",
        "title": "How to Use Sermorelin: Dosing, Timing & Protocol Guide"
      },
      {
        "slug": "how-to-use-tb-500",
        "path": "/guides/how-to-use-tb-500",
        "title": "How to Use TB-500: Dosing, Protocol & Injury Recovery Guide"
      },
      {
        "slug": "how-to-use-nad-plus",
        "path": "/guides/how-to-use-nad-plus",
        "title": "How to Use NAD+: Dosing, Routes & Anti-Aging Protocol"
      },
      {
        "slug": "how-to-use-ghk-cu",
        "path": "/guides/how-to-use-ghk-cu",
        "title": "How to Use GHK-Cu: Topical & Injectable Protocols"
      },
      {
        "slug": "how-to-use-epithalon",
        "path": "/guides/how-to-use-epithalon",
        "title": "How to Use Epithalon: Dosing & Longevity Protocol"
      },
      {
        "slug": "how-to-use-pt-141",
        "path": "/guides/how-to-use-pt-141",
        "title": "How to Use PT-141: Dosing & Sexual Health Protocol"
      },
      {
        "slug": "how-to-use-cjc-1295",
        "path": "/guides/how-to-use-cjc-1295",
        "title": "How to Use CJC-1295: DAC vs No-DAC, Dosing & Protocol"
      },
      {
        "slug": "how-to-use-semaglutide",
        "path": "/guides/how-to-use-semaglutide",
        "title": "How to Use Semaglutide: Dosing Titration & Weight Loss Protocol"
      },
      {
        "slug": "how-to-use-tirzepatide",
        "path": "/guides/how-to-use-tirzepatide",
        "title": "How to Use Tirzepatide: Dosing Titration & Weight Loss Protocol"
      },
      {
        "slug": "how-to-use-melanotan-2",
        "path": "/guides/how-to-use-melanotan-2",
        "title": "How to Use Melanotan 2: Dosing, Tanning Protocol & Side Effects"
      },
      {
        "slug": "how-to-use-thymosin-alpha-1",
        "path": "/guides/how-to-use-thymosin-alpha-1",
        "title": "How to Use Thymosin Alpha-1: Immune Support Protocol"
      },
      {
        "slug": "how-to-read-a-peptide-coa",
        "path": "/guides/how-to-read-a-peptide-coa",
        "title": "How to Read a Peptide Certificate of Analysis (COA)"
      },
      {
        "slug": "how-to-choose-a-peptide-vendor",
        "path": "/guides/how-to-choose-a-peptide-vendor",
        "title": "How to Choose a Reputable Peptide Vendor: 7 Key Criteria"
      },
      {
        "slug": "how-to-build-a-peptide-stack",
        "path": "/guides/how-to-build-a-peptide-stack",
        "title": "How to Build a Peptide Stack: Synergy, Timing & Safety"
      },
      {
        "slug": "how-to-cycle-peptides",
        "path": "/guides/how-to-cycle-peptides",
        "title": "How to Cycle Peptides: On and Off Periods Explained"
      },
      {
        "slug": "how-to-use-peptides-for-fat-loss",
        "path": "/guides/how-to-use-peptides-for-fat-loss",
        "title": "How to Use Peptides for Fat Loss: Best Protocols & Combinations"
      },
      {
        "slug": "how-to-use-peptides-for-muscle-growth",
        "path": "/guides/how-to-use-peptides-for-muscle-growth",
        "title": "How to Use Peptides for Muscle Growth: Best Protocols"
      },
      {
        "slug": "how-to-use-peptides-for-sleep",
        "path": "/guides/how-to-use-peptides-for-sleep",
        "title": "How to Use Peptides for Sleep: Best Protocols & Timing"
      },
      {
        "slug": "how-to-use-peptides-for-anti-aging",
        "path": "/guides/how-to-use-peptides-for-anti-aging",
        "title": "How to Use Peptides for Anti-Aging: Longevity Protocol Guide"
      },
      {
        "slug": "how-to-use-peptides-for-injury-recovery",
        "path": "/guides/how-to-use-peptides-for-injury-recovery",
        "title": "How to Use Peptides for Injury Recovery: Complete Protocol"
      },
      {
        "slug": "bpc-157-dosage-protocol",
        "path": "/guides/bpc-157-dosage-protocol",
        "title": "BPC-157 Dosage Protocol: Exactly How Much to Take"
      },
      {
        "slug": "subcutaneous-vs-intramuscular-injections",
        "path": "/guides/subcutaneous-vs-intramuscular-injections",
        "title": "Subcutaneous vs. Intramuscular Peptide Injections: Which is Better?"
      },
      {
        "slug": "oral-vs-injectable-peptides",
        "path": "/guides/oral-vs-injectable-peptides",
        "title": "Oral Peptides vs. Injections: Do Oral Peptides Actually Work?"
      },
      {
        "slug": "best-time-to-take-gh-peptides",
        "path": "/guides/best-time-to-take-gh-peptides",
        "title": "The Best Time of Day to Take Growth Hormone Peptides"
      },
      {
        "slug": "fasting-and-peptides",
        "path": "/guides/fasting-and-peptides",
        "title": "Fasting and Peptides: Should You Inject on an Empty Stomach?"
      },
      {
        "slug": "peptide-half-lives-dosing-frequency",
        "path": "/guides/peptide-half-lives-dosing-frequency",
        "title": "Peptide Half-Lives Explained: Dosing Frequency Guide"
      }
    ]
  },
  {
    "key": "for",
    "label": "For",
    "path": "/for",
    "description": "Find peptides by condition or concern.",
    "entries": [
      {
        "slug": "brain-fog",
        "path": "/for/brain-fog",
        "title": "Brain Fog and Cognitive Fatigue"
      },
      {
        "slug": "leaky-gut",
        "path": "/for/leaky-gut",
        "title": "Leaky Gut (Intestinal Permeability)"
      },
      {
        "slug": "joint-pain",
        "path": "/for/joint-pain",
        "title": "Joint Pain and Osteoarthritis"
      },
      {
        "slug": "low-testosterone",
        "path": "/for/low-testosterone",
        "title": "Low Testosterone (Hypogonadism)"
      },
      {
        "slug": "anxiety",
        "path": "/for/anxiety",
        "title": "Anxiety and Stress"
      },
      {
        "slug": "poor-sleep",
        "path": "/for/poor-sleep",
        "title": "Poor Sleep and Insomnia"
      },
      {
        "slug": "tendinopathy",
        "path": "/for/tendinopathy",
        "title": "Tendinopathy (Tendon Injury)"
      },
      {
        "slug": "chronic-fatigue",
        "path": "/for/chronic-fatigue",
        "title": "Chronic Fatigue Syndrome (ME/CFS)"
      },
      {
        "slug": "depression",
        "path": "/for/depression",
        "title": "Depression (Major Depressive Disorder)"
      },
      {
        "slug": "osteoporosis",
        "path": "/for/osteoporosis",
        "title": "Osteoporosis"
      },
      {
        "slug": "erectile-dysfunction",
        "path": "/for/erectile-dysfunction",
        "title": "Erectile Dysfunction"
      },
      {
        "slug": "hair-loss",
        "path": "/for/hair-loss",
        "title": "Hair Loss (Androgenetic Alopecia)"
      },
      {
        "slug": "skin-aging",
        "path": "/for/skin-aging",
        "title": "Skin Aging (Photoaging & Intrinsic Aging)"
      },
      {
        "slug": "obesity",
        "path": "/for/obesity",
        "title": "Obesity"
      },
      {
        "slug": "type-2-diabetes",
        "path": "/for/type-2-diabetes",
        "title": "Type 2 Diabetes"
      },
      {
        "slug": "cognitive-decline",
        "path": "/for/cognitive-decline",
        "title": "Cognitive Decline and Mild Cognitive Impairment"
      },
      {
        "slug": "wound-healing",
        "path": "/for/wound-healing",
        "title": "Impaired Wound Healing"
      },
      {
        "slug": "autoimmune-disease",
        "path": "/for/autoimmune-disease",
        "title": "Autoimmune Diseases"
      },
      {
        "slug": "insomnia",
        "path": "/for/insomnia",
        "title": "Insomnia"
      },
      {
        "slug": "perimenopause",
        "path": "/for/perimenopause",
        "title": "Perimenopause and Menopause"
      },
      {
        "slug": "pcos",
        "path": "/for/pcos",
        "title": "PCOS"
      },
      {
        "slug": "lyme-disease",
        "path": "/for/lyme-disease",
        "title": "Lyme Disease and Chronic Illness Recovery"
      },
      {
        "slug": "adhd",
        "path": "/for/adhd",
        "title": "ADHD"
      },
      {
        "slug": "irritable-bowel-syndrome",
        "path": "/for/irritable-bowel-syndrome",
        "title": "Irritable Bowel Syndrome"
      },
      {
        "slug": "hashimotos-thyroiditis",
        "path": "/for/hashimotos-thyroiditis",
        "title": "Hashimoto's Thyroiditis"
      },
      {
        "slug": "women-over-40",
        "path": "/for/women-over-40",
        "title": "Women Over 40"
      },
      {
        "slug": "men-over-50",
        "path": "/for/men-over-50",
        "title": "Men Over 50"
      },
      {
        "slug": "osteoarthritis",
        "path": "/for/osteoarthritis",
        "title": "Osteoarthritis"
      },
      {
        "slug": "chronic-fatigue-syndrome",
        "path": "/for/chronic-fatigue-syndrome",
        "title": "Chronic Fatigue Syndrome"
      }
    ]
  },
  {
    "key": "reviews",
    "label": "Reviews",
    "path": "/reviews",
    "description": "Independent peptide reviews.",
    "entries": [
      {
        "slug": "bpc-157-review",
        "path": "/reviews/bpc-157-review",
        "title": "BPC-157 Review: Is It Worth It? An Independent Assessment"
      },
      {
        "slug": "ipamorelin-cjc-1295-review",
        "path": "/reviews/ipamorelin-cjc-1295-review",
        "title": "Ipamorelin / CJC-1295 Review: The Most Popular GH Stack Assessed"
      },
      {
        "slug": "semaglutide-review",
        "path": "/reviews/semaglutide-review",
        "title": "Semaglutide Review: Ozempic and Wegovy Assessed Independently"
      },
      {
        "slug": "tb-500-review",
        "path": "/reviews/tb-500-review",
        "title": "TB-500 Review: Is Thymosin Beta-4 Worth It? Independent Assessment"
      },
      {
        "slug": "ghk-cu-review",
        "path": "/reviews/ghk-cu-review",
        "title": "GHK-Cu Review: Is the Copper Peptide Worth It? Independent Assessment"
      },
      {
        "slug": "ipamorelin-review",
        "path": "/reviews/ipamorelin-review",
        "title": "Ipamorelin Review: GH Release, Body Composition & Side Effects"
      },
      {
        "slug": "tirzepatide-review",
        "path": "/reviews/tirzepatide-review",
        "title": "Tirzepatide Review: Weight Loss Results, Side Effects & Comparison with Semaglutide"
      },
      {
        "slug": "sermorelin-review",
        "path": "/reviews/sermorelin-review",
        "title": "Sermorelin Review: Anti-Aging Results, Side Effects & Comparison with HGH"
      },
      {
        "slug": "nad-plus-review",
        "path": "/reviews/nad-plus-review",
        "title": "NAD+ Review: Anti-Aging Evidence, Energy Results & Best Forms"
      },
      {
        "slug": "epithalon-review",
        "path": "/reviews/epithalon-review",
        "title": "Epithalon Review: Telomere Lengthening Evidence, Results & Protocol"
      },
      {
        "slug": "pt-141-review",
        "path": "/reviews/pt-141-review",
        "title": "PT-141 Review: Sexual Health Results, Side Effects & Dosing"
      },
      {
        "slug": "cjc-1295-review",
        "path": "/reviews/cjc-1295-review",
        "title": "CJC-1295 Review: Body Composition Results, DAC vs No-DAC & Side Effects"
      },
      {
        "slug": "thymosin-alpha-1-review",
        "path": "/reviews/thymosin-alpha-1-review",
        "title": "Thymosin Alpha-1 Review: Immune Support Evidence, Results & Side Effects"
      },
      {
        "slug": "melanotan-2-review",
        "path": "/reviews/melanotan-2-review",
        "title": "Melanotan 2 Review: Tanning Results, Side Effects & Safety Concerns"
      },
      {
        "slug": "selank-review",
        "path": "/reviews/selank-review",
        "title": "Selank Review: Anxiety Relief Results, Side Effects & Evidence"
      },
      {
        "slug": "semax-review",
        "path": "/reviews/semax-review",
        "title": "Semax Review: Cognitive Enhancement Evidence, Results & Side Effects"
      }
    ]
  }
] satisfies PseoSection[];
