import type { StackPageData } from "./pseoData";

export const batch3StackPages: StackPageData[] = [
  {
    slug: "fat-loss-stack",
    name: "The Fat Loss Stack",
    h1: "The Fat Loss Stack: Tesamorelin + AOD-9604 + MOTS-C",
    metaDescription: "The Fat Loss Stack (Tesamorelin + AOD-9604 + MOTS-C): independent guide to the leading metabolism-targeting peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A targeted metabolic stack combining GH-driven lipolysis, mitochondrial efficiency, and insulin sensitivity support.",
    peptides: ["tesamorelin", "aod-9604", "mots-c"],
    peptideNames: ["Tesamorelin", "AOD-9604", "MOTS-C"],
    primaryGoal: "Fat loss, metabolic flexibility, body recomposition",
    goalSlugs: ["fat-loss", "body-recomposition", "metabolic-health", "blood-sugar-control"],
    synergyExplanation: "This stack addresses fat storage through three complementary axes. Tesamorelin reduces visceral adiposity through the GH axis, targeting the metabolically dangerous central fat depot. AOD-9604 amplifies lipolytic signaling without broad GH activation, making it a precision tool for fat-cell mobilization. MOTS-C improves insulin sensitivity and exercise-driven fat oxidation, ensuring the metabolic environment supports rather than resists fat loss. Together they create a comprehensive metabolic intervention that no single peptide can match.",
    protocol: "The standard protocol runs 8-12 weeks. Tesamorelin 1-2 mg daily SubQ before bed. AOD-9604 250-500 mcg daily SubQ, ideally before fasted morning cardio. MOTS-C 5-15 mg 2-3x weekly SubQ. All three can be administered in the same session using separate syringes.",
    dosingSchedule: [
      { peptide: "Tesamorelin", dose: "1-2 mg", timing: "Daily before bed", route: "Subcutaneous injection" },
      { peptide: "AOD-9604", dose: "250-500 mcg", timing: "Daily before fasted cardio", route: "Subcutaneous injection" },
      { peptide: "MOTS-C", dose: "5-15 mg", timing: "2-3x weekly", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults with stubborn visceral adiposity, metabolic inflexibility, or body recomposition goals that have not responded to diet and exercise alone. Best suited for users who already have solid nutritional habits and training consistency.",
    evidenceBase: "Tesamorelin has strong human clinical data for visceral fat reduction. AOD-9604 has moderate preclinical evidence for lipolysis. MOTS-C has emerging human data for insulin sensitivity and exercise metabolism. The combination has strong mechanistic logic but no formal combination trials.",
    costEstimate: "$350-$700/month depending on sources and dosing protocol",
    faqItems: [
      { q: "Which component drives the most fat loss in this stack?", a: "Tesamorelin has the strongest human evidence for visceral fat reduction. AOD-9604 and MOTS-C play supporting roles in lipolysis and metabolic flexibility respectively." },
      { q: "Can this stack be combined with GLP-1 agonists?", a: "With physician supervision, yes. GLP-1 agonists address appetite and glucose regulation through a completely different mechanism, making the combination potentially complementary for comprehensive metabolic health." },
    ],
  },
  {
    slug: "mitochondrial-stack",
    name: "The Mitochondrial Stack",
    h1: "The Mitochondrial Stack: SS-31 + Humanin + MOTS-C",
    metaDescription: "The Mitochondrial Stack (SS-31 + Humanin + MOTS-C): independent guide to the leading mitochondrial health peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A comprehensive mitochondrial support stack targeting energy production, cellular resilience, and metabolic efficiency.",
    peptides: ["ss-31", "humanin", "mots-c"],
    peptideNames: ["SS-31", "Humanin", "MOTS-C"],
    primaryGoal: "Mitochondrial health, energy, longevity, metabolic flexibility",
    goalSlugs: ["energy", "longevity", "metabolic-health", "cardiovascular-health", "neuroprotection"],
    synergyExplanation: "These three mitochondrial-derived and mitochondria-targeted peptides work at different levels of the same core biology. SS-31 stabilizes cardiolipin in the inner mitochondrial membrane, improving electron transport chain efficiency and reducing reactive oxygen species. Humanin acts as a cellular stress signal, promoting apoptosis resistance and insulin sensitivity through mitochondrial signaling pathways. MOTS-C regulates AMPK-dependent metabolic adaptation and exercise-induced mitochondrial biogenesis. Together they address mitochondrial function from membrane integrity to adaptive signaling.",
    protocol: "Standard protocol runs 8 weeks. SS-31 5-20 mg daily SubQ. Humanin 5-10 mg 2-3x weekly SubQ. MOTS-C 5-15 mg 2-3x weekly SubQ. Many users run SS-31 and MOTS-C more frequently and Humanin on alternating days to manage injection load.",
    dosingSchedule: [
      { peptide: "SS-31", dose: "5-20 mg", timing: "Daily", route: "Subcutaneous injection" },
      { peptide: "Humanin", dose: "5-10 mg", timing: "2-3x weekly", route: "Subcutaneous injection" },
      { peptide: "MOTS-C", dose: "5-15 mg", timing: "2-3x weekly", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults experiencing age-related energy decline, poor exercise recovery, metabolic stiffness, or those with a strong longevity orientation. Also relevant for users who identify mitochondrial dysfunction as a bottleneck in their health optimization.",
    evidenceBase: "SS-31 has moderate preclinical and emerging human evidence for cardiolipin stabilization and mitochondrial efficiency. Humanin has preclinical evidence for cytoprotective and insulin-sensitizing effects. MOTS-C has emerging human data for exercise metabolism and AMPK activation.",
    costEstimate: "$450-$900/month depending on dosing protocol and sources",
    faqItems: [
      { q: "How quickly do users notice effects from the Mitochondrial Stack?", a: "SS-31 effects on recovery and endurance are often noticed within 2-4 weeks. Humanin and MOTS-C effects on energy and metabolic flexibility typically emerge over 4-8 weeks." },
      { q: "Should this stack be cycled or used continuously?", a: "Most protocols run 8-12 week cycles. Some users maintain on lower doses of SS-31 and MOTS-C between cycles." },
    ],
  },
  {
    slug: "sleep-stack",
    name: "The Sleep Stack",
    h1: "The Sleep Stack: DSIP + Epithalon + Ipamorelin",
    metaDescription: "The Sleep Stack (DSIP + Epithalon + Ipamorelin): independent guide to the leading sleep-quality peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A multi-mechanism sleep stack targeting sleep onset, sleep depth, and circadian regulation.",
    peptides: ["dsip", "epithalon", "ipamorelin"],
    peptideNames: ["DSIP", "Epithalon", "Ipamorelin"],
    primaryGoal: "Sleep optimization, recovery, circadian health",
    goalSlugs: ["sleep-optimization", "anti-aging", "recovery", "energy"],
    synergyExplanation: "This stack addresses sleep through three independent mechanisms. DSIP modulates delta-wave sleep architecture and stress hormone regulation at the neurochemical level. Epithalon normalizes pineal gland function and melatonin production, supporting healthy circadian rhythm. Ipamorelin amplifies the natural nocturnal GH pulse, which both enhances slow-wave sleep and improves recovery. The result is a comprehensive sleep intervention that targets onset, depth, and hormonal recovery simultaneously.",
    protocol: "DSIP 100-300 mcg SubQ before bed, cycled 2-6 weeks. Epithalon 5-10 mg daily SubQ for 10-20 day cycles, 1-2x per year. Ipamorelin 200-300 mcg SubQ before bed, 5-7 days per week for 8-12 week cycles. Start with one compound at a time to assess individual response.",
    dosingSchedule: [
      { peptide: "DSIP", dose: "100-300 mcg", timing: "Before bed, cycled 2-6 weeks", route: "Subcutaneous injection" },
      { peptide: "Epithalon", dose: "5-10 mg", timing: "Daily for 10-20 day cycles", route: "Subcutaneous injection" },
      { peptide: "Ipamorelin", dose: "200-300 mcg", timing: "Before bed, 5-7 days/week", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults with chronic sleep disruption, age-related sleep deterioration, poor sleep architecture, or recovery-limited sleep patterns. Especially useful when stress-driven hyperarousal or hormonal decline is the root cause.",
    evidenceBase: "DSIP has preclinical and limited human evidence for sleep architecture modulation. Epithalon has 30+ years of Russian research for pineal regulation and sleep improvement. Ipamorelin has emerging human evidence for GH-driven sleep enhancement.",
    costEstimate: "$150-$350/month depending on cycling schedules and sources",
    faqItems: [
      { q: "Which peptide in this stack has the strongest sleep-specific evidence?", a: "DSIP is the most directly sleep-targeted peptide in the stack, with specific effects on delta-wave sleep. Epithalon and Ipamorelin improve sleep as part of broader hormonal and circadian regulation." },
      { q: "Can all three peptides be used simultaneously?", a: "Yes, but it is prudent to start with one to assess individual response. Adding Epithalon in short cycles on top of a DSIP and Ipamorelin base is a common approach." },
    ],
  },
  {
    slug: "gut-support-stack",
    name: "The Gut Support Stack",
    h1: "The Gut Support Stack: BPC-157 + KPV + VIP",
    metaDescription: "The Gut Support Stack (BPC-157 + KPV + VIP): independent guide to the leading gut-health peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A comprehensive gut-health stack targeting mucosal repair, inflammation control, and gut-brain signaling.",
    peptides: ["bpc-157", "kpv", "vip"],
    peptideNames: ["BPC-157", "KPV", "VIP"],
    primaryGoal: "Gut health, inflammation control, mucosal repair",
    goalSlugs: ["gut-health", "ibd-support", "gastric-ulcer-healing", "inflammation", "microbiome-diversity"],
    synergyExplanation: "Each peptide in this stack targets a distinct layer of gut biology. BPC-157 promotes angiogenesis, epithelial repair, and gut-brain axis normalization through vagal signaling. KPV reduces inflammatory cytokine activity in the gut lining through alpha-MSH-derived anti-inflammatory signaling. VIP modulates autonomic tone, gut motility, and mucosal immune balance, making it especially relevant when inflammation and dysmotility coexist. The stack covers structural repair, immune calming, and neural regulation.",
    protocol: "BPC-157 250-500 mcg daily oral or SubQ. KPV 250-500 mcg once or twice daily oral or SubQ. VIP 50-200 mcg once or twice daily intranasal or SubQ. Standard cycle: 4-8 weeks. Oral routes are preferred for gut-specific applications when available.",
    dosingSchedule: [
      { peptide: "BPC-157", dose: "250-500 mcg", timing: "Daily", route: "Oral capsule or SubQ" },
      { peptide: "KPV", dose: "250-500 mcg", timing: "1-2x daily", route: "Oral capsule or SubQ" },
      { peptide: "VIP", dose: "50-200 mcg", timing: "1-2x daily", route: "Intranasal or SubQ" },
    ],
    whoIsItFor: "Individuals with inflammatory bowel patterns, IBS, gut barrier dysfunction, food reactivity, or autonomic gut dysregulation. Best suited when the gut issue involves both inflammation and impaired mucosal integrity.",
    evidenceBase: "BPC-157 has strong preclinical evidence for mucosal repair and gut protection. KPV has preclinical evidence for colitis and inflammatory gut models. VIP has preclinical and emerging human evidence for gut motility and mucosal immune regulation.",
    costEstimate: "$200-$450/month depending on dosing and routes",
    faqItems: [
      { q: "Is oral or injectable administration better for this stack?", a: "For gut-specific applications, oral BPC-157 and KPV allow direct mucosal contact. Injectable routes provide more consistent systemic absorption. Some users combine oral KPV with injectable BPC-157." },
      { q: "How long before gut symptoms improve?", a: "Acute symptom relief can occur within 1-3 weeks. Full mucosal repair and inflammatory quieting typically require 4-8 weeks of consistent use." },
    ],
  },
  {
    slug: "brain-fog-stack",
    name: "The Brain Fog Stack",
    h1: "The Brain Fog Stack: Semax + Selank + Cerebrolysin",
    metaDescription: "The Brain Fog Stack (Semax + Selank + Cerebrolysin): independent guide to the leading cognitive clarity peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A multi-mechanism cognitive stack targeting mental clarity, processing speed, and neurotrophic support.",
    peptides: ["semax", "selank", "cerebrolysin"],
    peptideNames: ["Semax", "Selank", "Cerebrolysin"],
    primaryGoal: "Cognitive performance, mental clarity, brain fog relief",
    goalSlugs: ["cognitive-performance", "focus-and-concentration", "memory-retention", "neuroprotection", "mood-elevation"],
    synergyExplanation: "Semax upregulates BDNF and NGF, providing the neurotrophic foundation for synaptic plasticity and cognitive function. Selank reduces anxiety-driven cognitive impairment through GABA-A modulation without sedation, clearing the background noise that interferes with focus. Cerebrolysin provides a broad neuropeptide mixture that supports neuronal survival, synaptic density, and recovery from metabolic or inflammatory stress. Together they address processing speed, working memory, and the neurobiological environment needed for sustained cognitive performance.",
    protocol: "Semax 200-600 mcg intranasal daily. Selank 250-1000 mcg intranasal daily. Cerebrolysin 2-5 mL IM or IV per treatment day, 10-20 treatment days per cycle. Run the intranasal peptides for 4-8 weeks; Cerebrolysin can be run as a separate 10-20 day cycle twice per year.",
    dosingSchedule: [
      { peptide: "Semax", dose: "200-600 mcg", timing: "Daily morning", route: "Intranasal spray" },
      { peptide: "Selank", dose: "250-1000 mcg", timing: "Daily morning", route: "Intranasal spray" },
      { peptide: "Cerebrolysin", dose: "2-5 mL", timing: "10-20 treatment days per cycle", route: "IM or IV" },
    ],
    whoIsItFor: "Adults experiencing brain fog, reduced processing speed, difficulty concentrating, or cognitive decline associated with stress, aging, or post-viral syndromes. Also relevant for knowledge workers seeking sustained cognitive performance.",
    evidenceBase: "Semax has Russian clinical data for cognitive enhancement and BDNF upregulation. Selank has Russian clinical data for anxiolytic effects without sedation. Cerebrolysin has strong human clinical evidence for neurorecovery and cognitive support in neurologic settings.",
    costEstimate: "$200-$500/month depending on Cerebrolysin cycling",
    faqItems: [
      { q: "How quickly does the Brain Fog Stack work?", a: "Semax and Selank produce noticeable effects within days. Cerebrolysin effects are more gradual and cumulative, typically becoming apparent after 10-15 treatment days." },
      { q: "Can Cerebrolysin be replaced with another nootropic in this stack?", a: "For a lighter protocol, Semax and Selank alone provide meaningful cognitive support. Cerebrolysin adds depth for users with more significant cognitive fatigue or recovery needs." },
    ],
  },
  {
    slug: "libido-stack",
    name: "The Libido Stack",
    h1: "The Libido Stack: PT-141 + Kisspeptin + Melanotan 2",
    metaDescription: "The Libido Stack (PT-141 + Kisspeptin + Melanotan 2): independent guide to the leading sexual health peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A multi-pathway sexual health stack targeting desire, hormonal signaling, and arousal response.",
    peptides: ["pt-141", "kisspeptin", "melanotan-2"],
    peptideNames: ["PT-141", "Kisspeptin", "Melanotan 2"],
    primaryGoal: "Sexual health, libido, hormonal balance",
    goalSlugs: ["libido", "sexual-health", "mood-elevation", "confidence"],
    synergyExplanation: "PT-141 activates central melanocortin receptors to enhance sexual desire at the neurological level, addressing libido rather than just physical response. Kisspeptin stimulates GnRH and downstream LH/FSH output, supporting endogenous sex hormone production through the hypothalamic-pituitary-gonadal axis. Melanotan 2 adds broader melanocortin receptor activation that can amplify both desire signaling and the physical arousal response. The three compounds cover desire, hormonal drive, and physical response through distinct pathways.",
    protocol: "PT-141 0.5-1.75 mg SubQ as needed, 45 minutes before sexual activity, max 1x per 24 hours. Kisspeptin 100-500 mcg 2-4x weekly SubQ, cycled 4-8 weeks. Melanotan 2 0.25-1 mg daily during loading then 0.5-1 mg twice weekly maintenance SubQ.",
    dosingSchedule: [
      { peptide: "PT-141", dose: "0.5-1.75 mg", timing: "As needed, 45 min before activity", route: "Subcutaneous injection" },
      { peptide: "Kisspeptin", dose: "100-500 mcg", timing: "2-4x weekly", route: "Subcutaneous injection" },
      { peptide: "Melanotan 2", dose: "0.25-1 mg", timing: "Daily loading then 2x weekly maintenance", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults with low libido, hypoactive sexual desire, or age-related decline in sexual interest. PT-141 is the most evidence-backed component with FDA approval for HSDD. Kisspeptin is more experimental but offers upstream hormonal support.",
    evidenceBase: "PT-141 is FDA-approved for HSDD with strong clinical data. Kisspeptin has moderate preclinical and emerging human evidence for reproductive hormone signaling. Melanotan 2 has moderate preclinical evidence for melanocortin-mediated sexual effects.",
    costEstimate: "$150-$400/month depending on frequency and sources",
    faqItems: [
      { q: "How is this stack different from PDE5 inhibitor-based approaches?", a: "PDE5 inhibitors address blood flow peripherally. This stack targets central desire mechanisms, hormonal drive, and neurological arousal pathways, making it more appropriate for libido-centric concerns." },
      { q: "Can PT-141 be used alongside PDE5 inhibitors?", a: "Caution is warranted due to potential blood pressure effects. Physician guidance is recommended before combining." },
    ],
  },
  {
    slug: "immune-defense-stack",
    name: "The Immune Defense Stack",
    h1: "The Immune Defense Stack: Thymosin Alpha-1 + LL-37 + KPV",
    metaDescription: "The Immune Defense Stack (Thymosin Alpha-1 + LL-37 + KPV): independent guide to the leading immune-modulating peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A comprehensive immune modulation stack covering adaptive immunity, innate defense, and inflammatory balance.",
    peptides: ["thymosin-alpha-1", "ll-37", "kpv"],
    peptideNames: ["Thymosin Alpha-1", "LL-37", "KPV"],
    primaryGoal: "Immune support, immune modulation, infection resilience",
    goalSlugs: ["immune-support", "stress-resilience", "energy", "inflammation"],
    synergyExplanation: "Thymosin Alpha-1 organizes the adaptive immune response by enhancing T-cell maturation, dendritic cell activity, and antigen presentation without indiscriminate activation. LL-37 provides front-line innate defense through direct antimicrobial activity and broader immunoregulatory signaling. KPV calms inflammatory tone through alpha-MSH-derived anti-inflammatory pathways, preventing the immune response from becoming excessive or damaging. The stack covers immune coordination, microbial defense, and inflammatory balance in a single protocol.",
    protocol: "Thymosin Alpha-1 1.6 mg SubQ twice weekly. LL-37 100-250 mcg SubQ daily for short courses of 10-30 days. KPV 250-500 mcg oral or SubQ 1-2x daily. Typical cycle: 6-12 weeks for Thymosin Alpha-1, with LL-37 used in shorter targeted windows.",
    dosingSchedule: [
      { peptide: "Thymosin Alpha-1", dose: "1.6 mg", timing: "2x weekly", route: "Subcutaneous injection" },
      { peptide: "LL-37", dose: "100-250 mcg", timing: "Daily for 10-30 day courses", route: "Subcutaneous injection" },
      { peptide: "KPV", dose: "250-500 mcg", timing: "1-2x daily", route: "Oral or SubQ" },
    ],
    whoIsItFor: "Adults with frequent illness, poor recovery after viral or bacterial infections, immune fragility, or chronic low-grade inflammatory patterns. Also relevant for those preparing for high-stress periods or travel.",
    evidenceBase: "Thymosin Alpha-1 has strong human clinical data for immune modulation in hepatitis and infectious disease settings. LL-37 has moderate preclinical evidence for antimicrobial and immunoregulatory activity. KPV has moderate preclinical evidence for anti-inflammatory effects in mucosal tissues.",
    costEstimate: "$300-$600/month depending on LL-37 cycling and sources",
    faqItems: [
      { q: "Is this stack appropriate for ongoing daily use?", a: "Thymosin Alpha-1 can be used for 6-12 week cycles. LL-37 is best reserved for shorter courses when active immune support is needed. KPV can be used more continuously." },
      { q: "Does this stack overstimulate the immune system?", a: "No. These peptides modulate rather than indiscriminately activate immune function. Thymosin Alpha-1 organizes adaptive responses, LL-37 supports innate barriers, and KPV provides inflammatory regulation." },
    ],
  },
  {
    slug: "nerve-repair-stack",
    name: "The Nerve Repair Stack",
    h1: "The Nerve Repair Stack: ARA-290 + Cerebrolysin + BPC-157",
    metaDescription: "The Nerve Repair Stack (ARA-290 + Cerebrolysin + BPC-157): independent guide to the leading neuro-regenerative peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A targeted nerve repair stack for neuropathic pain, nerve injury, and neural recovery.",
    peptides: ["ara-290", "cerebrolysin", "bpc-157"],
    peptideNames: ["ARA-290", "Cerebrolysin", "BPC-157"],
    primaryGoal: "Nerve regeneration, neuropathic pain relief, neural recovery",
    goalSlugs: ["nerve-regeneration", "inflammation", "injury-recovery", "neuroprotection"],
    synergyExplanation: "ARA-290 activates the innate repair receptor to support small-fiber nerve repair and reduce neuropathic pain signaling, targeting the tissue-protective erythropoietin pathway without red-cell stimulation. Cerebrolysin provides neurotrophic support through BDNF and NGF-like signaling, promoting synaptic plasticity and neuronal survival. BPC-157 contributes angiogenesis and growth-factor signaling that supports the local tissue environment needed for nerve repair. The combination addresses neural recovery, the inflammatory environment, and the vascular support required for sustained regeneration.",
    protocol: "ARA-290 2-4 mg SubQ daily or 3-5x weekly. Cerebrolysin 2-10 mL IM or IV per treatment day, 10-20 treatment days per cycle. BPC-157 200-500 mcg SubQ daily. Standard protocol: 8 weeks with Cerebrolysin cycled separately.",
    dosingSchedule: [
      { peptide: "ARA-290", dose: "2-4 mg", timing: "Daily or 3-5x weekly", route: "Subcutaneous injection" },
      { peptide: "Cerebrolysin", dose: "2-10 mL", timing: "10-20 treatment days per cycle", route: "IM or IV" },
      { peptide: "BPC-157", dose: "200-500 mcg", timing: "Daily", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults with neuropathic pain, peripheral neuropathy, small-fiber nerve injury, or recovery after nerve trauma. Best suited when the symptom pattern includes burning, numbness, tingling, or shooting pain rather than purely mechanical issues.",
    evidenceBase: "ARA-290 has moderate preclinical and emerging human evidence for small-fiber neuropathy and neuropathic pain. Cerebrolysin has strong human clinical evidence for neurologic recovery. BPC-157 has strong preclinical evidence for tissue repair including nerve-adjacent healing.",
    costEstimate: "$400-$800/month depending on Cerebrolysin cycling",
    faqItems: [
      { q: "How long does the Nerve Repair Stack take to show results?", a: "ARA-290 effects on neuropathic pain are sometimes reported within 2-4 weeks. Cerebrolysin effects on neural recovery typically require a full 10-20 day treatment cycle. BPC-157 supports the tissue environment throughout." },
      { q: "Is this stack suitable for central nervous system injuries?", a: "Cerebrolysin has the strongest evidence for central nervous system recovery. ARA-290 is more specifically associated with peripheral and small-fiber nerve repair." },
    ],
  },
  {
    slug: "skin-health-stack",
    name: "The Skin Health Stack",
    h1: "The Skin Health Stack: GHK-Cu + Epithalon + Argireline",
    metaDescription: "The Skin Health Stack (GHK-Cu + Epithalon + Argireline): independent guide to the leading skin and appearance peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A comprehensive skin health stack combining collagen support, cellular repair, and expression-line management.",
    peptides: ["ghk-cu", "epithalon", "argireline"],
    peptideNames: ["GHK-Cu", "Epithalon", "Argireline"],
    primaryGoal: "Skin health, collagen support, anti-aging appearance",
    goalSlugs: ["skin-health", "collagen-production", "elastin-production", "anti-aging", "sun-damage-repair"],
    synergyExplanation: "GHK-Cu is the foundational skin peptide, stimulating collagen and elastin synthesis while activating antioxidant enzymes and modulating over 4,000 genes involved in tissue remodeling. Epithalon adds a systemic cellular-aging angle through telomerase activation and pineal regulation, supporting skin health from the inside out. Argireline targets dynamic expression lines by modulating SNARE-complex signaling, offering a topical complement to the deeper regenerative work of GHK-Cu and Epithalon.",
    protocol: "GHK-Cu topical 1-5% serum daily or SubQ 1-2 mg daily. Epithalon 5-10 mg SubQ daily for 10-20 day cycles, 1-2x per year. Argireline topical serum applied 1-2x daily. Continuous topical use with periodic Epithalon cycles.",
    dosingSchedule: [
      { peptide: "GHK-Cu", dose: "1-5% topical or 1-2 mg SubQ", timing: "Daily", route: "Topical serum or SubQ" },
      { peptide: "Epithalon", dose: "5-10 mg", timing: "10-20 day cycles, 1-2x/year", route: "Subcutaneous injection" },
      { peptide: "Argireline", dose: "Topical serum", timing: "1-2x daily", route: "Topical" },
    ],
    whoIsItFor: "Adults concerned with visible skin aging, collagen loss, fine lines, and skin texture. GHK-Cu and Argireline are suitable for most skin types. Epithalon adds systemic anti-aging support for those with broader longevity goals.",
    evidenceBase: "GHK-Cu has moderate clinical evidence in cosmetic dermatology for collagen synthesis and skin improvement. Epithalon has moderate preclinical evidence for telomere-related cellular health. Argireline has cosmetic ingredient-level evidence for expression-line softening.",
    costEstimate: "$100-$250/month for topical protocol; $200-$400/month with injectable GHK-Cu",
    faqItems: [
      { q: "Is topical or injectable GHK-Cu better in this stack?", a: "For skin-specific goals, topical GHK-Cu provides direct dermal delivery. Injectable GHK-Cu adds systemic effects on wound healing and inflammation." },
      { q: "Can Argireline be replaced with another topical peptide?", a: "SNAP-8 is a comparable alternative with a similar SNARE-modulating mechanism. The choice depends on individual formulation preference." },
    ],
  },
  {
    slug: "muscle-growth-stack",
    name: "The Muscle Growth Stack",
    h1: "The Muscle Growth Stack: Ipamorelin + Sermorelin + IGF-1 LR3",
    metaDescription: "The Muscle Growth Stack (Ipamorelin + Sermorelin + IGF-1 LR3): independent guide to the leading anabolic peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A comprehensive anabolic stack targeting GH pulsatility, IGF-1 signaling, and direct muscle protein synthesis.",
    peptides: ["ipamorelin", "sermorelin", "igf-1-lr3"],
    peptideNames: ["Ipamorelin", "Sermorelin", "IGF-1 LR3"],
    primaryGoal: "Muscle growth, body recomposition, anabolic optimization",
    goalSlugs: ["muscle-growth", "body-recomposition", "fat-loss", "muscle-recovery"],
    synergyExplanation: "Ipamorelin triggers clean GH pulses through ghrelin receptor agonism, while Sermorelin amplifies GH output through GHRH receptor stimulation, creating a dual-pathway amplification of the GH axis. IGF-1 LR3 then delivers the downstream anabolic signal directly, bypassing IGF-binding protein attenuation for a more potent growth signal. The stack works through every level of the GH-IGF axis: upstream secretagogue signaling, pituitary GH release, and direct IGF-1 receptor activation.",
    protocol: "Ipamorelin 200-300 mcg and Sermorelin 200-300 mcg combined SubQ before bed, 5-7 days per week. IGF-1 LR3 20-50 mcg SubQ or IM daily, often post-workout. Standard cycle: 6-8 weeks with appropriate monitoring.",
    dosingSchedule: [
      { peptide: "Ipamorelin", dose: "200-300 mcg", timing: "Before bed, 5-7 days/week", route: "Subcutaneous injection" },
      { peptide: "Sermorelin", dose: "200-300 mcg", timing: "Before bed with Ipamorelin", route: "Subcutaneous injection" },
      { peptide: "IGF-1 LR3", dose: "20-50 mcg", timing: "Daily, often post-workout", route: "SubQ or IM" },
    ],
    whoIsItFor: "Experienced users with serious muscle-building goals who have already optimized training and nutrition. This is an advanced stack that requires careful monitoring of glucose, IGF-1 levels, and tissue response.",
    evidenceBase: "Ipamorelin and Sermorelin have emerging human evidence for GH stimulation. IGF-1 LR3 has moderate preclinical evidence for anabolic signaling and nutrient partitioning. The stack has strong mechanistic logic but limited formal combination data.",
    costEstimate: "$250-$500/month depending on dosing and sources",
    faqItems: [
      { q: "Is this stack appropriate for beginners?", a: "No. This is an advanced anabolic stack. Beginners should start with Ipamorelin and Sermorelin alone before considering IGF-1 LR3." },
      { q: "How does IGF-1 LR3 change the risk profile compared to GH secretagogues alone?", a: "IGF-1 LR3 acts closer to the end of the growth signaling chain, creating more potent anabolic effects but also greater potential for hypoglycemia and unwanted tissue growth. Monitoring is essential." },
    ],
  },
  {
    slug: "endurance-stack",
    name: "The Endurance Stack",
    h1: "The Endurance Stack: MOTS-C + SS-31 + TB-500",
    metaDescription: "The Endurance Stack (MOTS-C + SS-31 + TB-500): independent guide to the leading exercise performance peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A performance-focused stack for endurance, recovery, and exercise adaptation.",
    peptides: ["mots-c", "ss-31", "tb-500"],
    peptideNames: ["MOTS-C", "SS-31", "TB-500"],
    primaryGoal: "Endurance, exercise performance, recovery capacity",
    goalSlugs: ["energy", "vo2-max", "muscle-endurance", "inflammation", "muscle-recovery"],
    synergyExplanation: "MOTS-C activates AMPK-linked metabolic adaptation and improves glucose utilization during exercise, effectively acting as an exercise mimetic that enhances training response. SS-31 improves mitochondrial electron transport efficiency and reduces oxidative stress in high-output tissues, directly supporting sustained aerobic performance. TB-500 provides systemic tissue repair and anti-inflammatory effects that accelerate recovery between training sessions, allowing higher training volume and frequency.",
    protocol: "MOTS-C 5-15 mg SubQ 2-3x weekly. SS-31 5-20 mg SubQ daily. TB-500 2-2.5 mg SubQ twice weekly loading then weekly maintenance. Typical cycle: 8 weeks with 4-week break.",
    dosingSchedule: [
      { peptide: "MOTS-C", dose: "5-15 mg", timing: "2-3x weekly", route: "Subcutaneous injection" },
      { peptide: "SS-31", dose: "5-20 mg", timing: "Daily", route: "Subcutaneous injection" },
      { peptide: "TB-500", dose: "2-2.5 mg", timing: "2x weekly loading, weekly maintenance", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Endurance athletes, high-volume trainers, and active adults who want to improve work capacity, reduce recovery time between sessions, and support mitochondrial health under training stress.",
    evidenceBase: "MOTS-C has emerging human data for exercise metabolism and AMPK activation. SS-31 has moderate preclinical and emerging human evidence for mitochondrial efficiency. TB-500 has moderate preclinical evidence for systemic tissue repair.",
    costEstimate: "$400-$800/month depending on dosing protocol",
    faqItems: [
      { q: "How soon do users notice performance improvements?", a: "SS-31 and MOTS-C effects on endurance and recovery are often noticed within 2-4 weeks. TB-500 effects on systemic recovery typically emerge over 4-6 weeks." },
      { q: "Can this stack replace traditional endurance training adaptations?", a: "No. These compounds support the physiological systems involved in endurance but do not replace the cardiovascular, metabolic, and neuromuscular adaptations produced by consistent training." },
    ],
  },
  {
    slug: "stress-resilience-stack",
    name: "The Stress Resilience Stack",
    h1: "The Stress Resilience Stack: Selank + DSIP + VIP",
    metaDescription: "The Stress Resilience Stack (Selank + DSIP + VIP): independent guide to the leading stress-modulating peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A multi-system stress adaptation stack targeting anxiety, sleep quality, and autonomic balance.",
    peptides: ["selank", "dsip", "vip"],
    peptideNames: ["Selank", "DSIP", "VIP"],
    primaryGoal: "Stress resilience, anxiety management, autonomic regulation",
    goalSlugs: ["stress-resilience", "anxiety-reduction", "sleep-optimization", "mood-elevation", "energy"],
    synergyExplanation: "Selank reduces anxiety through GABA-A modulation without sedation, clearing the cognitive and emotional noise that perpetuates stress cycles. DSIP improves sleep architecture and stress hormone regulation, ensuring that the recovery period is restorative rather than fragmented. VIP modulates autonomic tone, vasodilation, and mucosal immune balance, addressing the physiological stress response at the neuroimmune level. Together they cover the cognitive, sleep, and autonomic dimensions of stress adaptation.",
    protocol: "Selank 250-1000 mcg intranasal daily. DSIP 100-300 mcg SubQ before bed. VIP 50-200 mcg intranasal or SubQ 1-2x daily. Run Selank and DSIP for 4-8 week cycles. VIP can be added for specific autonomic or inflammatory patterns.",
    dosingSchedule: [
      { peptide: "Selank", dose: "250-1000 mcg", timing: "Daily", route: "Intranasal spray" },
      { peptide: "DSIP", dose: "100-300 mcg", timing: "Before bed, cycled 2-6 weeks", route: "Subcutaneous injection" },
      { peptide: "VIP", dose: "50-200 mcg", timing: "1-2x daily", route: "Intranasal or SubQ" },
    ],
    whoIsItFor: "Adults experiencing chronic stress, anxiety, poor stress recovery, or autonomic dysregulation. Best suited when stress manifests across multiple systems: cognitive worry, poor sleep, and physical tension or inflammatory reactivity.",
    evidenceBase: "Selank has Russian clinical data for anxiety reduction without sedation. DSIP has preclinical and limited human evidence for sleep and stress hormone modulation. VIP has preclinical and emerging human evidence for autonomic and neuroimmune regulation.",
    costEstimate: "$200-$400/month depending on dosing and VIP inclusion",
    faqItems: [
      { q: "How quickly does the Stress Resilience Stack work?", a: "Selank effects on anxiety are often noticeable within days. DSIP effects on sleep quality typically emerge over 1-3 weeks. VIP effects on autonomic balance are more variable." },
      { q: "Is this stack suitable for daily long-term use?", a: "Selank can be used for extended periods without tolerance concerns. DSIP and VIP are best cycled to maintain responsiveness." },
    ],
  },
  {
    slug: "bodybuilding-stack",
    name: "The Bodybuilding Stack",
    h1: "The Bodybuilding Stack: IGF-1 LR3 + PEG-MGF + Ipamorelin",
    metaDescription: "The Bodybuilding Stack (IGF-1 LR3 + PEG-MGF + Ipamorelin): independent guide to the advanced hypertrophy peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "An advanced anabolic stack designed for maximal hypertrophy, satellite-cell activation, and recovery-driven growth.",
    peptides: ["igf-1-lr3", "peg-mgf", "ipamorelin"],
    peptideNames: ["IGF-1 LR3", "PEG-MGF", "Ipamorelin"],
    primaryGoal: "Maximum hypertrophy, muscle fiber recruitment, recovery-driven growth",
    goalSlugs: ["muscle-growth", "sprint-performance", "body-recomposition", "muscle-recovery"],
    synergyExplanation: "IGF-1 LR3 provides direct anabolic signaling through the IGF-1 receptor, driving protein synthesis and nutrient partitioning into muscle tissue. PEG-MGF extends mechano growth factor signaling, which is thought to support satellite-cell activation and localized muscle repair after intense training. Ipamorelin maintains the upstream GH-IGF axis, ensuring endogenous IGF-1 production supports the growth environment. The stack addresses hypertrophy through direct anabolic signaling, local repair mechanisms, and systemic GH support.",
    protocol: "IGF-1 LR3 20-50 mcg SubQ or IM daily, typically post-workout. PEG-MGF 200-400 mcg SubQ or IM 2-3x weekly. Ipamorelin 200-300 mcg SubQ before bed daily. Standard cycle: 6 weeks on, 4 weeks off. Blood glucose monitoring recommended.",
    dosingSchedule: [
      { peptide: "IGF-1 LR3", dose: "20-50 mcg", timing: "Daily, post-workout preferred", route: "SubQ or IM" },
      { peptide: "PEG-MGF", dose: "200-400 mcg", timing: "2-3x weekly", route: "SubQ or IM" },
      { peptide: "Ipamorelin", dose: "200-300 mcg", timing: "Before bed daily", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Advanced bodybuilders and serious strength athletes with hypertrophy-focused goals who have already optimized training, nutrition, and recovery. Not suitable for general wellness or beginner use.",
    evidenceBase: "IGF-1 LR3 has moderate preclinical evidence for anabolic signaling. PEG-MGF has preclinical evidence for satellite-cell activation. Ipamorelin has emerging human evidence for GH-driven body composition improvement. The combination is based on mechanistic logic rather than formal combination trials.",
    costEstimate: "$300-$600/month depending on dosing and sources",
    faqItems: [
      { q: "How is this stack different from standard GH secretagogue protocols?", a: "This stack adds direct IGF-1 receptor activation and mechano growth factor signaling to the GH pulse provided by Ipamorelin. It is significantly more potent and carries correspondingly more risk." },
      { q: "What monitoring is essential during this stack?", a: "Blood glucose monitoring is critical due to IGF-1 LR3 effects on glucose handling. Regular assessment of IGF-1 levels, fasting glucose, and tissue response is recommended." },
    ],
  },
  {
    slug: "cardio-stack",
    name: "The Cardiovascular Stack",
    h1: "The Cardiovascular Stack: SS-31 + Tesamorelin + Humanin",
    metaDescription: "The Cardiovascular Stack (SS-31 + Tesamorelin + Humanin): independent guide to the leading cardiometabolic peptide combination. Protocol, dosing, and evidence. Vendor-neutral.",
    tagline: "A targeted cardiometabolic stack for heart health, vascular function, and metabolic risk reduction.",
    peptides: ["ss-31", "tesamorelin", "humanin"],
    peptideNames: ["SS-31", "Tesamorelin", "Humanin"],
    primaryGoal: "Cardiovascular health, metabolic function, visceral fat reduction",
    goalSlugs: ["cardiovascular-health", "metabolic-health", "blood-sugar-control", "energy", "vo2-max"],
    synergyExplanation: "SS-31 improves mitochondrial function in high-energy cardiac tissue by stabilizing cardiolipin and reducing oxidative stress, directly supporting myocardial efficiency. Tesamorelin reduces visceral adiposity and improves the metabolic environment that drives cardiovascular risk, targeting the fat depot most closely linked to heart disease. Humanin provides cellular stress resistance and anti-apoptotic signaling that protects vascular and cardiac tissue under metabolic strain. Together they address mitochondrial, metabolic, and cellular-resilience aspects of cardiovascular health.",
    protocol: "SS-31 5-20 mg SubQ daily. Tesamorelin 1-2 mg SubQ daily. Humanin 5-10 mg SubQ 2-3x weekly. Standard protocol: 8-12 weeks. Cardiovascular monitoring including blood pressure and lipid panels recommended before and during the protocol.",
    dosingSchedule: [
      { peptide: "SS-31", dose: "5-20 mg", timing: "Daily", route: "Subcutaneous injection" },
      { peptide: "Tesamorelin", dose: "1-2 mg", timing: "Daily", route: "Subcutaneous injection" },
      { peptide: "Humanin", dose: "5-10 mg", timing: "2-3x weekly", route: "Subcutaneous injection" },
    ],
    whoIsItFor: "Adults with cardiometabolic risk factors including central adiposity, reduced exercise tolerance, or age-related cardiovascular decline. Best suited for users who also maintain foundational cardiovascular care including appropriate medical management.",
    evidenceBase: "SS-31 has moderate preclinical and emerging human evidence for mitochondrial protection in cardiac tissue. Tesamorelin has strong human clinical data for visceral fat reduction. Humanin has preclinical evidence for cardiovascular protection and insulin sensitivity.",
    costEstimate: "$450-$900/month depending on dosing protocol",
    faqItems: [
      { q: "Does this stack replace standard cardiovascular medications?", a: "No. This stack is a supportive intervention, not a replacement for statins, antihypertensives, or other prescribed cardiovascular therapies." },
      { q: "What baseline metrics should be checked before starting?", a: "Blood pressure, fasting glucose, lipid panel, IGF-1, and inflammatory markers provide a useful baseline for assessing the stack effects." },
    ],
  },
];
