// Auto-generated by scripts/generate-pseo-batch-6.ts
// 150 total pages

export const batch6CompareEntries = [
  {
    "slug": "ozempic-vs-victoza",
    "path": "/compare/ozempic-vs-victoza",
    "title": "Ozempic vs Victoza"
  },
  {
    "slug": "victoza-vs-wegovy",
    "path": "/compare/victoza-vs-wegovy",
    "title": "Victoza vs Wegovy"
  },
  {
    "slug": "wegovy-vs-victoza",
    "path": "/compare/wegovy-vs-victoza",
    "title": "Wegovy vs Victoza"
  },
  {
    "slug": "victoza-vs-saxenda",
    "path": "/compare/victoza-vs-saxenda",
    "title": "Victoza vs Saxenda"
  },
  {
    "slug": "saxenda-vs-victoza",
    "path": "/compare/saxenda-vs-victoza",
    "title": "Saxenda vs Victoza"
  },
  {
    "slug": "wegovy-vs-ozempic",
    "path": "/compare/wegovy-vs-ozempic",
    "title": "Wegovy vs Ozempic"
  },
  {
    "slug": "saxenda-vs-ozempic",
    "path": "/compare/saxenda-vs-ozempic",
    "title": "Saxenda vs Ozempic"
  },
  {
    "slug": "victoza-vs-mounjaro",
    "path": "/compare/victoza-vs-mounjaro",
    "title": "Victoza vs Mounjaro"
  },
  {
    "slug": "mounjaro-vs-victoza",
    "path": "/compare/mounjaro-vs-victoza",
    "title": "Mounjaro vs Victoza"
  },
  {
    "slug": "victoza-vs-trulicity",
    "path": "/compare/victoza-vs-trulicity",
    "title": "Victoza vs Trulicity"
  },
  {
    "slug": "trulicity-vs-victoza",
    "path": "/compare/trulicity-vs-victoza",
    "title": "Trulicity vs Victoza"
  },
  {
    "slug": "victoza-vs-rybelsus",
    "path": "/compare/victoza-vs-rybelsus",
    "title": "Victoza vs Rybelsus"
  },
  {
    "slug": "rybelsus-vs-victoza",
    "path": "/compare/rybelsus-vs-victoza",
    "title": "Rybelsus vs Victoza"
  },
  {
    "slug": "mounjaro-vs-ozempic",
    "path": "/compare/mounjaro-vs-ozempic",
    "title": "Mounjaro vs Ozempic"
  },
  {
    "slug": "victoza-vs-ozempic-for-weight-loss",
    "path": "/compare/victoza-vs-ozempic-for-weight-loss",
    "title": "Victoza vs Ozempic for Weight Loss"
  },
  {
    "slug": "victoza-vs-ozempic-for-diabetes",
    "path": "/compare/victoza-vs-ozempic-for-diabetes",
    "title": "Victoza vs Ozempic for Diabetes"
  },
  {
    "slug": "ozempic-vs-wegovy-for-weight-loss",
    "path": "/compare/ozempic-vs-wegovy-for-weight-loss",
    "title": "Ozempic vs Wegovy for Weight Loss"
  },
  {
    "slug": "mounjaro-vs-ozempic-for-weight-loss",
    "path": "/compare/mounjaro-vs-ozempic-for-weight-loss",
    "title": "Mounjaro vs Ozempic for Weight Loss"
  },
  {
    "slug": "liraglutide-vs-semaglutide",
    "path": "/compare/liraglutide-vs-semaglutide",
    "title": "Liraglutide vs Semaglutide"
  },
  {
    "slug": "mounjaro-vs-trulicity",
    "path": "/compare/mounjaro-vs-trulicity",
    "title": "Mounjaro vs Trulicity"
  },
  {
    "slug": "semaglutide-vs-dulaglutide",
    "path": "/compare/semaglutide-vs-dulaglutide",
    "title": "Semaglutide vs Dulaglutide"
  },
  {
    "slug": "rybelsus-vs-ozempic-for-diabetes",
    "path": "/compare/rybelsus-vs-ozempic-for-diabetes",
    "title": "Rybelsus vs Ozempic for Diabetes"
  },
  {
    "slug": "mounjaro-vs-saxenda-for-weight-loss",
    "path": "/compare/mounjaro-vs-saxenda-for-weight-loss",
    "title": "Mounjaro vs Saxenda for Weight Loss"
  },
  {
    "slug": "semax-vs-selank",
    "path": "/compare/semax-vs-selank",
    "title": "Semax vs Selank"
  },
  {
    "slug": "semax-vs-noopept",
    "path": "/compare/semax-vs-noopept",
    "title": "Semax vs Noopept"
  },
  {
    "slug": "noopept-vs-semax",
    "path": "/compare/noopept-vs-semax",
    "title": "Noopept vs Semax"
  },
  {
    "slug": "selank-vs-noopept",
    "path": "/compare/selank-vs-noopept",
    "title": "Selank vs Noopept"
  },
  {
    "slug": "noopept-vs-selank",
    "path": "/compare/noopept-vs-selank",
    "title": "Noopept vs Selank"
  },
  {
    "slug": "semax-vs-piracetam",
    "path": "/compare/semax-vs-piracetam",
    "title": "Semax vs Piracetam"
  },
  {
    "slug": "piracetam-vs-semax",
    "path": "/compare/piracetam-vs-semax",
    "title": "Piracetam vs Semax"
  },
  {
    "slug": "selank-vs-piracetam",
    "path": "/compare/selank-vs-piracetam",
    "title": "Selank vs Piracetam"
  },
  {
    "slug": "piracetam-vs-selank",
    "path": "/compare/piracetam-vs-selank",
    "title": "Piracetam vs Selank"
  },
  {
    "slug": "semax-vs-phenylpiracetam",
    "path": "/compare/semax-vs-phenylpiracetam",
    "title": "Semax vs Phenylpiracetam"
  },
  {
    "slug": "selank-vs-aniracetam",
    "path": "/compare/selank-vs-aniracetam",
    "title": "Selank vs Aniracetam"
  },
  {
    "slug": "semax-vs-selank-for-anxiety",
    "path": "/compare/semax-vs-selank-for-anxiety",
    "title": "Semax vs Selank for Anxiety"
  },
  {
    "slug": "semax-vs-selank-for-focus",
    "path": "/compare/semax-vs-selank-for-focus",
    "title": "Semax vs Selank for Focus"
  },
  {
    "slug": "semax-vs-selank-for-cognitive-enhancement",
    "path": "/compare/semax-vs-selank-for-cognitive-enhancement",
    "title": "Semax vs Selank for Cognitive Enhancement"
  },
  {
    "slug": "semaglutide-vs-aod-9604",
    "path": "/compare/semaglutide-vs-aod-9604",
    "title": "Semaglutide vs AOD 9604"
  },
  {
    "slug": "aod-9604-vs-semaglutide-for-weight-loss",
    "path": "/compare/aod-9604-vs-semaglutide-for-weight-loss",
    "title": "AOD 9604 vs Semaglutide for Weight Loss"
  },
  {
    "slug": "aod-9604-vs-retatrutide",
    "path": "/compare/aod-9604-vs-retatrutide",
    "title": "AOD 9604 vs Retatrutide"
  },
  {
    "slug": "aod-9604-vs-tesofensine",
    "path": "/compare/aod-9604-vs-tesofensine",
    "title": "AOD 9604 vs Tesofensine"
  },
  {
    "slug": "aod-9604-vs-liraglutide",
    "path": "/compare/aod-9604-vs-liraglutide",
    "title": "AOD 9604 vs Liraglutide"
  },
  {
    "slug": "aod-9604-vs-phentermine",
    "path": "/compare/aod-9604-vs-phentermine",
    "title": "AOD 9604 vs Phentermine"
  },
  {
    "slug": "semaglutide-vs-phentermine",
    "path": "/compare/semaglutide-vs-phentermine",
    "title": "Semaglutide vs Phentermine"
  },
  {
    "slug": "aod-9604-vs-motsc",
    "path": "/compare/aod-9604-vs-motsc",
    "title": "AOD 9604 vs MOTS-c"
  },
  {
    "slug": "aod-9604-vs-semaglutide-side-effects",
    "path": "/compare/aod-9604-vs-semaglutide-side-effects",
    "title": "AOD 9604 vs Semaglutide Side Effects"
  },
  {
    "slug": "ipamorelin-vs-tesamorelin",
    "path": "/compare/ipamorelin-vs-tesamorelin",
    "title": "Ipamorelin vs Tesamorelin"
  },
  {
    "slug": "sermorelin-vs-tesamorelin",
    "path": "/compare/sermorelin-vs-tesamorelin",
    "title": "Sermorelin vs Tesamorelin"
  },
  {
    "slug": "sermorelin-vs-cjc-1295",
    "path": "/compare/sermorelin-vs-cjc-1295",
    "title": "Sermorelin vs CJC-1295"
  },
  {
    "slug": "ipamorelin-vs-sermorelin-for-muscle-growth",
    "path": "/compare/ipamorelin-vs-sermorelin-for-muscle-growth",
    "title": "Ipamorelin vs Sermorelin for Muscle Growth"
  },
  {
    "slug": "ipamorelin-vs-sermorelin-for-anti-aging",
    "path": "/compare/ipamorelin-vs-sermorelin-for-anti-aging",
    "title": "Ipamorelin vs Sermorelin for Anti-Aging"
  },
  {
    "slug": "ipamorelin-vs-sermorelin-for-weight-loss",
    "path": "/compare/ipamorelin-vs-sermorelin-for-weight-loss",
    "title": "Ipamorelin vs Sermorelin for Weight Loss"
  },
  {
    "slug": "semax-vs-selank-dosage",
    "path": "/compare/semax-vs-selank-dosage",
    "title": "Semax vs Selank: Dosage Comparison"
  },
  {
    "slug": "aod-9604-vs-hgh-fragment",
    "path": "/compare/aod-9604-vs-hgh-fragment",
    "title": "AOD 9604 vs HGH Fragment 176-191"
  },
  {
    "slug": "semaglutide-vs-tirzepatide-vs-retatrutide",
    "path": "/compare/semaglutide-vs-tirzepatide-vs-retatrutide",
    "title": "Semaglutide vs Tirzepatide vs Retatrutide"
  },
  {
    "slug": "victoza-vs-ozempic-dosage",
    "path": "/compare/victoza-vs-ozempic-dosage",
    "title": "Victoza vs Ozempic: Dosage Comparison"
  },
  {
    "slug": "ipamorelin-vs-sermorelin-cost",
    "path": "/compare/ipamorelin-vs-sermorelin-cost",
    "title": "Ipamorelin vs Sermorelin: Cost Comparison"
  },
  {
    "slug": "semaglutide-vs-tirzepatide-for-weight-loss",
    "path": "/compare/semaglutide-vs-tirzepatide-for-weight-loss",
    "title": "Semaglutide vs Tirzepatide for Weight Loss"
  },
  {
    "slug": "saxenda-vs-wegovy",
    "path": "/compare/saxenda-vs-wegovy",
    "title": "Saxenda vs Wegovy"
  },
  {
    "slug": "aod-9604-vs-tirzepatide-for-weight-loss",
    "path": "/compare/aod-9604-vs-tirzepatide-for-weight-loss",
    "title": "AOD 9604 vs Tirzepatide for Weight Loss"
  },
  {
    "slug": "selank-vs-modafinil",
    "path": "/compare/selank-vs-modafinil",
    "title": "Selank vs Modafinil"
  },
  {
    "slug": "ipamorelin-vs-sermorelin-for-fat-loss",
    "path": "/compare/ipamorelin-vs-sermorelin-for-fat-loss",
    "title": "Ipamorelin vs Sermorelin for Fat Loss"
  },
  {
    "slug": "aod-9604-vs-clenbuterol",
    "path": "/compare/aod-9604-vs-clenbuterol",
    "title": "AOD 9604 vs Clenbuterol"
  },
  {
    "slug": "liraglutide-vs-tirzepatide",
    "path": "/compare/liraglutide-vs-tirzepatide",
    "title": "Liraglutide vs Tirzepatide"
  },
  {
    "slug": "semax-vs-aniracetam",
    "path": "/compare/semax-vs-aniracetam",
    "title": "Semax vs Aniracetam"
  },
  {
    "slug": "selank-vs-phenylpiracetam",
    "path": "/compare/selank-vs-phenylpiracetam",
    "title": "Selank vs Phenylpiracetam"
  },
  {
    "slug": "ipamorelin-vs-sermorelin-for-recovery",
    "path": "/compare/ipamorelin-vs-sermorelin-for-recovery",
    "title": "Ipamorelin vs Sermorelin for Recovery"
  },
  {
    "slug": "semaglutide-vs-retatrutide-for-weight-loss",
    "path": "/compare/semaglutide-vs-retatrutide-for-weight-loss",
    "title": "Semaglutide vs Retatrutide for Weight Loss"
  },
  {
    "slug": "aod-9604-vs-semaglutide-cost",
    "path": "/compare/aod-9604-vs-semaglutide-cost",
    "title": "AOD 9604 vs Semaglutide: Cost"
  },
  {
    "slug": "ozempic-vs-tirzepatide",
    "path": "/compare/ozempic-vs-tirzepatide",
    "title": "Ozempic vs Tirzepatide"
  },
  {
    "slug": "semax-vs-selank-stack",
    "path": "/compare/semax-vs-selank-stack",
    "title": "Semax and Selank Stack"
  }
];

export const batch6GoalEntries = [
  {
    "slug": "knee-pain",
    "path": "/goals/knee-pain",
    "title": "Best Peptides for Knee Pain"
  },
  {
    "slug": "back-pain",
    "path": "/goals/back-pain",
    "title": "Best Peptides for Back Pain"
  },
  {
    "slug": "shoulder-pain",
    "path": "/goals/shoulder-pain",
    "title": "Best Peptides for Shoulder Pain"
  },
  {
    "slug": "hip-pain",
    "path": "/goals/hip-pain",
    "title": "Best Peptides for Hip Pain"
  },
  {
    "slug": "joint-repair",
    "path": "/goals/joint-repair",
    "title": "Best Peptides for Joint Repair"
  },
  {
    "slug": "healing",
    "path": "/goals/healing",
    "title": "Best Peptides for Healing"
  },
  {
    "slug": "muscle-healing",
    "path": "/goals/muscle-healing",
    "title": "Best Peptides for Muscle Healing"
  },
  {
    "slug": "tendon-healing",
    "path": "/goals/tendon-healing",
    "title": "Best Peptides for Tendon Healing"
  },
  {
    "slug": "bone-healing",
    "path": "/goals/bone-healing",
    "title": "Best Peptides for Bone Healing"
  },
  {
    "slug": "ligament-healing",
    "path": "/goals/ligament-healing",
    "title": "Best Peptides for Ligament Healing"
  },
  {
    "slug": "soft-tissue-healing",
    "path": "/goals/soft-tissue-healing",
    "title": "Best Peptides for Soft Tissue Healing"
  },
  {
    "slug": "nerve-healing",
    "path": "/goals/nerve-healing",
    "title": "Best Peptides for Nerve Healing"
  },
  {
    "slug": "skin-healing",
    "path": "/goals/skin-healing",
    "title": "Best Peptides for Skin Healing"
  },
  {
    "slug": "gut-healing",
    "path": "/goals/gut-healing",
    "title": "Best Peptides for Gut Healing"
  },
  {
    "slug": "crossfit",
    "path": "/goals/crossfit",
    "title": "Best Peptides for CrossFit"
  },
  {
    "slug": "hiit",
    "path": "/goals/hiit",
    "title": "Best Peptides for HIIT"
  },
  {
    "slug": "functional-fitness",
    "path": "/goals/functional-fitness",
    "title": "Best Peptides for Functional Fitness"
  },
  {
    "slug": "endurance-athletes",
    "path": "/goals/endurance-athletes",
    "title": "Best Peptides for Endurance Athletes"
  },
  {
    "slug": "runners",
    "path": "/goals/runners",
    "title": "Best Peptides for Runners"
  },
  {
    "slug": "weightlifting",
    "path": "/goals/weightlifting",
    "title": "Best Peptides for Weightlifting"
  },
  {
    "slug": "bodybuilding",
    "path": "/goals/bodybuilding",
    "title": "Best Peptides for Bodybuilding"
  },
  {
    "slug": "strength-training",
    "path": "/goals/strength-training",
    "title": "Best Peptides for Strength Training"
  },
  {
    "slug": "athletic-performance",
    "path": "/goals/athletic-performance",
    "title": "Best Peptides for Athletic Performance"
  },
  {
    "slug": "combat-sports",
    "path": "/goals/combat-sports",
    "title": "Best Peptides for Combat Sports"
  },
  {
    "slug": "surgery-recovery",
    "path": "/goals/surgery-recovery",
    "title": "Best Peptides for Surgery Recovery"
  },
  {
    "slug": "post-op-recovery",
    "path": "/goals/post-op-recovery",
    "title": "Best Peptides for Post-Op Recovery"
  },
  {
    "slug": "acl-surgery-recovery",
    "path": "/goals/acl-surgery-recovery",
    "title": "Best Peptides for ACL Surgery Recovery"
  },
  {
    "slug": "rotator-cuff-surgery",
    "path": "/goals/rotator-cuff-surgery",
    "title": "Best Peptides for Rotator Cuff Surgery Recovery"
  },
  {
    "slug": "joint-replacement-recovery",
    "path": "/goals/joint-replacement-recovery",
    "title": "Best Peptides for Joint Replacement Recovery"
  },
  {
    "slug": "spinal-surgery-recovery",
    "path": "/goals/spinal-surgery-recovery",
    "title": "Best Peptides for Spinal Surgery Recovery"
  },
  {
    "slug": "meniscus-surgery",
    "path": "/goals/meniscus-surgery",
    "title": "Best Peptides for Meniscus Surgery Recovery"
  },
  {
    "slug": "hernia-repair-recovery",
    "path": "/goals/hernia-repair-recovery",
    "title": "Best Peptides for Hernia Repair Recovery"
  },
  {
    "slug": "tendon-surgery-recovery",
    "path": "/goals/tendon-surgery-recovery",
    "title": "Best Peptides for Tendon Surgery Recovery"
  },
  {
    "slug": "workout-recovery",
    "path": "/goals/workout-recovery",
    "title": "Best Peptides for Workout Recovery"
  },
  {
    "slug": "exercise-recovery",
    "path": "/goals/exercise-recovery",
    "title": "Best Peptides for Exercise Recovery"
  },
  {
    "slug": "sports-recovery",
    "path": "/goals/sports-recovery",
    "title": "Best Peptides for Sports Recovery"
  },
  {
    "slug": "post-workout-recovery",
    "path": "/goals/post-workout-recovery",
    "title": "Best Peptides for Post-Workout Recovery"
  },
  {
    "slug": "training-recovery",
    "path": "/goals/training-recovery",
    "title": "Best Peptides for Training Recovery"
  },
  {
    "slug": "fatigue-recovery",
    "path": "/goals/fatigue-recovery",
    "title": "Best Peptides for Fatigue Recovery"
  },
  {
    "slug": "faster-recovery",
    "path": "/goals/faster-recovery",
    "title": "Best Peptides for Faster Recovery"
  },
  {
    "slug": "overtraining-recovery",
    "path": "/goals/overtraining-recovery",
    "title": "Best Peptides for Overtraining Recovery"
  },
  {
    "slug": "fracture-healing",
    "path": "/goals/fracture-healing",
    "title": "Best Peptides for Fracture Healing"
  },
  {
    "slug": "connective-tissue",
    "path": "/goals/connective-tissue",
    "title": "Best Peptides for Connective Tissue"
  },
  {
    "slug": "joint-mobility",
    "path": "/goals/joint-mobility",
    "title": "Best Peptides for Joint Mobility"
  },
  {
    "slug": "muscle-strain",
    "path": "/goals/muscle-strain",
    "title": "Best Peptides for Muscle Strain"
  },
  {
    "slug": "tendonitis",
    "path": "/goals/tendonitis",
    "title": "Best Peptides for Tendonitis"
  },
  {
    "slug": "sprain-recovery",
    "path": "/goals/sprain-recovery",
    "title": "Best Peptides for Sprain Recovery"
  },
  {
    "slug": "post-training-recovery",
    "path": "/goals/post-training-recovery",
    "title": "Best Peptides for Post-Training Recovery"
  },
  {
    "slug": "mobility",
    "path": "/goals/mobility",
    "title": "Best Peptides for Mobility"
  },
  {
    "slug": "immune-recovery",
    "path": "/goals/immune-recovery",
    "title": "Best Peptides for Immune Recovery"
  },
  {
    "slug": "sleep-and-recovery",
    "path": "/goals/sleep-and-recovery",
    "title": "Best Peptides for Sleep and Recovery"
  },
  {
    "slug": "post-marathon-recovery",
    "path": "/goals/post-marathon-recovery",
    "title": "Best Peptides for Post-Marathon Recovery"
  },
  {
    "slug": "strength-and-recovery",
    "path": "/goals/strength-and-recovery",
    "title": "Best Peptides for Strength and Recovery"
  },
  {
    "slug": "labral-tear-recovery",
    "path": "/goals/labral-tear-recovery",
    "title": "Best Peptides for Labral Tear Recovery"
  },
  {
    "slug": "cervical-fusion-recovery",
    "path": "/goals/cervical-fusion-recovery",
    "title": "Best Peptides for Cervical Fusion Recovery"
  },
  {
    "slug": "meniscus-tear-recovery",
    "path": "/goals/meniscus-tear-recovery",
    "title": "Best Peptides for Meniscus Tear Recovery"
  },
  {
    "slug": "achilles-tendon-recovery",
    "path": "/goals/achilles-tendon-recovery",
    "title": "Best Peptides for Achilles Tendon Recovery"
  },
  {
    "slug": "hamstring-recovery",
    "path": "/goals/hamstring-recovery",
    "title": "Best Peptides for Hamstring Recovery"
  },
  {
    "slug": "groin-pull-recovery",
    "path": "/goals/groin-pull-recovery",
    "title": "Best Peptides for Groin Pull Recovery"
  },
  {
    "slug": "shin-splints",
    "path": "/goals/shin-splints",
    "title": "Best Peptides for Shin Splints"
  },
  {
    "slug": "golfs-elbow",
    "path": "/goals/golfs-elbow",
    "title": "Best Peptides for Golfer's Elbow"
  },
  {
    "slug": "bursitis",
    "path": "/goals/bursitis",
    "title": "Best Peptides for Bursitis"
  },
  {
    "slug": "si-joint-pain",
    "path": "/goals/si-joint-pain",
    "title": "Best Peptides for SI Joint Pain"
  },
  {
    "slug": "neck-pain",
    "path": "/goals/neck-pain",
    "title": "Best Peptides for Neck Pain"
  },
  {
    "slug": "tmj-pain",
    "path": "/goals/tmj-pain",
    "title": "Best Peptides for TMJ Pain"
  },
  {
    "slug": "rib-injury-recovery",
    "path": "/goals/rib-injury-recovery",
    "title": "Best Peptides for Rib Injury Recovery"
  },
  {
    "slug": "hip-flexor-recovery",
    "path": "/goals/hip-flexor-recovery",
    "title": "Best Peptides for Hip Flexor Recovery"
  },
  {
    "slug": "muscle-cramps",
    "path": "/goals/muscle-cramps",
    "title": "Best Peptides for Muscle Cramps"
  },
  {
    "slug": "spine-health",
    "path": "/goals/spine-health",
    "title": "Best Peptides for Spine Health"
  },
  {
    "slug": "disc-bulge-recovery",
    "path": "/goals/disc-bulge-recovery",
    "title": "Best Peptides for Disc Bulge Recovery"
  },
  {
    "slug": "piriformis-syndrome",
    "path": "/goals/piriformis-syndrome",
    "title": "Best Peptides for Piriformis Syndrome"
  },
  {
    "slug": "costochondritis",
    "path": "/goals/costochondritis",
    "title": "Best Peptides for Costochondritis"
  },
  {
    "slug": "rib-fracture-healing",
    "path": "/goals/rib-fracture-healing",
    "title": "Best Peptides for Rib Fracture Healing"
  },
  {
    "slug": "posture-support",
    "path": "/goals/posture-support",
    "title": "Best Peptides for Posture Support"
  },
  {
    "slug": "core-strength-recovery",
    "path": "/goals/core-strength-recovery",
    "title": "Best Peptides for Core Strength Recovery"
  },
  {
    "slug": "pelvic-floor-recovery",
    "path": "/goals/pelvic-floor-recovery",
    "title": "Best Peptides for Pelvic Floor Recovery"
  },
  {
    "slug": "overuse-injury",
    "path": "/goals/overuse-injury",
    "title": "Best Peptides for Overuse Injury"
  },
  {
    "slug": "stress-fracture-recovery",
    "path": "/goals/stress-fracture-recovery",
    "title": "Best Peptides for Stress Fracture Recovery"
  },
  {
    "slug": "weightlifting-injury-recovery",
    "path": "/goals/weightlifting-injury-recovery",
    "title": "Best Peptides for Weightlifting Injury Recovery"
  }
];