/* Auto-generated by scripts/export-static-content.ts. */
import type { PseoSection } from "./pseo";

export const pseoSections = [
  {
    "key": "peptides",
    "label": "Peptide Library",
    "path": "/peptides",
    "description": "Profiles for 12+ research peptides.",
    "entries": [
      {
        "slug": "bpc-157",
        "path": "/peptides/bpc-157",
        "title": "BPC-157"
      },
      {
        "slug": "tb-500",
        "path": "/peptides/tb-500",
        "title": "TB-500"
      },
      {
        "slug": "ipamorelin",
        "path": "/peptides/ipamorelin",
        "title": "Ipamorelin"
      },
      {
        "slug": "cjc-1295",
        "path": "/peptides/cjc-1295",
        "title": "CJC-1295"
      },
      {
        "slug": "sermorelin",
        "path": "/peptides/sermorelin",
        "title": "Sermorelin"
      },
      {
        "slug": "semaglutide",
        "path": "/peptides/semaglutide",
        "title": "Semaglutide"
      },
      {
        "slug": "tirzepatide",
        "path": "/peptides/tirzepatide",
        "title": "Tirzepatide"
      },
      {
        "slug": "ghk-cu",
        "path": "/peptides/ghk-cu",
        "title": "GHK-Cu"
      },
      {
        "slug": "epithalon",
        "path": "/peptides/epithalon",
        "title": "Epithalon"
      },
      {
        "slug": "selank",
        "path": "/peptides/selank",
        "title": "Selank"
      },
      {
        "slug": "semax",
        "path": "/peptides/semax",
        "title": "Semax"
      },
      {
        "slug": "pt-141",
        "path": "/peptides/pt-141",
        "title": "PT-141"
      },
      {
        "slug": "nad-plus",
        "path": "/peptides/nad-plus",
        "title": "NAD+"
      },
      {
        "slug": "methylene-blue",
        "path": "/peptides/methylene-blue",
        "title": "Methylene Blue"
      },
      {
        "slug": "glutathione",
        "path": "/peptides/glutathione",
        "title": "Glutathione"
      },
      {
        "slug": "rapamycin",
        "path": "/peptides/rapamycin",
        "title": "Rapamycin"
      },
      {
        "slug": "low-dose-naltrexone",
        "path": "/peptides/low-dose-naltrexone",
        "title": "Low Dose Naltrexone (LDN)"
      },
      {
        "slug": "metformin",
        "path": "/peptides/metformin",
        "title": "Metformin"
      },
      {
        "slug": "oxandrolone",
        "path": "/peptides/oxandrolone",
        "title": "Oxandrolone (Anavar)"
      },
      {
        "slug": "nandrolone",
        "path": "/peptides/nandrolone",
        "title": "Nandrolone (Deca)"
      },
      {
        "slug": "retatrutide",
        "path": "/peptides/retatrutide",
        "title": "Retatrutide"
      },
      {
        "slug": "kpv",
        "path": "/peptides/kpv",
        "title": "KPV"
      },
      {
        "slug": "mots-c",
        "path": "/peptides/mots-c",
        "title": "MOTS-c"
      },
      {
        "slug": "ll-37",
        "path": "/peptides/ll-37",
        "title": "LL-37"
      },
      {
        "slug": "humanin",
        "path": "/peptides/humanin",
        "title": "Humanin"
      },
      {
        "slug": "orforglipron",
        "path": "/peptides/orforglipron",
        "title": "Orforglipron"
      },
      {
        "slug": "dihexa",
        "path": "/peptides/dihexa",
        "title": "Dihexa"
      },
      {
        "slug": "tesamorelin",
        "path": "/peptides/tesamorelin",
        "title": "Tesamorelin"
      },
      {
        "slug": "aod-9604",
        "path": "/peptides/aod-9604",
        "title": "AOD-9604"
      },
      {
        "slug": "ss-31",
        "path": "/peptides/ss-31",
        "title": "SS-31"
      },
      {
        "slug": "tesamorelin",
        "path": "/peptides/tesamorelin",
        "title": "Tesamorelin"
      },
      {
        "slug": "aod-9604",
        "path": "/peptides/aod-9604",
        "title": "AOD-9604"
      },
      {
        "slug": "kisspeptin",
        "path": "/peptides/kisspeptin",
        "title": "Kisspeptin"
      },
      {
        "slug": "dsip",
        "path": "/peptides/dsip",
        "title": "DSIP"
      },
      {
        "slug": "cerebrolysin",
        "path": "/peptides/cerebrolysin",
        "title": "Cerebrolysin"
      },
      {
        "slug": "dihexa",
        "path": "/peptides/dihexa",
        "title": "Dihexa"
      },
      {
        "slug": "ll-37",
        "path": "/peptides/ll-37",
        "title": "LL-37"
      },
      {
        "slug": "thymosin-alpha-1",
        "path": "/peptides/thymosin-alpha-1",
        "title": "Thymosin Alpha-1"
      },
      {
        "slug": "melanotan-2",
        "path": "/peptides/melanotan-2",
        "title": "Melanotan 2"
      },
      {
        "slug": "snap-8",
        "path": "/peptides/snap-8",
        "title": "SNAP-8"
      },
      {
        "slug": "argireline",
        "path": "/peptides/argireline",
        "title": "Argireline"
      },
      {
        "slug": "humanin",
        "path": "/peptides/humanin",
        "title": "Humanin"
      },
      {
        "slug": "mots-c",
        "path": "/peptides/mots-c",
        "title": "MOTS-C"
      },
      {
        "slug": "foxo4-dri",
        "path": "/peptides/foxo4-dri",
        "title": "FOXO4-DRI"
      },
      {
        "slug": "ss-31",
        "path": "/peptides/ss-31",
        "title": "SS-31"
      },
      {
        "slug": "vip",
        "path": "/peptides/vip",
        "title": "VIP"
      },
      {
        "slug": "kpv",
        "path": "/peptides/kpv",
        "title": "KPV"
      },
      {
        "slug": "ara-290",
        "path": "/peptides/ara-290",
        "title": "ARA-290"
      },
      {
        "slug": "peg-mgf",
        "path": "/peptides/peg-mgf",
        "title": "PEG-MGF"
      },
      {
        "slug": "igf-1-lr3",
        "path": "/peptides/igf-1-lr3",
        "title": "IGF-1-LR3"
      }
    ]
  },
  {
    "key": "goals",
    "label": "Goals",
    "path": "/goals",
    "description": "Find peptides by health goal.",
    "entries": [
      {
        "slug": "muscle-growth",
        "path": "/goals/muscle-growth",
        "title": "Best Peptides for Muscle Growth"
      },
      {
        "slug": "fat-loss",
        "path": "/goals/fat-loss",
        "title": "Best Peptides for Fat Loss"
      },
      {
        "slug": "joint-recovery",
        "path": "/goals/joint-recovery",
        "title": "Best Peptides for Joint Recovery"
      },
      {
        "slug": "gut-health",
        "path": "/goals/gut-health",
        "title": "Best Peptides for Gut Health"
      },
      {
        "slug": "anti-aging",
        "path": "/goals/anti-aging",
        "title": "Best Peptides for Anti-Aging"
      },
      {
        "slug": "sleep-optimization",
        "path": "/goals/sleep-optimization",
        "title": "Best Peptides for Sleep"
      },
      {
        "slug": "cognitive-performance",
        "path": "/goals/cognitive-performance",
        "title": "Best Peptides for Cognitive Performance"
      },
      {
        "slug": "anxiety-reduction",
        "path": "/goals/anxiety-reduction",
        "title": "Best Peptides for Anxiety"
      },
      {
        "slug": "skin-health",
        "path": "/goals/skin-health",
        "title": "Best Peptides for Skin Health"
      },
      {
        "slug": "hair-growth",
        "path": "/goals/hair-growth",
        "title": "Best Peptides for Hair Growth"
      },
      {
        "slug": "longevity",
        "path": "/goals/longevity",
        "title": "Best Peptides for Longevity"
      },
      {
        "slug": "body-recomposition",
        "path": "/goals/body-recomposition",
        "title": "Best Peptides for Body Recomposition"
      },
      {
        "slug": "injury-recovery",
        "path": "/goals/injury-recovery",
        "title": "Best Peptides for Injury Recovery"
      },
      {
        "slug": "energy",
        "path": "/goals/energy",
        "title": "Best Peptides for Energy"
      },
      {
        "slug": "libido",
        "path": "/goals/libido",
        "title": "Best Peptides for Libido"
      },
      {
        "slug": "inflammation",
        "path": "/goals/inflammation",
        "title": "Best Peptides for Inflammation"
      },
      {
        "slug": "metabolic-health",
        "path": "/goals/metabolic-health",
        "title": "Best Peptides for Metabolic Health"
      },
      {
        "slug": "muscle-recovery",
        "path": "/goals/muscle-recovery",
        "title": "Best Peptides for Muscle Recovery"
      },
      {
        "slug": "bone-density",
        "path": "/goals/bone-density",
        "title": "Best Peptides for Bone Density Support in 2026"
      },
      {
        "slug": "wound-repair",
        "path": "/goals/wound-repair",
        "title": "Best Peptides for Wound Repair Support in 2026"
      },
      {
        "slug": "immune-support",
        "path": "/goals/immune-support",
        "title": "Best Peptides for Immune Support in 2026"
      },
      {
        "slug": "neuroprotection",
        "path": "/goals/neuroprotection",
        "title": "Best Peptides for Neuroprotection in 2026"
      },
      {
        "slug": "cardiovascular-health",
        "path": "/goals/cardiovascular-health",
        "title": "Best Peptides for Cardiovascular Health in 2026"
      },
      {
        "slug": "blood-sugar-control",
        "path": "/goals/blood-sugar-control",
        "title": "Best Peptides for Blood Sugar Control in 2026"
      },
      {
        "slug": "vision-health",
        "path": "/goals/vision-health",
        "title": "Best Peptides for Vision Health Support in 2026"
      },
      {
        "slug": "hearing-support",
        "path": "/goals/hearing-support",
        "title": "Best Peptides for Hearing Support in 2026"
      },
      {
        "slug": "nerve-regeneration",
        "path": "/goals/nerve-regeneration",
        "title": "Best Peptides for Nerve Regeneration in 2026"
      },
      {
        "slug": "cartilage-repair",
        "path": "/goals/cartilage-repair",
        "title": "Best Peptides for Cartilage Repair Support in 2026"
      },
      {
        "slug": "muscle-endurance",
        "path": "/goals/muscle-endurance",
        "title": "Best Peptides for Muscle Endurance in 2026"
      },
      {
        "slug": "sprint-performance",
        "path": "/goals/sprint-performance",
        "title": "Best Peptides for Sprint Performance in 2026"
      },
      {
        "slug": "vo2-max",
        "path": "/goals/vo2-max",
        "title": "Best Peptides for VO2 Max Support in 2026"
      },
      {
        "slug": "focus-and-concentration",
        "path": "/goals/focus-and-concentration",
        "title": "Best Peptides for Focus and Concentration"
      },
      {
        "slug": "memory-retention",
        "path": "/goals/memory-retention",
        "title": "Best Peptides for Memory Retention in 2026"
      },
      {
        "slug": "verbal-fluency",
        "path": "/goals/verbal-fluency",
        "title": "Best Peptides for Verbal Fluency Support"
      },
      {
        "slug": "stress-resilience",
        "path": "/goals/stress-resilience",
        "title": "Best Peptides for Stress Resilience in 2026"
      },
      {
        "slug": "mood-elevation",
        "path": "/goals/mood-elevation",
        "title": "Best Peptides for Mood Elevation Support"
      },
      {
        "slug": "social-anxiety",
        "path": "/goals/social-anxiety",
        "title": "Best Peptides for Social Anxiety Support"
      },
      {
        "slug": "ptsd-support",
        "path": "/goals/ptsd-support",
        "title": "Best Peptides for PTSD Recovery Support in 2026"
      },
      {
        "slug": "collagen-production",
        "path": "/goals/collagen-production",
        "title": "Best Peptides for Collagen Production in 2026"
      },
      {
        "slug": "elastin-production",
        "path": "/goals/elastin-production",
        "title": "Best Peptides for Elastin Production in 2026"
      },
      {
        "slug": "sun-damage-repair",
        "path": "/goals/sun-damage-repair",
        "title": "Best Peptides for Sun Damage Repair in 2026"
      },
      {
        "slug": "scar-reduction",
        "path": "/goals/scar-reduction",
        "title": "Best Peptides for Scar Reduction Support"
      },
      {
        "slug": "hyperpigmentation",
        "path": "/goals/hyperpigmentation",
        "title": "Best Peptides for Hyperpigmentation in 2026"
      },
      {
        "slug": "nail-health",
        "path": "/goals/nail-health",
        "title": "Best Peptides for Nail Health Support in 2026"
      },
      {
        "slug": "gut-motility",
        "path": "/goals/gut-motility",
        "title": "Best Peptides for Gut Motility Support in 2026"
      },
      {
        "slug": "microbiome-diversity",
        "path": "/goals/microbiome-diversity",
        "title": "Best Peptides for Microbiome Diversity in 2026"
      },
      {
        "slug": "gastric-ulcer-healing",
        "path": "/goals/gastric-ulcer-healing",
        "title": "Best Peptides for Gastric Ulcer Healing in 2026"
      },
      {
        "slug": "ibd-support",
        "path": "/goals/ibd-support",
        "title": "Best Peptides for IBD Gut Support in 2026"
      },
      {
        "slug": "muscle-recovery-women",
        "path": "/goals/muscle-recovery-women",
        "title": "Best Peptides for Muscle Recovery in Women in 2026"
      },
      {
        "slug": "fat-loss-men-over-40",
        "path": "/goals/fat-loss-men-over-40",
        "title": "Best Peptides for Fat Loss in Men Over 40 in 2026"
      },
      {
        "slug": "joint-pain-runners",
        "path": "/goals/joint-pain-runners",
        "title": "Best Peptides for Joint Pain in Runners in 2026"
      },
      {
        "slug": "gut-health-athletes",
        "path": "/goals/gut-health-athletes",
        "title": "Best Peptides for Gut Health in Athletes in 2026"
      },
      {
        "slug": "anti-aging-skin-care",
        "path": "/goals/anti-aging-skin-care",
        "title": "Best Peptides for Anti-Aging Skin Care in 2026"
      },
      {
        "slug": "post-surgery-recovery",
        "path": "/goals/post-surgery-recovery",
        "title": "Best Peptides for Post-Surgery Recovery in 2026"
      },
      {
        "slug": "burn-healing",
        "path": "/goals/burn-healing",
        "title": "Best Peptides for Severe Burn Healing in 2026"
      },
      {
        "slug": "bone-fracture-healing",
        "path": "/goals/bone-fracture-healing",
        "title": "Best Peptides for Bone Fracture Healing in 2026"
      },
      {
        "slug": "concussion-recovery",
        "path": "/goals/concussion-recovery",
        "title": "Best Peptides for Concussion Recovery in 2026"
      },
      {
        "slug": "stroke-recovery",
        "path": "/goals/stroke-recovery",
        "title": "Best Peptides for Stroke Recovery in 2026"
      },
      {
        "slug": "body-recomposition",
        "path": "/goals/body-recomposition",
        "title": "Best Peptides for Body Recomposition in 2026"
      },
      {
        "slug": "immune-function",
        "path": "/goals/immune-function",
        "title": "Best Peptides for Immune Function in 2026"
      },
      {
        "slug": "hormone-balance",
        "path": "/goals/hormone-balance",
        "title": "Best Peptides for Hormone Balance in 2026"
      },
      {
        "slug": "focus",
        "path": "/goals/focus",
        "title": "Best Peptides for Focus and Concentration in 2026"
      },
      {
        "slug": "bodybuilding-performance",
        "path": "/goals/bodybuilding-performance",
        "title": "Best Peptides for Bodybuilding Performance in 2026"
      },
      {
        "slug": "cognitive-performance",
        "path": "/goals/cognitive-performance",
        "title": "Best Peptides for Cognitive Performance in 2026"
      },
      {
        "slug": "muscle-recovery",
        "path": "/goals/muscle-recovery",
        "title": "Best Peptides for Muscle Recovery in 2026"
      },
      {
        "slug": "anxiety-reduction",
        "path": "/goals/anxiety-reduction",
        "title": "Best Peptides for Anxiety Reduction in 2026"
      },
      {
        "slug": "joint-recovery",
        "path": "/goals/joint-recovery",
        "title": "Best Peptides for Joint Recovery in 2026"
      },
      {
        "slug": "gut-health",
        "path": "/goals/gut-health",
        "title": "Best Peptides for Gut Health in 2026"
      },
      {
        "slug": "injury-recovery",
        "path": "/goals/injury-recovery",
        "title": "Best Peptides for Injury Recovery in 2026"
      },
      {
        "slug": "fat-loss",
        "path": "/goals/fat-loss",
        "title": "Best Peptides for Fat Loss in 2026"
      },
      {
        "slug": "memory",
        "path": "/goals/memory",
        "title": "Best Peptides for Memory in 2026"
      },
      {
        "slug": "metabolic-health",
        "path": "/goals/metabolic-health",
        "title": "Best Peptides for Metabolic Health in 2026"
      },
      {
        "slug": "recovery",
        "path": "/goals/recovery",
        "title": "Best Peptides for Recovery in 2026"
      },
      {
        "slug": "skin-health",
        "path": "/goals/skin-health",
        "title": "Best Peptides for Skin Health in 2026"
      }
    ]
  },
  {
    "key": "compare",
    "label": "Compare",
    "path": "/compare",
    "description": "Head-to-head peptide comparisons.",
    "entries": [
      {
        "slug": "bpc-157-vs-tb-500",
        "path": "/compare/bpc-157-vs-tb-500",
        "title": "BPC-157 vs TB-500"
      },
      {
        "slug": "semaglutide-vs-tirzepatide",
        "path": "/compare/semaglutide-vs-tirzepatide",
        "title": "Semaglutide vs Tirzepatide"
      },
      {
        "slug": "ipamorelin-vs-cjc-1295",
        "path": "/compare/ipamorelin-vs-cjc-1295",
        "title": "Ipamorelin vs CJC-1295"
      },
      {
        "slug": "ozempic-vs-wegovy",
        "path": "/compare/ozempic-vs-wegovy",
        "title": "Ozempic vs Wegovy"
      },
      {
        "slug": "mounjaro-vs-zepbound",
        "path": "/compare/mounjaro-vs-zepbound",
        "title": "Mounjaro vs Zepbound"
      },
      {
        "slug": "selank-vs-semax",
        "path": "/compare/selank-vs-semax",
        "title": "Selank vs Semax"
      },
      {
        "slug": "epithalon-vs-ghk-cu",
        "path": "/compare/epithalon-vs-ghk-cu",
        "title": "Epithalon vs GHK-Cu"
      },
      {
        "slug": "sermorelin-vs-ipamorelin",
        "path": "/compare/sermorelin-vs-ipamorelin",
        "title": "Sermorelin vs Ipamorelin"
      },
      {
        "slug": "bpc-157-vs-ghk-cu",
        "path": "/compare/bpc-157-vs-ghk-cu",
        "title": "BPC-157 vs GHK-Cu"
      },
      {
        "slug": "tb-500-vs-ghk-cu",
        "path": "/compare/tb-500-vs-ghk-cu",
        "title": "TB-500 vs GHK-Cu"
      },
      {
        "slug": "tesamorelin-vs-ipamorelin",
        "path": "/compare/tesamorelin-vs-ipamorelin",
        "title": "Tesamorelin vs Ipamorelin"
      },
      {
        "slug": "semaglutide-vs-retatrutide",
        "path": "/compare/semaglutide-vs-retatrutide",
        "title": "Semaglutide vs Retatrutide"
      },
      {
        "slug": "aod-9604-vs-semaglutide",
        "path": "/compare/aod-9604-vs-semaglutide",
        "title": "AOD-9604 vs Semaglutide"
      },
      {
        "slug": "cjc-1295-vs-ghrp-6",
        "path": "/compare/cjc-1295-vs-ghrp-6",
        "title": "CJC-1295 vs GHRP-6"
      },
      {
        "slug": "pt-141-vs-kisspeptin",
        "path": "/compare/pt-141-vs-kisspeptin",
        "title": "PT-141 vs Kisspeptin"
      },
      {
        "slug": "semaglutide-vs-liraglutide",
        "path": "/compare/semaglutide-vs-liraglutide",
        "title": "Semaglutide vs Liraglutide"
      },
      {
        "slug": "mots-c-vs-nad",
        "path": "/compare/mots-c-vs-nad",
        "title": "MOTS-c vs NAD+"
      },
      {
        "slug": "ozempic-vs-mounjaro",
        "path": "/compare/ozempic-vs-mounjaro",
        "title": "Ozempic vs Mounjaro"
      },
      {
        "slug": "ozempic-vs-saxenda",
        "path": "/compare/ozempic-vs-saxenda",
        "title": "Ozempic vs Saxenda"
      },
      {
        "slug": "wegovy-vs-mounjaro",
        "path": "/compare/wegovy-vs-mounjaro",
        "title": "Wegovy vs Mounjaro"
      },
      {
        "slug": "wegovy-vs-saxenda",
        "path": "/compare/wegovy-vs-saxenda",
        "title": "Wegovy vs Saxenda"
      },
      {
        "slug": "tirzepatide-vs-retatrutide",
        "path": "/compare/tirzepatide-vs-retatrutide",
        "title": "Tirzepatide vs Retatrutide"
      },
      {
        "slug": "ozempic-vs-rybelsus",
        "path": "/compare/ozempic-vs-rybelsus",
        "title": "Ozempic vs Rybelsus"
      },
      {
        "slug": "trulicity-vs-ozempic",
        "path": "/compare/trulicity-vs-ozempic",
        "title": "Trulicity vs Ozempic"
      },
      {
        "slug": "victoza-vs-ozempic",
        "path": "/compare/victoza-vs-ozempic",
        "title": "Victoza vs Ozempic"
      },
      {
        "slug": "ipamorelin-vs-sermorelin",
        "path": "/compare/ipamorelin-vs-sermorelin",
        "title": "Ipamorelin vs Sermorelin"
      },
      {
        "slug": "cjc-1295-vs-sermorelin",
        "path": "/compare/cjc-1295-vs-sermorelin",
        "title": "CJC-1295 vs Sermorelin"
      },
      {
        "slug": "ghrp-6-vs-ghrp-2",
        "path": "/compare/ghrp-6-vs-ghrp-2",
        "title": "GHRP-6 vs GHRP-2"
      },
      {
        "slug": "ipamorelin-vs-ghrp-6",
        "path": "/compare/ipamorelin-vs-ghrp-6",
        "title": "Ipamorelin vs GHRP-6"
      },
      {
        "slug": "ipamorelin-vs-ghrp-2",
        "path": "/compare/ipamorelin-vs-ghrp-2",
        "title": "Ipamorelin vs GHRP-2"
      },
      {
        "slug": "hexarelin-vs-ipamorelin",
        "path": "/compare/hexarelin-vs-ipamorelin",
        "title": "Hexarelin vs Ipamorelin"
      },
      {
        "slug": "tesamorelin-vs-sermorelin",
        "path": "/compare/tesamorelin-vs-sermorelin",
        "title": "Tesamorelin vs Sermorelin"
      },
      {
        "slug": "cjc-1295-dac-vs-no-dac",
        "path": "/compare/cjc-1295-dac-vs-no-dac",
        "title": "CJC-1295 with DAC vs CJC-1295 without DAC (Mod GRF 1-29)"
      },
      {
        "slug": "sermorelin-vs-hgh",
        "path": "/compare/sermorelin-vs-hgh",
        "title": "Sermorelin vs HGH (Synthetic)"
      },
      {
        "slug": "ipamorelin-vs-hgh",
        "path": "/compare/ipamorelin-vs-hgh",
        "title": "Ipamorelin vs HGH (Synthetic)"
      },
      {
        "slug": "bpc-157-vs-ipamorelin",
        "path": "/compare/bpc-157-vs-ipamorelin",
        "title": "BPC-157 vs Ipamorelin"
      },
      {
        "slug": "epithalon-vs-nad",
        "path": "/compare/epithalon-vs-nad",
        "title": "Epithalon vs NAD+"
      },
      {
        "slug": "ghk-cu-vs-nad",
        "path": "/compare/ghk-cu-vs-nad",
        "title": "GHK-Cu vs NAD+"
      },
      {
        "slug": "nad-vs-nmn",
        "path": "/compare/nad-vs-nmn",
        "title": "NAD+ (IV) vs NMN (Oral)"
      },
      {
        "slug": "nad-vs-niacin",
        "path": "/compare/nad-vs-niacin",
        "title": "NAD+ / NMN vs Niacin (Vitamin B3)"
      },
      {
        "slug": "selank-vs-semax-anxiety",
        "path": "/compare/selank-vs-semax-anxiety",
        "title": "Selank vs Semax"
      },
      {
        "slug": "semax-vs-dihexa",
        "path": "/compare/semax-vs-dihexa",
        "title": "Semax vs Dihexa"
      },
      {
        "slug": "pt-141-vs-tadalafil",
        "path": "/compare/pt-141-vs-tadalafil",
        "title": "PT-141 vs Tadalafil (Cialis)"
      },
      {
        "slug": "pt-141-vs-sildenafil",
        "path": "/compare/pt-141-vs-sildenafil",
        "title": "PT-141 vs Sildenafil (Viagra)"
      },
      {
        "slug": "melanotan-2-vs-pt-141",
        "path": "/compare/melanotan-2-vs-pt-141",
        "title": "Melanotan II vs PT-141"
      },
      {
        "slug": "ghk-cu-vs-retinol",
        "path": "/compare/ghk-cu-vs-retinol",
        "title": "GHK-Cu vs Retinol (Vitamin A)"
      },
      {
        "slug": "ghk-cu-vs-hyaluronic-acid",
        "path": "/compare/ghk-cu-vs-hyaluronic-acid",
        "title": "GHK-Cu vs Hyaluronic Acid"
      },
      {
        "slug": "ghk-cu-vs-minoxidil",
        "path": "/compare/ghk-cu-vs-minoxidil",
        "title": "GHK-Cu vs Minoxidil"
      },
      {
        "slug": "bpc-157-vs-minoxidil",
        "path": "/compare/bpc-157-vs-minoxidil",
        "title": "BPC-157 vs Minoxidil"
      },
      {
        "slug": "thymosin-alpha-1-vs-ll-37",
        "path": "/compare/thymosin-alpha-1-vs-ll-37",
        "title": "Thymosin Alpha-1 vs LL-37"
      },
      {
        "slug": "thymosin-alpha-1-vs-bpc-157",
        "path": "/compare/thymosin-alpha-1-vs-bpc-157",
        "title": "Thymosin Alpha-1 vs BPC-157"
      },
      {
        "slug": "ll-37-vs-bpc-157",
        "path": "/compare/ll-37-vs-bpc-157",
        "title": "LL-37 vs BPC-157"
      },
      {
        "slug": "snap-8-vs-argireline",
        "path": "/compare/snap-8-vs-argireline",
        "title": "SNAP-8 vs Argireline (Acetyl Hexapeptide-3)"
      },
      {
        "slug": "ghk-cu-vs-argireline",
        "path": "/compare/ghk-cu-vs-argireline",
        "title": "GHK-Cu vs Argireline"
      },
      {
        "slug": "semaglutide-vs-orforglipron",
        "path": "/compare/semaglutide-vs-orforglipron",
        "title": "Semaglutide vs Orforglipron"
      },
      {
        "slug": "aod-9604-vs-tirzepatide",
        "path": "/compare/aod-9604-vs-tirzepatide",
        "title": "AOD-9604 vs Tirzepatide"
      },
      {
        "slug": "oxytocin-vs-kisspeptin",
        "path": "/compare/oxytocin-vs-kisspeptin",
        "title": "Oxytocin vs Kisspeptin"
      },
      {
        "slug": "pt-141-vs-oxytocin",
        "path": "/compare/pt-141-vs-oxytocin",
        "title": "PT-141 vs Oxytocin"
      },
      {
        "slug": "kisspeptin-vs-pt-141",
        "path": "/compare/kisspeptin-vs-pt-141",
        "title": "Kisspeptin vs PT-141"
      },
      {
        "slug": "dsip-vs-selank",
        "path": "/compare/dsip-vs-selank",
        "title": "DSIP vs Selank"
      },
      {
        "slug": "dsip-vs-ipamorelin",
        "path": "/compare/dsip-vs-ipamorelin",
        "title": "DSIP vs Ipamorelin"
      },
      {
        "slug": "cerebrolysin-vs-dihexa",
        "path": "/compare/cerebrolysin-vs-dihexa",
        "title": "Cerebrolysin vs Dihexa"
      },
      {
        "slug": "cerebrolysin-vs-semax",
        "path": "/compare/cerebrolysin-vs-semax",
        "title": "Cerebrolysin vs Semax"
      },
      {
        "slug": "bpc-157-vs-glutamine",
        "path": "/compare/bpc-157-vs-glutamine",
        "title": "BPC-157 vs L-Glutamine"
      },
      {
        "slug": "bpc-157-vs-zinc-carnosine",
        "path": "/compare/bpc-157-vs-zinc-carnosine",
        "title": "BPC-157 vs Zinc Carnosine"
      },
      {
        "slug": "tb-500-vs-ipamorelin",
        "path": "/compare/tb-500-vs-ipamorelin",
        "title": "TB-500 vs Ipamorelin"
      },
      {
        "slug": "bpc-157-vs-nac",
        "path": "/compare/bpc-157-vs-nac",
        "title": "BPC-157 vs NAC (N-Acetyl Cysteine)"
      },
      {
        "slug": "ghk-cu-vs-epithalon",
        "path": "/compare/ghk-cu-vs-epithalon",
        "title": "GHK-Cu vs Epithalon"
      },
      {
        "slug": "mots-c-vs-humanin",
        "path": "/compare/mots-c-vs-humanin",
        "title": "MOTS-c vs Humanin"
      },
      {
        "slug": "ipamorelin-vs-mk-677",
        "path": "/compare/ipamorelin-vs-mk-677",
        "title": "Ipamorelin vs MK-677 (Ibutamoren)"
      },
      {
        "slug": "tesamorelin-vs-cjc-1295",
        "path": "/compare/tesamorelin-vs-cjc-1295",
        "title": "Tesamorelin vs CJC-1295"
      },
      {
        "slug": "aod-9604-vs-ipamorelin",
        "path": "/compare/aod-9604-vs-ipamorelin",
        "title": "AOD-9604 vs Ipamorelin"
      },
      {
        "slug": "aod-9604-vs-tesamorelin",
        "path": "/compare/aod-9604-vs-tesamorelin",
        "title": "AOD-9604 vs Tesamorelin"
      },
      {
        "slug": "kisspeptin-vs-hcg",
        "path": "/compare/kisspeptin-vs-hcg",
        "title": "Kisspeptin vs HCG"
      },
      {
        "slug": "dsip-vs-epithalon",
        "path": "/compare/dsip-vs-epithalon",
        "title": "DSIP vs Epithalon"
      },
      {
        "slug": "melanotan-2-vs-melanotan-1",
        "path": "/compare/melanotan-2-vs-melanotan-1",
        "title": "Melanotan-2 vs Melanotan-1"
      },
      {
        "slug": "snap-8-vs-matrixyl",
        "path": "/compare/snap-8-vs-matrixyl",
        "title": "SNAP-8 vs Matrixyl"
      },
      {
        "slug": "argireline-vs-matrixyl",
        "path": "/compare/argireline-vs-matrixyl",
        "title": "Argireline vs Matrixyl"
      },
      {
        "slug": "humanin-vs-ss-31",
        "path": "/compare/humanin-vs-ss-31",
        "title": "Humanin vs SS-31"
      },
      {
        "slug": "mots-c-vs-ss-31",
        "path": "/compare/mots-c-vs-ss-31",
        "title": "MOTS-c vs SS-31"
      },
      {
        "slug": "vip-vs-kpv",
        "path": "/compare/vip-vs-kpv",
        "title": "VIP vs KPV"
      },
      {
        "slug": "kpv-vs-bpc-157",
        "path": "/compare/kpv-vs-bpc-157",
        "title": "KPV vs BPC-157"
      },
      {
        "slug": "peg-mgf-vs-igf-1-lr3",
        "path": "/compare/peg-mgf-vs-igf-1-lr3",
        "title": "PEG-MGF vs IGF-1 LR3"
      },
      {
        "slug": "igf-1-lr3-vs-ipamorelin",
        "path": "/compare/igf-1-lr3-vs-ipamorelin",
        "title": "IGF-1 LR3 vs Ipamorelin"
      },
      {
        "slug": "bpc-157-vs-ara-290",
        "path": "/compare/bpc-157-vs-ara-290",
        "title": "BPC-157 vs ARA-290"
      },
      {
        "slug": "tb-500-vs-ara-290",
        "path": "/compare/tb-500-vs-ara-290",
        "title": "TB-500 vs ARA-290"
      },
      {
        "slug": "ghk-cu-vs-matrixyl",
        "path": "/compare/ghk-cu-vs-matrixyl",
        "title": "GHK-Cu vs Matrixyl"
      },
      {
        "slug": "epithalon-vs-foxo4-dri",
        "path": "/compare/epithalon-vs-foxo4-dri",
        "title": "Epithalon vs FOXO4-DRI"
      },
      {
        "slug": "selank-vs-cerebrolysin",
        "path": "/compare/selank-vs-cerebrolysin",
        "title": "Selank vs Cerebrolysin"
      },
      {
        "slug": "nad-plus-vs-ss-31",
        "path": "/compare/nad-plus-vs-ss-31",
        "title": "NAD+ vs SS-31"
      },
      {
        "slug": "methylene-blue-vs-dihexa",
        "path": "/compare/methylene-blue-vs-dihexa",
        "title": "Methylene Blue vs Dihexa"
      },
      {
        "slug": "glutathione-vs-nac",
        "path": "/compare/glutathione-vs-nac",
        "title": "Glutathione vs NAC"
      },
      {
        "slug": "rapamycin-vs-metformin",
        "path": "/compare/rapamycin-vs-metformin",
        "title": "Rapamycin vs Metformin"
      },
      {
        "slug": "low-dose-naltrexone-vs-kpv",
        "path": "/compare/low-dose-naltrexone-vs-kpv",
        "title": "Low-Dose Naltrexone vs KPV"
      },
      {
        "slug": "metformin-vs-berberine",
        "path": "/compare/metformin-vs-berberine",
        "title": "Metformin vs Berberine"
      },
      {
        "slug": "oxandrolone-vs-ipamorelin",
        "path": "/compare/oxandrolone-vs-ipamorelin",
        "title": "Oxandrolone vs Ipamorelin"
      },
      {
        "slug": "nandrolone-vs-tb-500",
        "path": "/compare/nandrolone-vs-tb-500",
        "title": "Nandrolone vs TB-500"
      },
      {
        "slug": "tesamorelin-vs-hgh",
        "path": "/compare/tesamorelin-vs-hgh",
        "title": "Tesamorelin vs HGH"
      },
      {
        "slug": "aod-9604-vs-hgh",
        "path": "/compare/aod-9604-vs-hgh",
        "title": "AOD-9604 vs HGH"
      },
      {
        "slug": "kisspeptin-vs-clomid",
        "path": "/compare/kisspeptin-vs-clomid",
        "title": "Kisspeptin vs Clomid"
      },
      {
        "slug": "dsip-vs-melatonin",
        "path": "/compare/dsip-vs-melatonin",
        "title": "DSIP vs Melatonin"
      },
      {
        "slug": "cerebrolysin-vs-cortexin",
        "path": "/compare/cerebrolysin-vs-cortexin",
        "title": "Cerebrolysin vs Cortexin"
      },
      {
        "slug": "dihexa-vs-noopept",
        "path": "/compare/dihexa-vs-noopept",
        "title": "Dihexa vs Noopept"
      },
      {
        "slug": "ll-37-vs-kpv",
        "path": "/compare/ll-37-vs-kpv",
        "title": "LL-37 vs KPV"
      },
      {
        "slug": "thymosin-alpha-1-vs-vip",
        "path": "/compare/thymosin-alpha-1-vs-vip",
        "title": "Thymosin Alpha-1 vs VIP"
      },
      {
        "slug": "snap-8-vs-botox",
        "path": "/compare/snap-8-vs-botox",
        "title": "SNAP-8 vs Botox"
      },
      {
        "slug": "argireline-vs-botox",
        "path": "/compare/argireline-vs-botox",
        "title": "Argireline vs Botox"
      },
      {
        "slug": "mots-c-vs-aod-9604",
        "path": "/compare/mots-c-vs-aod-9604",
        "title": "MOTS-c vs AOD-9604"
      },
      {
        "slug": "foxo4-dri-vs-dasatinib",
        "path": "/compare/foxo4-dri-vs-dasatinib",
        "title": "FOXO4-DRI vs Dasatinib"
      },
      {
        "slug": "ss-31-vs-methylene-blue",
        "path": "/compare/ss-31-vs-methylene-blue",
        "title": "SS-31 vs Methylene Blue"
      },
      {
        "slug": "tesamorelin-vs-mk-677",
        "path": "/compare/tesamorelin-vs-mk-677",
        "title": "Tesamorelin vs MK-677"
      },
      {
        "slug": "bpc-157-oral-vs-injectable",
        "path": "/compare/bpc-157-oral-vs-injectable",
        "title": "BPC-157 (Oral) vs BPC-157 (Injectable)"
      },
      {
        "slug": "tb-500-vs-tb-4",
        "path": "/compare/tb-500-vs-tb-4",
        "title": "TB-500 vs TB-4 (Thymosin Beta-4)"
      },
      {
        "slug": "cjc-1295-dac-vs-sermorelin",
        "path": "/compare/cjc-1295-dac-vs-sermorelin",
        "title": "CJC-1295 with DAC vs Sermorelin"
      },
      {
        "slug": "semaglutide-vs-metformin-weight-loss",
        "path": "/compare/semaglutide-vs-metformin-weight-loss",
        "title": "Semaglutide vs Metformin"
      },
      {
        "slug": "epithalon-vs-resveratrol",
        "path": "/compare/epithalon-vs-resveratrol",
        "title": "Epithalon vs Resveratrol"
      },
      {
        "slug": "ghk-cu-vs-vitamin-c",
        "path": "/compare/ghk-cu-vs-vitamin-c",
        "title": "GHK-Cu vs Vitamin C (L-Ascorbic Acid)"
      },
      {
        "slug": "selank-vs-ashwagandha",
        "path": "/compare/selank-vs-ashwagandha",
        "title": "Selank vs Ashwagandha"
      },
      {
        "slug": "semax-vs-modafinil",
        "path": "/compare/semax-vs-modafinil",
        "title": "Semax vs Modafinil"
      },
      {
        "slug": "pt-141-vs-maca",
        "path": "/compare/pt-141-vs-maca",
        "title": "PT-141 (Bremelanotide) vs Maca Root"
      },
      {
        "slug": "pt-141-vs-kisspeptin-libido",
        "path": "/compare/pt-141-vs-kisspeptin-libido",
        "title": "PT-141 (Bremelanotide) vs Kisspeptin"
      },
      {
        "slug": "ipamorelin-vs-tesamorelin-fat-loss",
        "path": "/compare/ipamorelin-vs-tesamorelin-fat-loss",
        "title": "Ipamorelin vs Tesamorelin"
      },
      {
        "slug": "semax-vs-selank-focus",
        "path": "/compare/semax-vs-selank-focus",
        "title": "Semax vs Selank"
      }
    ]
  },
  {
    "key": "stacks",
    "label": "Stacks",
    "path": "/stacks",
    "description": "Curated peptide protocols.",
    "entries": [
      {
        "slug": "recovery-stack",
        "path": "/stacks/recovery-stack",
        "title": "The Recovery Stack"
      },
      {
        "slug": "gh-optimization-stack",
        "path": "/stacks/gh-optimization-stack",
        "title": "The GH Optimization Stack"
      },
      {
        "slug": "anti-aging-stack",
        "path": "/stacks/anti-aging-stack",
        "title": "The Anti-Aging Stack"
      },
      {
        "slug": "metabolic-stack",
        "path": "/stacks/metabolic-stack",
        "title": "The Metabolic Stack"
      },
      {
        "slug": "cognitive-stack",
        "path": "/stacks/cognitive-stack",
        "title": "The Cognitive Stack"
      },
      {
        "slug": "wolverine-stack",
        "path": "/stacks/wolverine-stack",
        "title": "The Wolverine Stack"
      },
      {
        "slug": "fat-loss-stack",
        "path": "/stacks/fat-loss-stack",
        "title": "The Fat Loss Stack"
      },
      {
        "slug": "mitochondrial-stack",
        "path": "/stacks/mitochondrial-stack",
        "title": "The Mitochondrial Stack"
      },
      {
        "slug": "sleep-stack",
        "path": "/stacks/sleep-stack",
        "title": "The Sleep Stack"
      },
      {
        "slug": "gut-support-stack",
        "path": "/stacks/gut-support-stack",
        "title": "The Gut Support Stack"
      },
      {
        "slug": "brain-fog-stack",
        "path": "/stacks/brain-fog-stack",
        "title": "The Brain Fog Stack"
      },
      {
        "slug": "libido-stack",
        "path": "/stacks/libido-stack",
        "title": "The Libido Stack"
      },
      {
        "slug": "immune-defense-stack",
        "path": "/stacks/immune-defense-stack",
        "title": "The Immune Defense Stack"
      },
      {
        "slug": "nerve-repair-stack",
        "path": "/stacks/nerve-repair-stack",
        "title": "The Nerve Repair Stack"
      },
      {
        "slug": "skin-health-stack",
        "path": "/stacks/skin-health-stack",
        "title": "The Skin Health Stack"
      },
      {
        "slug": "muscle-growth-stack",
        "path": "/stacks/muscle-growth-stack",
        "title": "The Muscle Growth Stack"
      },
      {
        "slug": "endurance-stack",
        "path": "/stacks/endurance-stack",
        "title": "The Endurance Stack"
      },
      {
        "slug": "stress-resilience-stack",
        "path": "/stacks/stress-resilience-stack",
        "title": "The Stress Resilience Stack"
      },
      {
        "slug": "bodybuilding-stack",
        "path": "/stacks/bodybuilding-stack",
        "title": "The Bodybuilding Stack"
      },
      {
        "slug": "cardio-stack",
        "path": "/stacks/cardio-stack",
        "title": "The Cardiovascular Stack"
      },
      {
        "slug": "wound-healing-stack",
        "path": "/stacks/wound-healing-stack",
        "title": "The Wound Healing Stack"
      },
      {
        "slug": "immune-boosting-stack",
        "path": "/stacks/immune-boosting-stack",
        "title": "The Immune Boosting Stack"
      },
      {
        "slug": "neurogenesis-stack",
        "path": "/stacks/neurogenesis-stack",
        "title": "The Neurogenesis Stack"
      },
      {
        "slug": "cardio-support-stack",
        "path": "/stacks/cardio-support-stack",
        "title": "The Cardio Support Stack"
      },
      {
        "slug": "blood-sugar-stack",
        "path": "/stacks/blood-sugar-stack",
        "title": "The Blood Sugar Stack"
      },
      {
        "slug": "vision-support-stack",
        "path": "/stacks/vision-support-stack",
        "title": "The Vision Support Stack"
      },
      {
        "slug": "womens-fat-loss-stack",
        "path": "/stacks/womens-fat-loss-stack",
        "title": "The Women's Fat Loss Peptide Stack"
      },
      {
        "slug": "mens-vitality-stack",
        "path": "/stacks/mens-vitality-stack",
        "title": "The Men's Vitality Peptide Stack"
      },
      {
        "slug": "runners-recovery-stack",
        "path": "/stacks/runners-recovery-stack",
        "title": "The Runner's Recovery Stack"
      },
      {
        "slug": "bodybuilders-bulking-stack",
        "path": "/stacks/bodybuilders-bulking-stack",
        "title": "The Bodybuilder's Bulking Stack"
      },
      {
        "slug": "executives-focus-stack",
        "path": "/stacks/executives-focus-stack",
        "title": "The Executive's Focus Stack"
      },
      {
        "slug": "post-surgery-stack",
        "path": "/stacks/post-surgery-stack",
        "title": "The Post-Surgery Healing Stack"
      },
      {
        "slug": "concussion-protocol-stack",
        "path": "/stacks/concussion-protocol-stack",
        "title": "The Concussion Recovery Stack"
      },
      {
        "slug": "hair-regrowth-stack",
        "path": "/stacks/hair-regrowth-stack",
        "title": "The Ultimate Hair Regrowth Stack"
      },
      {
        "slug": "skin-glow-stack",
        "path": "/stacks/skin-glow-stack",
        "title": "The Skin Glow Peptide Stack"
      },
      {
        "slug": "deep-sleep-stack",
        "path": "/stacks/deep-sleep-stack",
        "title": "The Deep Sleep Peptide Stack"
      },
      {
        "slug": "injury-recovery-stack-advanced",
        "path": "/stacks/injury-recovery-stack-advanced",
        "title": "Advanced Injury Recovery Stack"
      },
      {
        "slug": "gh-secretagogue-complete-stack",
        "path": "/stacks/gh-secretagogue-complete-stack",
        "title": "Complete GH Secretagogue Stack"
      },
      {
        "slug": "cognitive-enhancement-stack",
        "path": "/stacks/cognitive-enhancement-stack",
        "title": "Cognitive Enhancement Stack"
      },
      {
        "slug": "gut-healing-restoration-stack",
        "path": "/stacks/gut-healing-restoration-stack",
        "title": "Gut Healing & Restoration Stack"
      },
      {
        "slug": "bodybuilding-prep-stack",
        "path": "/stacks/bodybuilding-prep-stack",
        "title": "Bodybuilding Contest Prep Stack"
      },
      {
        "slug": "longevity-comprehensive-stack",
        "path": "/stacks/longevity-comprehensive-stack",
        "title": "Comprehensive Longevity Stack"
      },
      {
        "slug": "sleep-recovery-optimization-stack",
        "path": "/stacks/sleep-recovery-optimization-stack",
        "title": "Sleep & Recovery Optimization Stack"
      },
      {
        "slug": "metabolic-health-weight-loss-stack",
        "path": "/stacks/metabolic-health-weight-loss-stack",
        "title": "Metabolic Health & Weight Loss Stack"
      },
      {
        "slug": "inflammation-pain-management-stack",
        "path": "/stacks/inflammation-pain-management-stack",
        "title": "Systemic Inflammation & Pain Management Stack"
      },
      {
        "slug": "skin-hair-regeneration-stack",
        "path": "/stacks/skin-hair-regeneration-stack",
        "title": "Skin, Hair & Connective Tissue Regeneration Stack"
      },
      {
        "slug": "hormone-axis-support-stack",
        "path": "/stacks/hormone-axis-support-stack",
        "title": "HPA Axis & Hormone Support Stack"
      },
      {
        "slug": "endurance-athlete-recovery-stack",
        "path": "/stacks/endurance-athlete-recovery-stack",
        "title": "Endurance Athlete Recovery Stack"
      },
      {
        "slug": "stress-resilience-adaptogen-stack",
        "path": "/stacks/stress-resilience-adaptogen-stack",
        "title": "Stress Resilience & Adaptogen Stack"
      },
      {
        "slug": "post-surgical-recovery-stack",
        "path": "/stacks/post-surgical-recovery-stack",
        "title": "Post-Surgical Recovery Stack"
      },
      {
        "slug": "immune-boost-recovery-stack",
        "path": "/stacks/immune-boost-recovery-stack",
        "title": "Immune Boost & Recovery Stack"
      },
      {
        "slug": "mitochondrial-energy-stack",
        "path": "/stacks/mitochondrial-energy-stack",
        "title": "Mitochondrial Energy & Vitality Stack"
      },
      {
        "slug": "connective-tissue-joint-stack",
        "path": "/stacks/connective-tissue-joint-stack",
        "title": "Connective Tissue & Joint Longevity Stack"
      },
      {
        "slug": "fat-loss-metabolic-ignition-stack",
        "path": "/stacks/fat-loss-metabolic-ignition-stack",
        "title": "Fat Loss Metabolic Ignition Stack"
      },
      {
        "slug": "recovery-stack-everyday-active",
        "path": "/stacks/recovery-stack-everyday-active",
        "title": "Everyday Active Recovery Stack"
      },
      {
        "slug": "libido-desire-optimization-stack",
        "path": "/stacks/libido-desire-optimization-stack",
        "title": "Libido & Desire Optimization Stack"
      }
    ]
  },
  {
    "key": "guides",
    "label": "Guides",
    "path": "/guides",
    "description": "How-to dosing and injection guides.",
    "entries": [
      {
        "slug": "how-to-reconstitute-peptides",
        "path": "/guides/how-to-reconstitute-peptides",
        "title": "How to Reconstitute Peptides with Bacteriostatic Water"
      },
      {
        "slug": "how-to-inject-peptides-subcutaneously",
        "path": "/guides/how-to-inject-peptides-subcutaneously",
        "title": "How to Inject Peptides Subcutaneously"
      },
      {
        "slug": "how-to-calculate-peptide-dosage",
        "path": "/guides/how-to-calculate-peptide-dosage",
        "title": "How to Calculate Peptide Dosage"
      },
      {
        "slug": "how-to-store-peptides",
        "path": "/guides/how-to-store-peptides",
        "title": "How to Store Peptides: Refrigeration and Shelf Life Guide"
      },
      {
        "slug": "how-to-use-bpc-157-for-gut-healing",
        "path": "/guides/how-to-use-bpc-157-for-gut-healing",
        "title": "How to Use BPC-157 for Gut Healing"
      },
      {
        "slug": "how-to-inject-subcutaneously",
        "path": "/guides/how-to-inject-subcutaneously",
        "title": "How to Inject Peptides Subcutaneously (SubQ) — Step-by-Step"
      },
      {
        "slug": "how-to-use-ipamorelin",
        "path": "/guides/how-to-use-ipamorelin",
        "title": "How to Use Ipamorelin: Dosing, Timing & Protocol Guide"
      },
      {
        "slug": "how-to-use-sermorelin",
        "path": "/guides/how-to-use-sermorelin",
        "title": "How to Use Sermorelin: Dosing, Timing & Protocol Guide"
      },
      {
        "slug": "how-to-use-tb-500",
        "path": "/guides/how-to-use-tb-500",
        "title": "How to Use TB-500: Dosing, Protocol & Injury Recovery Guide"
      },
      {
        "slug": "how-to-use-nad-plus",
        "path": "/guides/how-to-use-nad-plus",
        "title": "How to Use NAD+: Dosing, Routes & Anti-Aging Protocol"
      },
      {
        "slug": "how-to-use-ghk-cu",
        "path": "/guides/how-to-use-ghk-cu",
        "title": "How to Use GHK-Cu: Topical & Injectable Protocols"
      },
      {
        "slug": "how-to-use-epithalon",
        "path": "/guides/how-to-use-epithalon",
        "title": "How to Use Epithalon: Dosing & Longevity Protocol"
      },
      {
        "slug": "how-to-use-pt-141",
        "path": "/guides/how-to-use-pt-141",
        "title": "How to Use PT-141: Dosing & Sexual Health Protocol"
      },
      {
        "slug": "how-to-use-cjc-1295",
        "path": "/guides/how-to-use-cjc-1295",
        "title": "How to Use CJC-1295: DAC vs No-DAC, Dosing & Protocol"
      },
      {
        "slug": "how-to-use-semaglutide",
        "path": "/guides/how-to-use-semaglutide",
        "title": "How to Use Semaglutide: Dosing Titration & Weight Loss Protocol"
      },
      {
        "slug": "how-to-use-tirzepatide",
        "path": "/guides/how-to-use-tirzepatide",
        "title": "How to Use Tirzepatide: Dosing Titration & Weight Loss Protocol"
      },
      {
        "slug": "how-to-use-melanotan-2",
        "path": "/guides/how-to-use-melanotan-2",
        "title": "How to Use Melanotan 2: Dosing, Tanning Protocol & Side Effects"
      },
      {
        "slug": "how-to-use-thymosin-alpha-1",
        "path": "/guides/how-to-use-thymosin-alpha-1",
        "title": "How to Use Thymosin Alpha-1: Immune Support Protocol"
      },
      {
        "slug": "how-to-read-a-peptide-coa",
        "path": "/guides/how-to-read-a-peptide-coa",
        "title": "How to Read a Peptide Certificate of Analysis (COA)"
      },
      {
        "slug": "how-to-choose-a-peptide-vendor",
        "path": "/guides/how-to-choose-a-peptide-vendor",
        "title": "How to Choose a Reputable Peptide Vendor: 7 Key Criteria"
      },
      {
        "slug": "how-to-build-a-peptide-stack",
        "path": "/guides/how-to-build-a-peptide-stack",
        "title": "How to Build a Peptide Stack: Synergy, Timing & Safety"
      },
      {
        "slug": "how-to-cycle-peptides",
        "path": "/guides/how-to-cycle-peptides",
        "title": "How to Cycle Peptides: On and Off Periods Explained"
      },
      {
        "slug": "how-to-use-peptides-for-fat-loss",
        "path": "/guides/how-to-use-peptides-for-fat-loss",
        "title": "How to Use Peptides for Fat Loss: Best Protocols & Combinations"
      },
      {
        "slug": "how-to-use-peptides-for-muscle-growth",
        "path": "/guides/how-to-use-peptides-for-muscle-growth",
        "title": "How to Use Peptides for Muscle Growth: Best Protocols"
      },
      {
        "slug": "how-to-use-peptides-for-sleep",
        "path": "/guides/how-to-use-peptides-for-sleep",
        "title": "How to Use Peptides for Sleep: Best Protocols & Timing"
      },
      {
        "slug": "how-to-use-peptides-for-anti-aging",
        "path": "/guides/how-to-use-peptides-for-anti-aging",
        "title": "How to Use Peptides for Anti-Aging: Longevity Protocol Guide"
      },
      {
        "slug": "how-to-use-peptides-for-injury-recovery",
        "path": "/guides/how-to-use-peptides-for-injury-recovery",
        "title": "How to Use Peptides for Injury Recovery: Complete Protocol"
      },
      {
        "slug": "bpc-157-dosage-protocol",
        "path": "/guides/bpc-157-dosage-protocol",
        "title": "BPC-157 Dosage Protocol: Exactly How Much to Take"
      },
      {
        "slug": "subcutaneous-vs-intramuscular-injections",
        "path": "/guides/subcutaneous-vs-intramuscular-injections",
        "title": "Subcutaneous vs. Intramuscular Peptide Injections: Which is Better?"
      },
      {
        "slug": "oral-vs-injectable-peptides",
        "path": "/guides/oral-vs-injectable-peptides",
        "title": "Oral Peptides vs. Injections: Do Oral Peptides Actually Work?"
      },
      {
        "slug": "best-time-to-take-gh-peptides",
        "path": "/guides/best-time-to-take-gh-peptides",
        "title": "The Best Time of Day to Take Growth Hormone Peptides"
      },
      {
        "slug": "fasting-and-peptides",
        "path": "/guides/fasting-and-peptides",
        "title": "Fasting and Peptides: Should You Inject on an Empty Stomach?"
      },
      {
        "slug": "peptide-half-lives-dosing-frequency",
        "path": "/guides/peptide-half-lives-dosing-frequency",
        "title": "Peptide Half-Lives Explained: Dosing Frequency Guide"
      },
      {
        "slug": "how-to-use-peptides-for-immune-support",
        "path": "/guides/how-to-use-peptides-for-immune-support",
        "title": "How to Use Peptides for Immune Support: Protocol Guide"
      },
      {
        "slug": "how-to-use-peptides-for-metabolic-health",
        "path": "/guides/how-to-use-peptides-for-metabolic-health",
        "title": "How to Use Peptides for Metabolic Health: Protocol Guide"
      },
      {
        "slug": "how-to-use-tesamorelin",
        "path": "/guides/how-to-use-tesamorelin",
        "title": "How To Use Tesamorelin: Dosing, Timing & Protocol Guide"
      },
      {
        "slug": "how-to-use-aod-9604",
        "path": "/guides/how-to-use-aod-9604",
        "title": "How To Use AOD-9604: Dosing & Fat Loss Protocol Guide"
      },
      {
        "slug": "how-to-use-kisspeptin",
        "path": "/guides/how-to-use-kisspeptin",
        "title": "How To Use Kisspeptin: Dosing & Hormonal Protocol Guide"
      },
      {
        "slug": "how-to-use-dsip",
        "path": "/guides/how-to-use-dsip",
        "title": "How To Use DSIP: Dosing & Sleep Protocol Guide"
      },
      {
        "slug": "how-to-use-cerebrolysin",
        "path": "/guides/how-to-use-cerebrolysin",
        "title": "How To Use Cerebrolysin: Dosing & Neuroprotection Guide"
      },
      {
        "slug": "how-to-use-dihexa",
        "path": "/guides/how-to-use-dihexa",
        "title": "How To Use Dihexa: Dosing & Cognitive Protocol Guide"
      },
      {
        "slug": "how-to-use-ll-37",
        "path": "/guides/how-to-use-ll-37",
        "title": "How To Use LL-37: Dosing & Immune Support Guide"
      },
      {
        "slug": "how-to-use-melanotan-1",
        "path": "/guides/how-to-use-melanotan-1",
        "title": "How To Use Melanotan-1: Dosing & Tanning Protocol Guide"
      },
      {
        "slug": "how-to-use-snap-8",
        "path": "/guides/how-to-use-snap-8",
        "title": "How To Use SNAP-8: Topical Application Guide"
      },
      {
        "slug": "how-to-use-argireline",
        "path": "/guides/how-to-use-argireline",
        "title": "How To Use Argireline: Topical Application Guide"
      },
      {
        "slug": "how-to-use-humanin",
        "path": "/guides/how-to-use-humanin",
        "title": "How To Use Humanin: Dosing & Longevity Protocol Guide"
      },
      {
        "slug": "how-to-use-mots-c",
        "path": "/guides/how-to-use-mots-c",
        "title": "How To Use MOTS-C: Dosing & Metabolic Protocol Guide"
      },
      {
        "slug": "how-to-use-foxo4-dri",
        "path": "/guides/how-to-use-foxo4-dri",
        "title": "How To Use FOXO4-DRI: Dosing & Senolytic Protocol Guide"
      },
      {
        "slug": "how-to-use-ss-31",
        "path": "/guides/how-to-use-ss-31",
        "title": "How To Use SS-31: Dosing & Mitochondrial Protocol Guide"
      },
      {
        "slug": "how-to-use-vip",
        "path": "/guides/how-to-use-vip",
        "title": "How To Use VIP: Dosing & Gut-Lung Protocol Guide"
      },
      {
        "slug": "how-to-use-kpv",
        "path": "/guides/how-to-use-kpv",
        "title": "How To Use KPV: Dosing & Gut Health Protocol Guide"
      },
      {
        "slug": "how-to-use-ara-290",
        "path": "/guides/how-to-use-ara-290",
        "title": "How To Use ARA-290: Dosing & Nerve Repair Protocol Guide"
      },
      {
        "slug": "how-to-use-peg-mgf",
        "path": "/guides/how-to-use-peg-mgf",
        "title": "How To Use PEG-MGF: Dosing & Muscle Repair Guide"
      },
      {
        "slug": "how-to-use-igf-1-lr3",
        "path": "/guides/how-to-use-igf-1-lr3",
        "title": "How To Use IGF-1 LR3: Dosing & Anabolic Protocol Guide"
      },
      {
        "slug": "how-to-use-glutathione",
        "path": "/guides/how-to-use-glutathione",
        "title": "How To Use Glutathione: Dosing & Antioxidant Guide"
      },
      {
        "slug": "how-to-use-rapamycin",
        "path": "/guides/how-to-use-rapamycin",
        "title": "How To Use Rapamycin: Dosing & Longevity Protocol Guide"
      },
      {
        "slug": "how-to-use-ldn",
        "path": "/guides/how-to-use-ldn",
        "title": "How To Use LDN (Low-Dose Naltrexone): Protocol Guide"
      },
      {
        "slug": "how-to-use-metformin-for-longevity",
        "path": "/guides/how-to-use-metformin-for-longevity",
        "title": "How To Use Metformin For Longevity: Protocol Guide"
      },
      {
        "slug": "how-to-travel-with-peptides",
        "path": "/guides/how-to-travel-with-peptides",
        "title": "How To Travel With Peptides: TSA & Storage Guide"
      },
      {
        "slug": "how-to-dispose-of-syringes",
        "path": "/guides/how-to-dispose-of-syringes",
        "title": "How To Dispose Of Syringes Safely: Complete Guide"
      },
      {
        "slug": "how-to-manage-injection-site-reactions",
        "path": "/guides/how-to-manage-injection-site-reactions",
        "title": "How To Manage Injection Site Reactions: Complete Guide"
      },
      {
        "slug": "how-to-measure-peptide-progress",
        "path": "/guides/how-to-measure-peptide-progress",
        "title": "How To Measure Peptide Progress: Tracking & Markers"
      },
      {
        "slug": "how-to-transition-off-peptides",
        "path": "/guides/how-to-transition-off-peptides",
        "title": "How To Transition Off Peptides: Post-Cycle Guide"
      },
      {
        "slug": "how-to-stack-peptides-safely",
        "path": "/guides/how-to-stack-peptides-safely",
        "title": "How To Stack Peptides Safely: Compatibility Guide"
      },
      {
        "slug": "how-to-find-a-peptide-doctor",
        "path": "/guides/how-to-find-a-peptide-doctor",
        "title": "How To Find A Peptide Doctor: Telemedicine Guide"
      },
      {
        "slug": "how-to-store-reconstituted-peptides",
        "path": "/guides/how-to-store-reconstituted-peptides",
        "title": "How to Store Reconstituted Peptides: Refrigeration Guide"
      },
      {
        "slug": "how-to-travel-with-refrigerated-peptides",
        "path": "/guides/how-to-travel-with-refrigerated-peptides",
        "title": "How to Travel with Refrigerated Peptides: Travel Guide"
      },
      {
        "slug": "how-to-inject-intramuscularly",
        "path": "/guides/how-to-inject-intramuscularly",
        "title": "How to Inject Peptides Intramuscularly (IM): Guide"
      },
      {
        "slug": "how-to-calculate-mcg-to-mg",
        "path": "/guides/how-to-calculate-mcg-to-mg",
        "title": "How to Calculate mcg to mg for Peptides: Dosage Math Guide"
      },
      {
        "slug": "how-to-spot-fake-peptides",
        "path": "/guides/how-to-spot-fake-peptides",
        "title": "How to Spot Fake or Underdosed Peptides: Quality Guide"
      },
      {
        "slug": "how-to-use-peptides-for-pets",
        "path": "/guides/how-to-use-peptides-for-pets",
        "title": "How to Use Peptides for Pets (Dogs & Cats): Vet Guide"
      },
      {
        "slug": "how-to-talk-to-your-doctor-about-peptides",
        "path": "/guides/how-to-talk-to-your-doctor-about-peptides",
        "title": "How to Talk to Your Doctor About Peptides: Communication Guide"
      },
      {
        "slug": "how-to-use-peptides-for-crossfit-training",
        "path": "/guides/how-to-use-peptides-for-crossfit-training",
        "title": "How to Use Peptides for CrossFit Training: Recovery & Performance Guide"
      },
      {
        "slug": "how-to-use-peptides-for-bjj-martial-arts",
        "path": "/guides/how-to-use-peptides-for-bjj-martial-arts",
        "title": "How to Use Peptides for BJJ and Martial Arts: Recovery & Injury Prevention"
      },
      {
        "slug": "how-to-use-peptides-for-marathon-running",
        "path": "/guides/how-to-use-peptides-for-marathon-running",
        "title": "How to Use Peptides for Marathon Running: Endurance & Recovery Guide"
      },
      {
        "slug": "how-to-use-peptides-for-powerlifting",
        "path": "/guides/how-to-use-peptides-for-powerlifting",
        "title": "How to Use Peptides for Powerlifting: Strength, Joint Health & Recovery"
      },
      {
        "slug": "how-to-use-peptides-for-bodybuilding",
        "path": "/guides/how-to-use-peptides-for-bodybuilding",
        "title": "How to Use Peptides for Bodybuilding: Muscle Growth & Fat Loss Guide"
      },
      {
        "slug": "how-to-use-peptides-for-endurance-sports",
        "path": "/guides/how-to-use-peptides-for-endurance-sports",
        "title": "How to Use Peptides for Endurance Sports: VO2 Max, Recovery & Inflammation"
      },
      {
        "slug": "how-to-use-peptides-for-swimming-performance",
        "path": "/guides/how-to-use-peptides-for-swimming-performance",
        "title": "How to Use Peptides for Swimming: Shoulder Recovery & Training Support"
      },
      {
        "slug": "how-to-use-peptides-for-cycling-performance",
        "path": "/guides/how-to-use-peptides-for-cycling-performance",
        "title": "How to Use Peptides for Cycling: Endurance, Recovery & Knee Health"
      },
      {
        "slug": "how-to-use-peptides-for-strongman-training",
        "path": "/guides/how-to-use-peptides-for-strongman-training",
        "title": "How to Use Peptides for Strongman: Joint Health & Heavy Loading Recovery"
      },
      {
        "slug": "how-to-use-peptides-for-olympic-weightlifting",
        "path": "/guides/how-to-use-peptides-for-olympic-weightlifting",
        "title": "How to Use Peptides for Olympic Weightlifting: Snatch, Clean & Jerk Recovery"
      },
      {
        "slug": "how-to-use-peptides-for-wrestling",
        "path": "/guides/how-to-use-peptides-for-wrestling",
        "title": "How to Use Peptides for Wrestling: Weight Cuts, Recovery & Injury Prevention"
      },
      {
        "slug": "how-to-use-peptides-for-soccer-performance",
        "path": "/guides/how-to-use-peptides-for-soccer-performance",
        "title": "How to Use Peptides for Soccer: Hamstring Recovery & Match Preparation"
      },
      {
        "slug": "how-to-use-peptides-for-basketball-performance",
        "path": "/guides/how-to-use-peptides-for-basketball-performance",
        "title": "How to Use Peptides for Basketball: Jumping, Ankle Recovery & Court Performance"
      },
      {
        "slug": "how-to-use-peptides-for-rugby-performance",
        "path": "/guides/how-to-use-peptides-for-rugby-performance",
        "title": "How to Use Peptides for Rugby: Contact Recovery & Injury Rehabilitation"
      },
      {
        "slug": "how-to-use-peptides-for-tennis-performance",
        "path": "/guides/how-to-use-peptides-for-tennis-performance",
        "title": "How to Use Peptides for Tennis: Elbow Recovery & Tournament Preparation"
      },
      {
        "slug": "how-to-use-peptides-for-sprinting-speed",
        "path": "/guides/how-to-use-peptides-for-sprinting-speed",
        "title": "How to Use Peptides for Sprinting: Hamstring Health & Explosive Power"
      },
      {
        "slug": "how-to-use-peptides-for-triathlon-training",
        "path": "/guides/how-to-use-peptides-for-triathlon-training",
        "title": "How to Use Peptides for Triathlon: Multi-Sport Recovery & Endurance"
      },
      {
        "slug": "how-to-use-peptides-for-hybrid-athlete-training",
        "path": "/guides/how-to-use-peptides-for-hybrid-athlete-training",
        "title": "How to Use Peptides for Hybrid Athletes: Strength + Endurance Recovery"
      },
      {
        "slug": "how-to-combine-bpc-157-and-tb-500",
        "path": "/guides/how-to-combine-bpc-157-and-tb-500",
        "title": "How to Combine BPC-157 and TB-500: The Recovery Stack Protocol"
      },
      {
        "slug": "how-to-stack-gh-secretagogues-safely",
        "path": "/guides/how-to-stack-gh-secretagogues-safely",
        "title": "How to Stack GH Secretagogues Safely: Ipamorelin, CJC-1295 & Sermorelin"
      },
      {
        "slug": "how-to-minimize-peptide-injection-side-effects",
        "path": "/guides/how-to-minimize-peptide-injection-side-effects",
        "title": "How to Minimize Peptide Injection Side Effects: Pain, Lumps & Reactions"
      },
      {
        "slug": "how-to-rotate-injection-sites-properly",
        "path": "/guides/how-to-rotate-injection-sites-properly",
        "title": "How to Rotate Injection Sites Properly for Peptide Protocols"
      },
      {
        "slug": "how-to-dose-peptides-by-body-weight",
        "path": "/guides/how-to-dose-peptides-by-body-weight",
        "title": "How to Dose Peptides by Body Weight: Calculating mcg/kg Protocols"
      },
      {
        "slug": "how-to-choose-between-peptide-vendors",
        "path": "/guides/how-to-choose-between-peptide-vendors",
        "title": "How to Choose Between Peptide Vendors: Quality, Transparency & Value"
      },
      {
        "slug": "how-to-verify-peptide-purity-using-coas",
        "path": "/guides/how-to-verify-peptide-purity-using-coas",
        "title": "How to Verify Peptide Purity Using COAs: HPLC & Mass Spec Guide"
      },
      {
        "slug": "how-to-taper-off-peptides-after-a-cycle",
        "path": "/guides/how-to-taper-off-peptides-after-a-cycle",
        "title": "How to Taper Off Peptides After a Cycle: Transition & Recovery Guide"
      },
      {
        "slug": "how-to-maintain-results-post-peptide-cycle",
        "path": "/guides/how-to-maintain-results-post-peptide-cycle",
        "title": "How to Maintain Results After a Peptide Cycle: Long-Term Strategy"
      },
      {
        "slug": "how-to-combine-peptides-with-diet-and-exercise",
        "path": "/guides/how-to-combine-peptides-with-diet-and-exercise",
        "title": "How to Combine Peptides with Diet and Exercise for Maximum Results"
      },
      {
        "slug": "how-to-combine-peptides-with-trt",
        "path": "/guides/how-to-combine-peptides-with-trt",
        "title": "How to Combine Peptides with TRT: Synergy, Safety & Protocol Guide"
      },
      {
        "slug": "how-to-time-peptides-around-workouts",
        "path": "/guides/how-to-time-peptides-around-workouts",
        "title": "How to Time Peptides Around Workouts: Pre, Post & Rest Day Dosing"
      },
      {
        "slug": "how-to-identify-and-avoid-peptide-scams",
        "path": "/guides/how-to-identify-and-avoid-peptide-scams",
        "title": "How to Identify and Avoid Peptide Scams: Red Flags & Warning Signs"
      },
      {
        "slug": "how-to-spot-counterfeit-or-low-quality-peptides",
        "path": "/guides/how-to-spot-counterfeit-or-low-quality-peptides",
        "title": "How to Spot Counterfeit or Low-Quality Peptides: Visual & Physical Checks"
      },
      {
        "slug": "how-to-travel-with-peptides-internationally",
        "path": "/guides/how-to-travel-with-peptides-internationally",
        "title": "How to Travel with Peptides Internationally: Customs, Storage & Legal Guide"
      },
      {
        "slug": "how-to-safely-dispose-of-peptide-syringes",
        "path": "/guides/how-to-safely-dispose-of-peptide-syringes",
        "title": "How to Safely Dispose of Peptide Syringes: Sharps Guidelines"
      },
      {
        "slug": "how-to-read-and-understand-a-peptide-coa",
        "path": "/guides/how-to-read-and-understand-a-peptide-coa",
        "title": "How to Read and Understand a Peptide COA Report"
      }
    ]
  },
  {
    "key": "for",
    "label": "For",
    "path": "/for",
    "description": "Find peptides by condition or concern.",
    "entries": [
      {
        "slug": "brain-fog",
        "path": "/for/brain-fog",
        "title": "Brain Fog and Cognitive Fatigue"
      },
      {
        "slug": "leaky-gut",
        "path": "/for/leaky-gut",
        "title": "Leaky Gut (Intestinal Permeability)"
      },
      {
        "slug": "joint-pain",
        "path": "/for/joint-pain",
        "title": "Joint Pain and Osteoarthritis"
      },
      {
        "slug": "low-testosterone",
        "path": "/for/low-testosterone",
        "title": "Low Testosterone (Hypogonadism)"
      },
      {
        "slug": "anxiety",
        "path": "/for/anxiety",
        "title": "Anxiety and Stress"
      },
      {
        "slug": "poor-sleep",
        "path": "/for/poor-sleep",
        "title": "Poor Sleep and Insomnia"
      },
      {
        "slug": "tendinopathy",
        "path": "/for/tendinopathy",
        "title": "Tendinopathy (Tendon Injury)"
      },
      {
        "slug": "chronic-fatigue",
        "path": "/for/chronic-fatigue",
        "title": "Chronic Fatigue Syndrome (ME/CFS)"
      },
      {
        "slug": "depression",
        "path": "/for/depression",
        "title": "Depression (Major Depressive Disorder)"
      },
      {
        "slug": "osteoporosis",
        "path": "/for/osteoporosis",
        "title": "Osteoporosis"
      },
      {
        "slug": "erectile-dysfunction",
        "path": "/for/erectile-dysfunction",
        "title": "Erectile Dysfunction"
      },
      {
        "slug": "hair-loss",
        "path": "/for/hair-loss",
        "title": "Hair Loss (Androgenetic Alopecia)"
      },
      {
        "slug": "skin-aging",
        "path": "/for/skin-aging",
        "title": "Skin Aging (Photoaging & Intrinsic Aging)"
      },
      {
        "slug": "obesity",
        "path": "/for/obesity",
        "title": "Obesity"
      },
      {
        "slug": "type-2-diabetes",
        "path": "/for/type-2-diabetes",
        "title": "Type 2 Diabetes"
      },
      {
        "slug": "cognitive-decline",
        "path": "/for/cognitive-decline",
        "title": "Cognitive Decline and Mild Cognitive Impairment"
      },
      {
        "slug": "wound-healing",
        "path": "/for/wound-healing",
        "title": "Impaired Wound Healing"
      },
      {
        "slug": "autoimmune-disease",
        "path": "/for/autoimmune-disease",
        "title": "Autoimmune Diseases"
      },
      {
        "slug": "insomnia",
        "path": "/for/insomnia",
        "title": "Insomnia"
      },
      {
        "slug": "perimenopause",
        "path": "/for/perimenopause",
        "title": "Perimenopause and Menopause"
      },
      {
        "slug": "pcos",
        "path": "/for/pcos",
        "title": "PCOS"
      },
      {
        "slug": "lyme-disease",
        "path": "/for/lyme-disease",
        "title": "Lyme Disease and Chronic Illness Recovery"
      },
      {
        "slug": "adhd",
        "path": "/for/adhd",
        "title": "ADHD"
      },
      {
        "slug": "irritable-bowel-syndrome",
        "path": "/for/irritable-bowel-syndrome",
        "title": "Irritable Bowel Syndrome"
      },
      {
        "slug": "hashimotos-thyroiditis",
        "path": "/for/hashimotos-thyroiditis",
        "title": "Hashimoto's Thyroiditis"
      },
      {
        "slug": "women-over-40",
        "path": "/for/women-over-40",
        "title": "Women Over 40"
      },
      {
        "slug": "men-over-50",
        "path": "/for/men-over-50",
        "title": "Men Over 50"
      },
      {
        "slug": "osteoarthritis",
        "path": "/for/osteoarthritis",
        "title": "Osteoarthritis"
      },
      {
        "slug": "chronic-fatigue-syndrome",
        "path": "/for/chronic-fatigue-syndrome",
        "title": "Chronic Fatigue Syndrome"
      },
      {
        "slug": "arthritis",
        "path": "/for/arthritis",
        "title": "Arthritis"
      },
      {
        "slug": "diabetes",
        "path": "/for/diabetes",
        "title": "Diabetes"
      },
      {
        "slug": "alzheimers",
        "path": "/for/alzheimers",
        "title": "Alzheimer's Disease"
      },
      {
        "slug": "parkinsons",
        "path": "/for/parkinsons",
        "title": "Parkinson's Disease"
      },
      {
        "slug": "multiple-sclerosis",
        "path": "/for/multiple-sclerosis",
        "title": "Multiple Sclerosis"
      },
      {
        "slug": "fibromyalgia",
        "path": "/for/fibromyalgia",
        "title": "Fibromyalgia"
      },
      {
        "slug": "lyme-disease",
        "path": "/for/lyme-disease",
        "title": "Lyme Disease"
      },
      {
        "slug": "hashimotos",
        "path": "/for/hashimotos",
        "title": "Hashimoto's Thyroiditis"
      },
      {
        "slug": "graves-disease",
        "path": "/for/graves-disease",
        "title": "Graves' Disease"
      },
      {
        "slug": "lupus",
        "path": "/for/lupus",
        "title": "Systemic Lupus Erythematosus"
      },
      {
        "slug": "psoriasis",
        "path": "/for/psoriasis",
        "title": "Psoriasis"
      },
      {
        "slug": "eczema",
        "path": "/for/eczema",
        "title": "Eczema (Atopic Dermatitis)"
      },
      {
        "slug": "rosacea",
        "path": "/for/rosacea",
        "title": "Rosacea"
      },
      {
        "slug": "acne",
        "path": "/for/acne",
        "title": "Acne Vulgaris"
      },
      {
        "slug": "melasma",
        "path": "/for/melasma",
        "title": "Melasma"
      },
      {
        "slug": "alopecia-areata",
        "path": "/for/alopecia-areata",
        "title": "Alopecia Areata"
      },
      {
        "slug": "telogen-effluvium",
        "path": "/for/telogen-effluvium",
        "title": "Telogen Effluvium"
      },
      {
        "slug": "macular-degeneration",
        "path": "/for/macular-degeneration",
        "title": "Age-Related Macular Degeneration"
      },
      {
        "slug": "glaucoma",
        "path": "/for/glaucoma",
        "title": "Glaucoma"
      },
      {
        "slug": "cataracts",
        "path": "/for/cataracts",
        "title": "Cataracts"
      },
      {
        "slug": "tinnitus",
        "path": "/for/tinnitus",
        "title": "Tinnitus"
      },
      {
        "slug": "vertigo",
        "path": "/for/vertigo",
        "title": "Vertigo"
      },
      {
        "slug": "neuropathy",
        "path": "/for/neuropathy",
        "title": "Peripheral Neuropathy"
      },
      {
        "slug": "sciatica",
        "path": "/for/sciatica",
        "title": "Sciatica"
      },
      {
        "slug": "carpal-tunnel",
        "path": "/for/carpal-tunnel",
        "title": "Carpal Tunnel Syndrome"
      },
      {
        "slug": "plantar-fasciitis",
        "path": "/for/plantar-fasciitis",
        "title": "Plantar Fasciitis"
      },
      {
        "slug": "tennis-elbow",
        "path": "/for/tennis-elbow",
        "title": "Tennis Elbow (Lateral Epicondylitis)"
      },
      {
        "slug": "golfers-elbow",
        "path": "/for/golfers-elbow",
        "title": "Golfer's Elbow (Medial Epicondylitis)"
      },
      {
        "slug": "rotator-cuff-tear",
        "path": "/for/rotator-cuff-tear",
        "title": "Rotator Cuff Tear"
      },
      {
        "slug": "achilles-tendinopathy",
        "path": "/for/achilles-tendinopathy",
        "title": "Achilles Tendinopathy"
      },
      {
        "slug": "patellar-tendinopathy",
        "path": "/for/patellar-tendinopathy",
        "title": "Patellar Tendinopathy"
      },
      {
        "slug": "meniscus-tear",
        "path": "/for/meniscus-tear",
        "title": "Meniscus Tear"
      },
      {
        "slug": "acl-tear",
        "path": "/for/acl-tear",
        "title": "ACL Tear"
      },
      {
        "slug": "mcl-tear",
        "path": "/for/mcl-tear",
        "title": "MCL Tear"
      },
      {
        "slug": "spinal-disc-herniation",
        "path": "/for/spinal-disc-herniation",
        "title": "Spinal Disc Herniation"
      },
      {
        "slug": "degenerative-disc-disease",
        "path": "/for/degenerative-disc-disease",
        "title": "Degenerative Disc Disease"
      },
      {
        "slug": "osteopenia",
        "path": "/for/osteopenia",
        "title": "Osteopenia"
      },
      {
        "slug": "sarcopenia",
        "path": "/for/sarcopenia",
        "title": "Sarcopenia"
      },
      {
        "slug": "cachexia",
        "path": "/for/cachexia",
        "title": "Cachexia"
      },
      {
        "slug": "anorexia",
        "path": "/for/anorexia",
        "title": "Anorexia Nervosa"
      },
      {
        "slug": "bulimia",
        "path": "/for/bulimia",
        "title": "Bulimia Nervosa"
      },
      {
        "slug": "binge-eating-disorder",
        "path": "/for/binge-eating-disorder",
        "title": "Binge Eating Disorder"
      },
      {
        "slug": "adhd",
        "path": "/for/adhd",
        "title": "Attention Deficit Hyperactivity Disorder (ADHD)"
      },
      {
        "slug": "add",
        "path": "/for/add",
        "title": "Attention Deficit Disorder (ADD)"
      },
      {
        "slug": "autism",
        "path": "/for/autism",
        "title": "Autism Spectrum Disorder"
      },
      {
        "slug": "bipolar-disorder",
        "path": "/for/bipolar-disorder",
        "title": "Bipolar Disorder"
      },
      {
        "slug": "schizophrenia",
        "path": "/for/schizophrenia",
        "title": "Schizophrenia"
      },
      {
        "slug": "ocd",
        "path": "/for/ocd",
        "title": "Obsessive-Compulsive Disorder (OCD)"
      },
      {
        "slug": "tourettes",
        "path": "/for/tourettes",
        "title": "Tourette Syndrome"
      },
      {
        "slug": "post-covid-fatigue",
        "path": "/for/post-covid-fatigue",
        "title": "Post-COVID Fatigue Syndrome"
      },
      {
        "slug": "long-covid-brain-fog",
        "path": "/for/long-covid-brain-fog",
        "title": "Long COVID Brain Fog"
      },
      {
        "slug": "vaccine-injury-recovery",
        "path": "/for/vaccine-injury-recovery",
        "title": "Vaccine Injury Recovery"
      },
      {
        "slug": "mold-toxicity",
        "path": "/for/mold-toxicity",
        "title": "Mold Toxicity (Mycotoxin Illness)"
      },
      {
        "slug": "heavy-metal-toxicity",
        "path": "/for/heavy-metal-toxicity",
        "title": "Heavy Metal Toxicity"
      },
      {
        "slug": "canine-arthritis",
        "path": "/for/canine-arthritis",
        "title": "Canine Arthritis (Osteoarthritis in Dogs)"
      },
      {
        "slug": "feline-kidney-disease",
        "path": "/for/feline-kidney-disease",
        "title": "Feline Chronic Kidney Disease"
      },
      {
        "slug": "crossfit-performance-and-recovery",
        "path": "/for/crossfit-performance-and-recovery",
        "title": "CrossFit Performance & Recovery"
      },
      {
        "slug": "running-performance-and-recovery",
        "path": "/for/running-performance-and-recovery",
        "title": "Running Performance & Recovery"
      },
      {
        "slug": "weightlifting-performance-and-recovery",
        "path": "/for/weightlifting-performance-and-recovery",
        "title": "Weightlifting Performance & Recovery"
      },
      {
        "slug": "bjj-martial-arts-recovery",
        "path": "/for/bjj-martial-arts-recovery",
        "title": "BJJ & Martial Arts Recovery"
      },
      {
        "slug": "swimming-performance-and-recovery",
        "path": "/for/swimming-performance-and-recovery",
        "title": "Swimming Performance & Recovery"
      },
      {
        "slug": "cycling-performance-and-recovery",
        "path": "/for/cycling-performance-and-recovery",
        "title": "Cycling Performance & Recovery"
      },
      {
        "slug": "soccer-performance-and-recovery",
        "path": "/for/soccer-performance-and-recovery",
        "title": "Soccer Performance & Recovery"
      },
      {
        "slug": "rugby-performance-and-recovery",
        "path": "/for/rugby-performance-and-recovery",
        "title": "Rugby Performance & Recovery"
      },
      {
        "slug": "metabolic-syndrome",
        "path": "/for/metabolic-syndrome",
        "title": "Metabolic Syndrome"
      },
      {
        "slug": "non-alcoholic-fatty-liver-disease",
        "path": "/for/non-alcoholic-fatty-liver-disease",
        "title": "Non-Alcoholic Fatty Liver Disease (NAFLD)"
      },
      {
        "slug": "pre-diabetes",
        "path": "/for/pre-diabetes",
        "title": "Pre-Diabetes"
      },
      {
        "slug": "insulin-resistance",
        "path": "/for/insulin-resistance",
        "title": "Insulin Resistance"
      },
      {
        "slug": "chronic-inflammation-systemic",
        "path": "/for/chronic-inflammation-systemic",
        "title": "Chronic Systemic Inflammation"
      },
      {
        "slug": "dyslipidemia-high-cholesterol",
        "path": "/for/dyslipidemia-high-cholesterol",
        "title": "Dyslipidemia (High Cholesterol)"
      },
      {
        "slug": "hypertension-high-blood-pressure",
        "path": "/for/hypertension-high-blood-pressure",
        "title": "Hypertension (High Blood Pressure)"
      },
      {
        "slug": "adult-onset-obesity",
        "path": "/for/adult-onset-obesity",
        "title": "Adult-Onset Obesity"
      },
      {
        "slug": "sibo-small-intestinal-bacterial-overgrowth",
        "path": "/for/sibo-small-intestinal-bacterial-overgrowth",
        "title": "SIBO (Small Intestinal Bacterial Overgrowth)"
      },
      {
        "slug": "candida-overgrowth",
        "path": "/for/candida-overgrowth",
        "title": "Candida Overgrowth"
      },
      {
        "slug": "intestinal-dysbiosis",
        "path": "/for/intestinal-dysbiosis",
        "title": "Intestinal Dysbiosis"
      },
      {
        "slug": "histamine-intolerance-mcas",
        "path": "/for/histamine-intolerance-mcas",
        "title": "Histamine Intolerance & MCAS"
      },
      {
        "slug": "adrenal-fatigue-hpa-axis-dysfunction",
        "path": "/for/adrenal-fatigue-hpa-axis-dysfunction",
        "title": "Adrenal Fatigue & HPA Axis Dysfunction"
      },
      {
        "slug": "chronic-stress-burnout",
        "path": "/for/chronic-stress-burnout",
        "title": "Chronic Stress & Burnout"
      },
      {
        "slug": "post-partum-recovery-support",
        "path": "/for/post-partum-recovery-support",
        "title": "Post-Partum Recovery Support"
      },
      {
        "slug": "menopausal-weight-gain",
        "path": "/for/menopausal-weight-gain",
        "title": "Menopausal Weight Gain"
      },
      {
        "slug": "andropause-low-testosterone-age-related",
        "path": "/for/andropause-low-testosterone-age-related",
        "title": "Andropause & Age-Related Low Testosterone"
      }
    ]
  },
  {
    "key": "reviews",
    "label": "Reviews",
    "path": "/reviews",
    "description": "Independent peptide reviews.",
    "entries": [
      {
        "slug": "bpc-157-review",
        "path": "/reviews/bpc-157-review",
        "title": "BPC-157 Review: Is It Worth It? An Independent Assessment"
      },
      {
        "slug": "ipamorelin-cjc-1295-review",
        "path": "/reviews/ipamorelin-cjc-1295-review",
        "title": "Ipamorelin / CJC-1295 Review: The Most Popular GH Stack Assessed"
      },
      {
        "slug": "semaglutide-review",
        "path": "/reviews/semaglutide-review",
        "title": "Semaglutide Review: Ozempic and Wegovy Assessed Independently"
      },
      {
        "slug": "tb-500-review",
        "path": "/reviews/tb-500-review",
        "title": "TB-500 Review: Is Thymosin Beta-4 Worth It? Independent Assessment"
      },
      {
        "slug": "ghk-cu-review",
        "path": "/reviews/ghk-cu-review",
        "title": "GHK-Cu Review: Is the Copper Peptide Worth It? Independent Assessment"
      },
      {
        "slug": "ipamorelin-review",
        "path": "/reviews/ipamorelin-review",
        "title": "Ipamorelin Review: GH Release, Body Composition & Side Effects"
      },
      {
        "slug": "tirzepatide-review",
        "path": "/reviews/tirzepatide-review",
        "title": "Tirzepatide Review: Weight Loss Results, Side Effects & Comparison with Semaglutide"
      },
      {
        "slug": "sermorelin-review",
        "path": "/reviews/sermorelin-review",
        "title": "Sermorelin Review: Anti-Aging Results, Side Effects & Comparison with HGH"
      },
      {
        "slug": "nad-plus-review",
        "path": "/reviews/nad-plus-review",
        "title": "NAD+ Review: Anti-Aging Evidence, Energy Results & Best Forms"
      },
      {
        "slug": "epithalon-review",
        "path": "/reviews/epithalon-review",
        "title": "Epithalon Review: Telomere Lengthening Evidence, Results & Protocol"
      },
      {
        "slug": "pt-141-review",
        "path": "/reviews/pt-141-review",
        "title": "PT-141 Review: Sexual Health Results, Side Effects & Dosing"
      },
      {
        "slug": "cjc-1295-review",
        "path": "/reviews/cjc-1295-review",
        "title": "CJC-1295 Review: Body Composition Results, DAC vs No-DAC & Side Effects"
      },
      {
        "slug": "thymosin-alpha-1-review",
        "path": "/reviews/thymosin-alpha-1-review",
        "title": "Thymosin Alpha-1 Review: Immune Support Evidence, Results & Side Effects"
      },
      {
        "slug": "melanotan-2-review",
        "path": "/reviews/melanotan-2-review",
        "title": "Melanotan 2 Review: Tanning Results, Side Effects & Safety Concerns"
      },
      {
        "slug": "selank-review",
        "path": "/reviews/selank-review",
        "title": "Selank Review: Anxiety Relief Results, Side Effects & Evidence"
      },
      {
        "slug": "semax-review",
        "path": "/reviews/semax-review",
        "title": "Semax Review: Cognitive Enhancement Evidence, Results & Side Effects"
      },
      {
        "slug": "tesamorelin-review",
        "path": "/reviews/tesamorelin-review",
        "title": "Tesamorelin Review: Growth Hormone Releasing Peptide for Fat Loss"
      },
      {
        "slug": "aod-9604-review",
        "path": "/reviews/aod-9604-review",
        "title": "AOD-9604 Review: Fat Loss Peptide Fragment Analysis"
      },
      {
        "slug": "kisspeptin-review",
        "path": "/reviews/kisspeptin-review",
        "title": "Kisspeptin Review: The Fertility and Libido Neuropeptide"
      },
      {
        "slug": "dsip-review",
        "path": "/reviews/dsip-review",
        "title": "DSIP Review: Delta Sleep-Inducing Peptide for Deep Rest"
      },
      {
        "slug": "cerebrolysin-review",
        "path": "/reviews/cerebrolysin-review",
        "title": "Cerebrolysin Review: Neurotropic Peptide for Brain Health"
      },
      {
        "slug": "dihexa-review",
        "path": "/reviews/dihexa-review",
        "title": "Dihexa Review: The Angiogenic Cognitive Enhancer"
      },
      {
        "slug": "ll-37-review",
        "path": "/reviews/ll-37-review",
        "title": "LL-37 Review: The Antimicrobial Peptide for Immune Support"
      },
      {
        "slug": "snap-8-review",
        "path": "/reviews/snap-8-review",
        "title": "SNAP-8 Review: Advanced Neurotransmitter-Inhibiting Peptide"
      },
      {
        "slug": "argireline-review",
        "path": "/reviews/argireline-review",
        "title": "Argireline Review: The Acetyl Hexapeptide Anti-Aging Powerhouse"
      },
      {
        "slug": "humanin-review",
        "path": "/reviews/humanin-review",
        "title": "Humanin Review: The Mitochondrial-Derived Longevity Peptide"
      },
      {
        "slug": "motsc-review",
        "path": "/reviews/motsc-review",
        "title": "MOTS-C Review: Mitochondrial Peptide for Metabolic Health"
      },
      {
        "slug": "foxo4-dri-review",
        "path": "/reviews/foxo4-dri-review",
        "title": "FOXO4-DRI Review: The Senolytic Anti-Aging Peptide"
      },
      {
        "slug": "ss-31-review",
        "path": "/reviews/ss-31-review",
        "title": "SS-31 (Elamipretide) Review: Mitochondrial Targeted Peptide"
      },
      {
        "slug": "vip-review",
        "path": "/reviews/vip-review",
        "title": "VIP Review: Vasoactive Intestinal Peptide for Gut and Immune Health"
      },
      {
        "slug": "kpv-review",
        "path": "/reviews/kpv-review",
        "title": "KPV Review: The Tripeptide for Gut and Immune Health"
      },
      {
        "slug": "ara-290-review",
        "path": "/reviews/ara-290-review",
        "title": "ARA-290 Review: The Erythropoietin-Derived Neuroprotective Peptide"
      },
      {
        "slug": "peg-mgf-review",
        "path": "/reviews/peg-mgf-review",
        "title": "PEG-MGF Review: Mechano Growth Factor for Muscle Recovery"
      },
      {
        "slug": "igf-1-lr3-review",
        "path": "/reviews/igf-1-lr3-review",
        "title": "IGF-1 LR3 Review: Long R3 Insulin-Like Growth Factor-1"
      },
      {
        "slug": "glutathione-review",
        "path": "/reviews/glutathione-review",
        "title": "Glutathione Review: The Master Antioxidant Peptide"
      },
      {
        "slug": "rapamycin-review",
        "path": "/reviews/rapamycin-review",
        "title": "Rapamycin Review: The mTOR Inhibitor Longevity Drug"
      },
      {
        "slug": "ldn-review",
        "path": "/reviews/ldn-review",
        "title": "Low-Dose Naltrexone (LDN) Review: Immune Modulation Therapy"
      },
      {
        "slug": "metformin-review",
        "path": "/reviews/metformin-review",
        "title": "Metformin Review: The Diabetes Drug Repurposed for Longevity"
      },
      {
        "slug": "oxandrolone-review",
        "path": "/reviews/oxandrolone-review",
        "title": "Oxandrolone (Anavar) Review: Mild Anabolic for Recovery"
      },
      {
        "slug": "nandrolone-review",
        "path": "/reviews/nandrolone-review",
        "title": "Nandrolone (Deca-Durabolin) Review: Anabolic for Joint Recovery"
      },
      {
        "slug": "hcg-review",
        "path": "/reviews/hcg-review",
        "title": "HCG Review: Human Chorionic Gonadotropin for Hormonal Health"
      },
      {
        "slug": "clomid-review",
        "path": "/reviews/clomid-review",
        "title": "Clomid (Clomiphene Citrate) Review: SERM for Hormonal Balance"
      },
      {
        "slug": "enclomiphene-review",
        "path": "/reviews/enclomiphene-review",
        "title": "Enclomiphene Review: The Purified SERM for Testosterone"
      },
      {
        "slug": "tamoxifen-review",
        "path": "/reviews/tamoxifen-review",
        "title": "Tamoxifen (Nolvadex) Review: SERM for Estrogen Management"
      },
      {
        "slug": "anastrozole-review",
        "path": "/reviews/anastrozole-review",
        "title": "Anastrozole (Arimidex) Review: Aromatase Inhibitor for Estrogen"
      },
      {
        "slug": "letrozole-review",
        "path": "/reviews/letrozole-review",
        "title": "Letrozole (Femara) Review: Potent Aromatase Inhibitor"
      },
      {
        "slug": "exemestane-review",
        "path": "/reviews/exemestane-review",
        "title": "Exemestane (Aromasin) Review: Irreversible Aromatase Inhibitor"
      },
      {
        "slug": "finasteride-review",
        "path": "/reviews/finasteride-review",
        "title": "Finasteride (Propecia) Review: DHT Blocker for Hair Loss"
      },
      {
        "slug": "dutasteride-review",
        "path": "/reviews/dutasteride-review",
        "title": "Dutasteride (Avodart) Review: Dual 5-AR Inhibitor for Hair"
      },
      {
        "slug": "minoxidil-review",
        "path": "/reviews/minoxidil-review",
        "title": "Minoxidil (Rogaine) Review: Topical Vasodilator for Hair Growth"
      },
      {
        "slug": "ru58841-review",
        "path": "/reviews/ru58841-review",
        "title": "RU58841 Review: Topical Anti-Androgen for Hair Preservation"
      },
      {
        "slug": "ketoconazole-review",
        "path": "/reviews/ketoconazole-review",
        "title": "Ketoconazole Shampoo Review: Anti-DHT Hair Loss Treatment"
      },
      {
        "slug": "tretinoin-review",
        "path": "/reviews/tretinoin-review",
        "title": "Tretinoin (Retin-A) Review: Gold Standard Topical Retinoid"
      },
      {
        "slug": "isotretinoin-review",
        "path": "/reviews/isotretinoin-review",
        "title": "Isotretinoin (Accutane) Review: The Acne Cure"
      },
      {
        "slug": "tazarotene-review",
        "path": "/reviews/tazarotene-review",
        "title": "Tazarotene (Tazorac) Review: Third-Generation Retinoid"
      },
      {
        "slug": "azelaic-acid-review",
        "path": "/reviews/azelaic-acid-review",
        "title": "Azelaic Acid Review: Multi-Functional Skincare Ingredient"
      },
      {
        "slug": "salicylic-acid-review",
        "path": "/reviews/salicylic-acid-review",
        "title": "Salicylic Acid Review: Beta Hydroxy Acid for Acne and Exfoliation"
      },
      {
        "slug": "niacinamide-review",
        "path": "/reviews/niacinamide-review",
        "title": "Niacinamide (Vitamin B3) Review: The Universal Skincare Ingredient"
      },
      {
        "slug": "vitamin-c-serum-review",
        "path": "/reviews/vitamin-c-serum-review",
        "title": "Vitamin C Serum (L-Ascorbic Acid) Review: Antioxidant Powerhouse"
      },
      {
        "slug": "hyaluronic-acid-review",
        "path": "/reviews/hyaluronic-acid-review",
        "title": "Hyaluronic Acid Review: The Ultimate Hydrating Molecule"
      },
      {
        "slug": "ceramides-review",
        "path": "/reviews/ceramides-review",
        "title": "Ceramides Review: Essential Lipids for Skin Barrier Health"
      },
      {
        "slug": "peptides-serum-review",
        "path": "/reviews/peptides-serum-review",
        "title": "Peptides Serum Review: Collagen Signaling for Anti-Aging"
      },
      {
        "slug": "growth-factors-review",
        "path": "/reviews/growth-factors-review",
        "title": "Growth Factors Review: Advanced Skincare Biotech"
      },
      {
        "slug": "stem-cells-review",
        "path": "/reviews/stem-cells-review",
        "title": "Stem Cells in Skincare Review: Fact vs Hype"
      },
      {
        "slug": "exosomes-review",
        "path": "/reviews/exosomes-review",
        "title": "Exosomes Review: Next-Generation Regenerative Skincare"
      },
      {
        "slug": "bpc-157-capsules-review",
        "path": "/reviews/bpc-157-capsules-review",
        "title": "BPC-157 Capsules Review: Oral Body Protective Compound"
      },
      {
        "slug": "tb-500-nasal-spray-review",
        "path": "/reviews/tb-500-nasal-spray-review",
        "title": "TB-500 Nasal Spray Review: Intranasal Thymosin Beta-4"
      },
      {
        "slug": "semaglutide-drops-review",
        "path": "/reviews/semaglutide-drops-review",
        "title": "Semaglutide Sublingual Drops Review: Oral GLP-1 Delivery"
      },
      {
        "slug": "pt-141-nasal-spray-review",
        "path": "/reviews/pt-141-nasal-spray-review",
        "title": "PT-141 Nasal Spray Review: Bremelanotide for Sexual Health"
      },
      {
        "slug": "ghk-cu-foam-review",
        "path": "/reviews/ghk-cu-foam-review",
        "title": "GHK-Cu Hair Foam Review: Copper Peptide for Hair Growth"
      },
      {
        "slug": "peptide-therapy-cost-review",
        "path": "/reviews/peptide-therapy-cost-review",
        "title": "Peptide Therapy Cost Review: Pricing Guide and Value Analysis"
      },
      {
        "slug": "bpc-157-tb-500-stack-review",
        "path": "/reviews/bpc-157-tb-500-stack-review",
        "title": "BPC-157 + TB-500 Stack Review: Does the Recovery Stack Work?"
      },
      {
        "slug": "semaglutide-vs-tirzepatide-review",
        "path": "/reviews/semaglutide-vs-tirzepatide-review",
        "title": "Semaglutide vs Tirzepatide Review: Which GLP-1 Is Better for Weight Loss?"
      },
      {
        "slug": "selank-vs-benzodiazepines-review",
        "path": "/reviews/selank-vs-benzodiazepines-review",
        "title": "Selank vs Benzodiazepines Review: Anxiety Treatment Without Sedation"
      },
      {
        "slug": "ghk-cu-injectable-vs-topical-review",
        "path": "/reviews/ghk-cu-injectable-vs-topical-review",
        "title": "GHK-Cu Injectable vs Topical Review: Which Form Is Better for Skin?"
      },
      {
        "slug": "ipamorelin-cjc-1295-stack-review",
        "path": "/reviews/ipamorelin-cjc-1295-stack-review",
        "title": "Ipamorelin + CJC-1295 Stack Review: The Gold Standard GH Protocol"
      }
    ]
  }
] satisfies PseoSection[];
