import fs from "node:fs/promises";
import path from "node:path";
import { generatedBlogPostContent } from "../shared/blog-content.generated";
import { legacyBlogPosts } from "../shared/blog-legacy";
import { pseoContentRecords } from "../shared/pseoContent";
import {
  comparisonPages,
  forConditionPages,
  goalPages,
  guidePages,
  peptidePages,
  reviewPages,
  stackPages,
} from "../shared/pseoData";

const projectRoot = path.resolve(import.meta.dirname, "..");
const dataRoot = path.join(projectRoot, "client", "public", "data");
const blogRoot = path.join(dataRoot, "blog");
const pseoRoot = path.join(dataRoot, "pseo");
const pseoIndexPath = path.join(projectRoot, "shared", "pseoIndex.generated.ts");

async function ensureCleanDir(dirPath: string) {
  await fs.rm(dirPath, { recursive: true, force: true });
  await fs.mkdir(dirPath, { recursive: true });
}

async function writeJsonFile(filePath: string, value: unknown) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, JSON.stringify(value), "utf8");
}

async function exportBlogContent() {
  await ensureCleanDir(blogRoot);

  const generatedPosts = Object.values(generatedBlogPostContent);
  const allPosts = [...generatedPosts, ...legacyBlogPosts];

  await Promise.all(
    allPosts.map((post) =>
      writeJsonFile(path.join(blogRoot, `${post.slug}.json`), post)
    )
  );

  console.log(`[content] exported ${allPosts.length} blog article payloads`);
}

async function exportPseoContent() {
  await ensureCleanDir(pseoRoot);

  const entries = Object.values(pseoContentRecords);

  await Promise.all(
    entries.map((record) => {
      const relativePath = record.path.replace(/^\//, "");
      return writeJsonFile(path.join(pseoRoot, `${relativePath}.json`), record);
    })
  );

  console.log(`[content] exported ${entries.length} pseo content payloads`);
}

function toPseoIndex() {
  return [
    {
      key: "peptides",
      label: "Peptide Library",
      path: "/peptides",
      description: "Profiles for 12+ research peptides.",
      entries: peptidePages.map((page) => ({
        slug: page.slug,
        path: `/peptides/${page.slug}`,
        title: page.name,
      })),
    },
    {
      key: "goals",
      label: "Goals",
      path: "/goals",
      description: "Find peptides by health goal.",
      entries: goalPages.map((page) => ({
        slug: page.slug,
        path: `/goals/${page.slug}`,
        title: page.title,
      })),
    },
    {
      key: "compare",
      label: "Compare",
      path: "/compare",
      description: "Head-to-head peptide comparisons.",
      entries: comparisonPages.map((page) => ({
        slug: page.slug,
        path: `/compare/${page.slug}`,
        title: `${page.peptideA} vs ${page.peptideB}`,
      })),
    },
    {
      key: "stacks",
      label: "Stacks",
      path: "/stacks",
      description: "Curated peptide protocols.",
      entries: stackPages.map((page) => ({
        slug: page.slug,
        path: `/stacks/${page.slug}`,
        title: page.name,
      })),
    },
    {
      key: "guides",
      label: "Guides",
      path: "/guides",
      description: "How-to dosing and injection guides.",
      entries: guidePages.map((page) => ({
        slug: page.slug,
        path: `/guides/${page.slug}`,
        title: page.title,
      })),
    },
    {
      key: "for",
      label: "For",
      path: "/for",
      description: "Find peptides by condition or concern.",
      entries: forConditionPages.map((page) => ({
        slug: page.slug,
        path: `/for/${page.slug}`,
        title: page.condition,
      })),
    },
    {
      key: "reviews",
      label: "Reviews",
      path: "/reviews",
      description: "Independent peptide reviews.",
      entries: reviewPages.map((page) => ({
        slug: page.slug,
        path: `/reviews/${page.slug}`,
        title: page.h1,
      })),
    },
  ] as const;
}

async function exportPseoIndex() {
  const sections = toPseoIndex();
  const contents = `/* Auto-generated by scripts/export-static-content.ts. */
import type { PseoSection } from "./pseo";

export const pseoSections = ${JSON.stringify(sections, null, 2)} satisfies PseoSection[];
`;

  await fs.writeFile(pseoIndexPath, contents, "utf8");
  console.log(`[content] exported ${sections.length} pseo section indexes`);
}

await fs.mkdir(dataRoot, { recursive: true });
await exportBlogContent();
await exportPseoContent();
await exportPseoIndex();
